### ISSUE TITLE
No ability to recover after suspend ubuntu mode

### ISSUE THREAD

**Issue by snuyanzin** [IsmaelMartinez/teams-for-linux#227] opened 2019-08-14 06:20 UTC
**Describe the bug**
Unable to initialize after suspend mode (ubuntu).
After suspend mode it is not even possible to quit and start again.
It shows only white screen which after several minutes suggests to try again.

The only way to cope with it is `rm -rf ~/.config/teams-for-linux`
**To Reproduce**
1. Go to '...'       start

**Expected behavior**
Should be initialized ok (it was ok in 0.4.0 and earlier)

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [ubuntu 19.0.4]
 - Installation package [deb] 
 - Version [0.6.0]

**Additional context**

**Comment by BenniG82** [comment] 2019-08-14 06:44
This is a duplicate of #225 and #171 
You can try Version 0.6.6, according to @IsmaelMartinez this version should fix the issue. I've installed it just today and I'm hoping it'll really fix the issue

**Comment by snuyanzin** [comment] 2019-08-14 08:01
thanks for quick response but as I see at release page 0.6.6 is marked as not release version and for testing purpose only...

Ok I will try to test with this version

**Comment by IsmaelMartinez** [comment] 2019-08-14 08:12
Hi @snuyanzin , is mark as "testing" release because needs a bit of release notes (also, there where a few people suffering from the blank screen that I wanted them to test it). 

Only thing that you will need to do is to clean you config folder (check known issues) after installing 0.6.6. Thanks @BenniG82 for the quick reply/help!

**Closed by IsmaelMartinez** 2019-08-14 08:12 UTC
