### ISSUE TITLE
Attention span related settings (full-mute, disable app icon animation)

### ISSUE THREAD

**Issue by LeStahL** [IsmaelMartinez/teams-for-linux#1170] opened 2024-04-03 09:50 UTC
**Is your feature request related to a problem? Please describe.**
I'm always frustrated when I'm focused and Teams plays sounds. I already disabled all configurable sounds, but some sounds still play. Also I don't appreciate the icon moving regularly when the window is disabled. I would like the Teams client to not constantly try to grab my attention when it's minimized. I would like to have control over when I use Teams, in order to be able to be "in the zone" more effectively.

**Describe the solution you'd like**
* A setting could full-mute the teams client, as in "It does not play any sounds, ever."
* Another setting could disable the animation of the Teams icon.

**Describe alternatives you've considered**
Usually I mute applications that play unsolicited sounds using the per-application volume mixer of my OS, but Ubuntu desktop seems to have removed this.
I do not think there is an easy solution to prevent applications from showing animations on their icons.

**Additional context**
None.

**Comment by IsmaelMartinez** [comment] 2024-04-04 09:57
have you tried disabling all notifications in the menu ?
![image](https://github.com/IsmaelMartinez/teams-for-linux/assets/430992/f44af393-e2cd-4483-bd3f-3a572220f9bb)

I am not sure if that works anymore in teams-v2 but it should work if you are still using teams-v1

**Comment by jijojosephk** [comment] 2024-04-12 10:26
@LeStahL I think the issue is resolved. Closing for now. Let us know if you need further help.

**Closed by jijojosephk** 2024-04-12 10:26 UTC
Labels: enhancement
