### ISSUE TITLE
Type a message box not in focus

### ISSUE THREAD

**Issue by simonsteiner1984** [IsmaelMartinez/teams-for-linux#503] opened 2021-11-04 09:29 UTC
Click a person in chat, the message box is in focus so i can type without clicking it

**Comment by jijojosephk** [comment] 2021-11-04 15:59
Could you add some details? It would be great if you could use the issue template.

**Comment by simonsteiner1984** [comment] 2021-11-04 16:09
OS: Ubuntu 18.04
I had to update to 1.0.20 and had this issue, used to be ok in a older release

**Comment by jijojosephk** [comment] 2021-11-04 16:59
Thanks for reporting the platform but we're still not sure we understood the problem. Could you make the description a little more clear?

**Comment by simonsteiner1984** [comment] 2021-11-04 17:43
When I click on a person in teams, at bottom of the window is a box where you enter text, that should be in focus so I can type a message. Most of the the time its not in focus so you have to click on it. The official MS teams client works fine.

**Comment by jijojosephk** [comment] 2021-11-04 17:45
Thanks. So are you saying that it used work in older versions?

**Comment by simonsteiner1984** [comment] 2021-11-04 17:47
I think it works in 1.0.6 but that version doesnt load as that had older electron

**Comment by jijojosephk** [comment] 2021-11-04 17:55
Which package you used for installation? deb, snap, flatpak?

**Comment by simonsteiner1984** [comment] 2021-11-04 17:56
deb x86

**Comment by jijojosephk** [comment] 2021-11-04 17:59
Could you try flatpak or snap? I tried on flatpak install and could not reproduce.

**Comment by simonsteiner1984** [comment] 2021-11-05 07:45
I get the issue on teams-for-linux-1.0.20.AppImage

**Comment by simonsteiner1984** [comment] 2021-11-05 07:51
I get the issue using app from sudo snap install teams-for-linux

**Comment by simonsteiner1984** [comment] 2021-11-05 08:28
I think since I have a slower internet connection, the focus is called before the page is rendered

**Comment by jijojosephk** [comment] 2021-11-06 03:33
@simonsteiner1984 So, can we close this if it's not a bug?

**Comment by simonsteiner1984** [comment] 2021-11-06 03:39
It's a bug, can you call focus method after page has finished rendering

**Comment by simonsteiner1984** [comment] 2021-11-06 03:40
Try using the app on a slower internet connection to replicate

**Comment by jijojosephk** [comment] 2021-11-06 03:43
@IsmaelMartinez We don't have much control over that as the script written by Microsoft. But I can have a look at it and see what can be done. @IsmaelMartinez What do you think about this one?

**Comment by IsmaelMartinez** [comment] 2021-11-13 09:40
Apologies for the delay on my reply. I was on holidays. 

We could do some JavaScript checks after loading and trigger a focus event, but I have found that been pretty unreliable (specially as we don't control the Front-end code and Microsoft can just change it a bit and break our "hack")

**Comment by simonsteiner1984** [comment] 2021-11-16 08:02
--onlineOfflineReload=false doesnt helk

**Comment by jijojosephk** [comment] 2022-08-11 17:53
@simonsteiner1984 I'm closing this for now as we're not able to reproduce. You may re-open if you think any help is needed.

**Closed by jijojosephk** 2022-08-11 17:53 UTC
