### ISSUE TITLE
Ubuntu 23.04 share screen not working

### ISSUE THREAD

**Issue by Vagrantin** [IsmaelMartinez/teams-for-linux#999] opened 2023-10-26 03:05 UTC
**Describe the bug**
Using the snap version of Teams-for-linux the share screen is not working.
When I click on the share button then "Screen, Window or tab..", I’m getting this popup
![Screenshot from 2023-10-26 11-19-27](https://github.com/IsmaelMartinez/teams-for-linux/assets/19902259/d1b45e43-8c8f-4501-97f7-a238a7531837)

If I click on the the first button, (others doesn’t seems to do anything )
![Screenshot from 2023-10-26 11-43-50](https://github.com/IsmaelMartinez/teams-for-linux/assets/19902259/0d8dda60-b3b8-4c79-b1eb-33b27665b0bb)

I’m getting this error message.
![Screenshot from 2023-10-26 11-22-41](https://github.com/IsmaelMartinez/teams-for-linux/assets/19902259/0e09f50d-7e1b-488f-81d5-85188601a68f)

I have tested separately the camera it is working, I don’t understand why the screen sharing is trying to access the camera...

As said above I’m using the snap version, i have tested all of the above with all the permissions available in the UI.
![Screenshot from 2023-10-26 11-21-37](https://github.com/IsmaelMartinez/teams-for-linux/assets/19902259/4546e9d7-58f3-4cb4-9811-d6fa58e5224f)

Here is my Ubuntu distribution version details, running on a laptop with an external monitor connected to it.
![Screenshot from 2023-10-26 11-22-04](https://github.com/IsmaelMartinez/teams-for-linux/assets/19902259/bc0dab65-9556-401a-a1df-1cb9b29550a2)

**To Reproduce**
1. On Ubuntu 23.04 install the snap package of Teams-for-linux
2. After login to teams start a "Meeting Now" from the calendar
3. Click on the "Share" button then "Screen, Window or tab.."
4. See error message shared above

**Expected behavior**
I’m expecting to be able to choose to share one of the monitor I have.

**Desktop (please complete the following information):**
 - OS: [Ubunut 23.04]
 - Installation package [snap]
 - Version [1.3.14] ( not tested with other version )

**Additional context**
It is working fine with the Debian package version 1.3.14.

**Comment by mwallnoefer** [comment] 2023-10-30 19:00
Same issue on Ubuntu _22.04.03 LTS_ with Teams-for-Linux _1.3.14_ (Revision 458).

**Comment by norman-knott** [comment] 2023-11-07 07:59
Same on Ubuntu 23.10. This seems to be caused by the lack of Wayland support in teams-for-linux. You have to switch back to X.org.
https://askubuntu.com/questions/1405195/how-to-share-a-screen-in-ms-teams-or-zoom-from-ubuntu-22-04

I have read somewhere that the lack of support could originate from the Electron framework. A newer version might support it.

**Comment by Monkeyfacemoney** [comment] 2023-11-15 08:13
It doesn't work with the version installed with Ubuntu-software center or Snap.
When installed with the .deb package described in this git, it works as expected.

**Comment by norman-knott** [comment] 2023-11-15 10:27
Yes, that's right. Via the .deb package the screen sharing works.

Only a new problem: A shared window is not scaled to the viewers display. Means the if the shared window is bigger than the viewers screen, the presentation cuts it. So the viewer will not see the whole window.

I think this was different before I switched to a Wayland based Ubuntu. And it's a different issue of course.

**Comment by russ-s7** [comment] 2023-11-22 09:44
I'm on Ubuntu 22.04 LTS, with 1.3.23 installed from .deb. Screen sharing works on X.org but not on Wayland. Using Wayland and the setting `global.context.unsafe_mode=true` in Looking Glass (or the extension in @norman-knott's link which does the same) does not work.

Summarising the above comments for clarity: the **only working combination** on Ubuntu at present is to use the **.deb package** AND use **X.org**.

**Comment by norman-knott** [comment] 2023-11-22 10:13
@russ-s7 I didn't try the .deb with Ubuntu 22.04, but on Ubuntu 23.10 it is working on Wayland.

**Comment by russ-s7** [comment] 2023-11-22 11:52
@norman-knott thanks. I have tried again on Wayland and this is what I get:
```
[167526:1122/112218.842192:ERROR:screen_capture_portal_interface.cc(48)] Failed to request session: GDBus.Error:org.freedesktop.DBus.Error.UnknownMethod: No such interface “org.freedesktop.portal.ScreenCast” on object at path /org/freedesktop/portal/desktop
[167526:1122/112218.842210:ERROR:base_capturer_pipewire.cc(81)] ScreenCastPortal failed: 3
```

The mention of Pipewire here reminds me I have a [non-standard audio setup](https://gist.github.com/the-spyke/2de98b22ff4f978ebf0650c90e82027e) for my Bluetooth headset to work - I don't know if this is related. @mwallnoefer you had issues on 22.04 also - was this with the snap or deb?

I tried `sudo apt install xdg-desktop-portal-gnome` then `systemctl --user start xdg-desktop-portal-gnome` as per [this](https://askubuntu.com/questions/1313369/screen-sharing-with-wayland/1398720#1398720) (my system is upgraded from 20.04) but no improvement.

**Comment by preussal** [comment] 2023-12-20 08:37
So with a newly installed Ubuntu 22.04 with 6.5 kernel it works via the .deb installation. 
But when I install it via Snap, screen/window sharing doesn't work.
![image](https://github.com/IsmaelMartinez/teams-for-linux/assets/26431172/a1336957-1a9f-4e04-9038-2a49e8f4bd4f)

**Comment by IsmaelMartinez** [comment] 2023-12-21 10:14
@preussal that indicates that is probably a local system configuration. Either you snap configuration is not fully setup, you aren't giving it the appropriate permissions in the snap app or another linux shenanigans.

**Comment by NaimadTheOne** [comment] 2024-01-08 11:33
I experienced the same issue. After switching from XOrg to Wayland, screen sharing functionality ceased to work. Reinstalling using the Snap store proved ineffective. However, installing the same version from a .deb package resolved the problem. I noticed that the program installed from Snap had diffetent size than the .deb file.

**Comment by jhay06** [comment] 2024-01-11 11:41
any updates on this with the new version 1.4.2 ?

**Comment by IsmaelMartinez** [comment] 2024-01-15 20:15
Can you check if 1.4.3 improve the situation? That area has been reworked in https://github.com/IsmaelMartinez/teams-for-linux/pull/1064 .  pre-release incomming

**Comment by IsmaelMartinez** [comment] 2024-01-16 22:02
closing as this has been reported working again in 1.4.3. Please do shout if it is not working and I can re-open

**Closed by IsmaelMartinez** 2024-01-16 22:02 UTC

**Comment by dfenerski** [comment] 2024-07-04 08:36
yeah this is still very much open also on 24.04

**Comment by Djradox** [comment] 2025-01-09 16:41
Hi, same problem here with app center

sudo snap connect teams-for-linux:audio-record
This fixed my microphone problem

sudo snap connect teams-for-linux:wayland
This is fixing the error message for sharing screen but no popup to allow us to choose what i want to share... Any solution ?

**Comment by jijojosephk** [comment] 2025-01-10 01:41
@Djradox please use `flatpak` version.
