### ISSUE TITLE
Markdown does not work in private chats

### ISSUE THREAD

**Issue by Jaffex** [IsmaelMartinez/teams-for-linux#795] opened 2023-05-03 06:54 UTC
**Describe the bug**
When I write a message in the composer of the teams section, markdown gets formatted as I type.
If I type markdown in a private chat however, nothing happens when entering markdown.

**To Reproduce**
1. Go to a private chat with someone
2. Enter "This is a \*\*test\*\* \[link\]\(https://example.com) "
3. The word "test" does not get turned bold and the link does not appear as an inline link

**Expected behavior**
While typing, I would expect the markdown code to be formatted

**Screenshots**
The composer in a teams-channel, where markdown gets formatted:
![Works](https://user-images.githubusercontent.com/31133207/235849161-abb8c1ad-96fe-4efe-9576-eac9640de8d2.gif)

The composer in a pricate chat, where markdown does not get formatted:
![Doesn't work](https://user-images.githubusercontent.com/31133207/235849206-e0bb8b74-21d4-4d09-907b-c54db415a0a6.gif)

**Desktop (please complete the following information):**
 - OS: Fedora 26
 - Installation package: via flatpak
 - Version: 1.0.80

**Additional context**
Links seem to work in private chats sometimes, but not always - I noticed that when I would type url manually, it works, but when I paste it from the clipboard, it doesn't.
In the teams-composer however, it works no matter if I paste from clipboard or type it manually.

**Comment by jijojosephk** [comment] 2023-05-04 08:24
It's the same behaviour in https://teams.microsoft.com/ also. So it's not a bug in this app. Sorry!

**Comment by jijojosephk** [comment] 2023-05-04 08:25
Closing this. You may re-open if you think the issue can be fixed or it is fixed in web version and not in this app.

**Closed by jijojosephk** 2023-05-04 08:25 UTC
