### ISSUE TITLE
Installing Teams for Linxu on OpenSuse 15.5; nothing provides libXtxt.

### ISSUE THREAD

**Issue by linxpatrick** [IsmaelMartinez/teams-for-linux#1183] opened 2024-04-09 01:26 UTC
I'm trying to install teams-for-linux v1.4.21-1 and two older versions on OpenSuse Leap 15.5 x86_64 using the rpm package. The package manager says that libXtst is not provided. Upon checking, libXtst6 v1.2.3-1.24 is installed on the system. Please fix this issue.

**Comment by ChristoSnake** [comment] 2024-04-09 08:35
I get warnings for two packages with the rpm install on openSUSE Tumbleweed:

`error: Failed dependencies:`
`        libuuid is needed by teams-for-linux-1.4.21-1.x86_64`
`        nss is needed by teams-for-linux-1.4.21-1.x86_64`

After verifying that they're both installed I've run my rpm installations with the `--nodeps` switch.   So far nothing has broken, and I spend 50% of my day using Teams (calls, screen shares, file uploads, etc).

**Comment by IsmaelMartinez** [comment] 2024-04-09 09:04
Hi @linxpatrick , please use the template when opening issues and provide as much information as possible on your installation steps, etc.

Also follow @ChristoSnake suggestion and see if that works for you. Thank you both!

**Comment by linxpatrick** [comment] 2024-04-09 17:42
It looks like the --nodeps switch worked. Thank you.

*/Patrick Headley/*
Linx Consulting, Inc.
(303) 916-5522
***@***.***
www.linxco-inc.com

**Comment by jijojosephk** [comment] 2024-04-11 13:28
closing as the solution provided by @ChristoSnake works! Thanks @ChristoSnake

**Closed by jijojosephk** 2024-04-11 13:28 UTC

**Comment by linxpatrick** [comment] 2024-04-11 20:59
Was hoping that the case wouldn't have been closed because the solution 
is just a work-around. The actual solution will be to fix the 
dependencies in the package so that it will install without issues.

*/Patrick Headley/*
Linx Consulting, Inc.
(303) 916-5522
***@***.***
www.linxco-inc.com

**Comment by IsmaelMartinez** [comment] 2024-04-11 21:40
The problem is probably with electron (the system we use to encapsulated
the browser) or electron-builder (the system we use to package the app). If
you can check around their GitHub repos and see if there is any
configuration we should change, that would be grand. But I will be
surprised if we can do much.

If you find something and/or know of a fix, do let us know and/or open a PR
with it. Happy to give some guidance.

We close issues when there is a workaround and/or we can't do much to keep
them manageable. Hope you understand.

**Comment by linxpatrick** [comment] 2024-04-11 23:37
I understand. Appreciate the feedback.

*/Patrick Headley/*
Linx Consulting, Inc.
(303) 916-5522
***@***.***
www.linxco-inc.com
