### ISSUE TITLE
Wrong time zone set in meeting scheduler

### ISSUE THREAD

**Issue by kente2t** [IsmaelMartinez/teams-for-linux#1106] opened 2024-02-15 16:47 UTC
**Describe the bug**
My local time and the time setting of my computer is UTC+1. The Teams-for-linux calendar shows the local time, red current time line is position of my local time. But when I click in the calendar to schedule a new meeting the selected time zone in this new window is UTC. I think you can call this a bug as it is very easy to forget to switch to the correct time zone and schedule the meeting to the wrong time.

**To Reproduce**
1. Open calendar in Teams-for-linux
2. Click in the calendar to schedule a new meeting
3. Notice that the meeting will be scheduled using UTC not the local time (must be corrected via upper list box)
4. If you now click to send invitation to participants it is too late to realize that wrong time zone was used.

**Expected behavior**
The new meeting scheduler should start with the local time of the computer selected.

**Screenshots**
Two screenshots appended.

**Desktop (please complete the following information):**
 - OS: Ubuntu 22.04
 - Installation package: deb installed from teamsforlinux.de repository.
 - Version: teams-for-linux ver. 1.4.10

**Additional context**
![Teams_new_meeting_window](https://github.com/IsmaelMartinez/teams-for-linux/assets/56929472/eed3d4da-7d7b-48df-a5a6-0f6894f86b65)
![Teams-for-linux_calendar](https://github.com/IsmaelMartinez/teams-for-linux/assets/56929472/3487e3c8-75e9-49d6-bb28-4d261f801b88)

**Comment by jijojosephk** [comment] 2024-02-16 04:00
It's duplicate of #1063. We can't have a fix as it's `electron` issue. But there may be some workarounds. Please check #1063

**Closed by jijojosephk** 2024-02-16 04:00 UTC
Labels: duplicate
