### ISSUE TITLE
Ubuntu 22.04 wayland unable to share screen

### ISSUE THREAD

**Issue by yudjinn** [IsmaelMartinez/teams-for-linux#629] opened 2022-10-13 16:09 UTC
**Describe the bug**
Unable to share screen from the deb package. It does create the "screen is being shared" notification in the gnome task bar, but no image is shown to viewer. No black screen, nothing. My syslog shows 
`
 Oct 13 10:57:51 101451 xdg-desktop-por[564390]: Unhandled parent window type 
Oct 13 10:57:51 101451 xdg-desktop-por[564390]: Failed to associate portal window with parent window 
Oct 13 10:58:03 101451 xdg-desktop-por[564390]: Unhandled parent window type 
Oct 13 10:58:03 101451 xdg-desktop-por[564390]: Failed to associate portal window with parent window 
`

**To Reproduce**
1. Install newest deb package using `sudo dpkg -i`
2. Login
3. Start meeting and click share screen
4. UI pops up to choose window
5. No matter what is selected, nothing is streamed to viewer.

**Expected behavior**
screen is shared

**Screenshots**

**Desktop (please complete the following information):**
 - ubuntu 22.04
 - deb
 - Version 1.0.45

**Additional context**
should note that using the debug level flag shows:
`
[2210227:1013/110507.008457:ERROR:browser_main_loop.cc(269)] Gtk: gtk_widget_add_accelerator: assertion 'GTK_IS_ACCEL_GROUP (accel_group)' failed
[2210227:1013/110507.008532:ERROR:browser_main_loop.cc(269)] Gtk: gtk_widget_add_accelerator: assertion 'GTK_IS_ACCEL_GROUP (accel_group)' failed
[2210227:1013/110507.008556:ERROR:browser_main_loop.cc(269)] Gtk: gtk_widget_add_accelerator: assertion 'GTK_IS_ACCEL_GROUP (accel_group)' failed
[2210227:1013/110507.008577:ERROR:browser_main_loop.cc(269)] Gtk: gtk_widget_add_accelerator: assertion 'GTK_IS_ACCEL_GROUP (accel_group)' failed
[2210227:1013/110507.008603:ERROR:browser_main_loop.cc(269)] Gtk: gtk_widget_add_accelerator: assertion 'GTK_IS_ACCEL_GROUP (accel_group)' failed
libva error: vaGetDriverNameByIndex() failed with unknown libva error, driver_name = (null)
[DEBUG] did-finish-load
[DEBUG] did-finish-load
`
on startup but no errors when attempting to screenshare

This was a machine on 20.04 that I upgraded (not clean install) to 22.04, and had a few issues but I validated I am missing no packages from a clean install

**Comment by jijojosephk** [comment] 2022-10-14 04:38
If you have tray icon, can you click on `debug` and see what's happening when you click on screenshare? There will be many warning, logs and errors. Make sure you clear everything just before clicking on screenshare. If it's has something to do with the script you won't see logs in the terminal.

**Comment by pallebone** [comment] 2022-10-14 12:56
I have tried to do this but have not been able to find a solution to the issue or enable it in any way with things like passing arguments (enable-webrtc-pipewire-capturer) or installing libraries. Still the error persists that : 
"One of following libraries is missing on your system:
 - PipeWire (libpipewire-0.3.so.0)
 - drm (libdrm.so.2)"

unsure how to proceed. Nothing I try is able to resolve.

**Comment by pallebone** [comment] 2022-10-14 12:58
@yudjinn I actually installed the deb version yesterday for the first time and it worked for me... Im thinking something must have changed on your system because it should be working.

**Comment by yudjinn** [comment] 2022-10-14 14:44
@pallebone i agree, I had the same problem on 1.0.41 and I have colleagues that have no issue. I'm assuming something broke with my upgrade from 20.04 and want to understand and resolve it.

**Comment by jijojosephk** [comment] 2022-10-14 16:57
Do you have a dedicated graphics card?

**Comment by DGrothe-PhD** [comment] 2022-10-14 17:47
> @pallebone i agree, I had the same problem on 1.0.41 and I have colleagues that have no issue. I'm assuming something broke with my upgrade from 20.04 and want to understand and resolve it.

Yes, with 20.04 screen sharing worked fine. It affects 21.04 as well and (web) screen sharing itself, not just for teams, but iirc for other browser-based screen-sharing applications as well, see https://askubuntu.com/questions/1313369/screen-sharing-with-wayland . You may try those workarounds.

**Comment by jijojosephk** [comment] 2022-10-15 02:56
@yudjinn can you try `export LIBVA_DRIVER_NAME=iHD` and run `teams-for-linux` from there?

**Comment by yudjinn** [comment] 2022-10-15 03:43
> @yudjinn can you try `export LIBVA_DRIVER_NAME=iHD` and run `teams-for-linux` from there?

I have tried that (as well as i986), no change in behavior.

**Comment by jijojosephk** [comment] 2022-10-15 09:57
@yudjinn yeah, then the upgrade didn't work just right. Do yours and your friend's OS kernel versions differ? I'm not sure if that matters. Also you can try other screen sharing or screen recording apps like Kazam or something similar and see if your'e facing any issues there. Looks like it's not easily identifiable by the community, you might wanna try really hard to identify the cause.

**Comment by yudjinn** [comment] 2022-10-15 14:03
Using the browser i am able to share, but only the browser window so nothing outside of that. If I switch to xorg i can share just fine using the desktop client. It's only on Wayland that this is breaking. Also, we are on the same kernel yes.

**Comment by jijojosephk** [comment] 2022-10-15 14:10
Can journalctl help you in anyway?

**Comment by jijojosephk** [comment] 2022-10-16 02:30
`journalctl -b | grep teams-for-linux` anything there?

**Comment by yudjinn** [comment] 2022-10-17 16:06
sorry, was away for the weekend, heres journal:
`Oct 14 12:40:35 101451 ubuntu-appindicators@ubuntu.com[3096]: unable to update icon for teams-for-linux1
Oct 14 12:40:36 101451 teams-for-linux.desktop[28315]: libva error: vaGetDriverNameByIndex() failed with unknown libva error, driver_name = (null)
Oct 14 12:40:38 101451 teams-for-linux.desktop[28315]: [28315:1014/124038.051088:ERROR:gl_surface_presentation_helper.cc(260)] GetVSyncParametersIfAvailable() failed for 1 times!
Oct 14 12:40:40 101451 teams-for-linux.desktop[28315]: [28315:1014/124040.134246:ERROR:gl_surface_presentation_helper.cc(260)] GetVSyncParametersIfAvailable() failed for 2 times!
Oct 14 12:41:06 101451 teams-for-linux.desktop[28315]: [28315:1014/124106.041138:ERROR:gl_surface_presentation_helper.cc(260)] GetVSyncParametersIfAvailable() failed for 3 times!
Oct 14 12:41:11 101451 teams-for-linux.desktop[28765]: [28765:1014/124111.950193:ERROR:browser_main_loop.cc(269)] Gtk: gtk_widget_add_accelerator: assertion 'GTK_IS_ACCEL_GROUP (accel_group)' failed
Oct 14 12:41:11 101451 teams-for-linux.desktop[28765]: [28765:1014/124111.950328:ERROR:browser_main_loop.cc(269)] Gtk: gtk_widget_add_accelerator: assertion 'GTK_IS_ACCEL_GROUP (accel_group)' failed
Oct 14 12:41:11 101451 teams-for-linux.desktop[28765]: [28765:1014/124111.950373:ERROR:browser_main_loop.cc(269)] Gtk: gtk_widget_add_accelerator: assertion 'GTK_IS_ACCEL_GROUP (accel_group)' failed
Oct 14 12:41:11 101451 teams-for-linux.desktop[28765]: [28765:1014/124111.950410:ERROR:browser_main_loop.cc(269)] Gtk: gtk_widget_add_accelerator: assertion 'GTK_IS_ACCEL_GROUP (accel_group)' failed
Oct 14 12:41:11 101451 teams-for-linux.desktop[28765]: [28765:1014/124111.950450:ERROR:browser_main_loop.cc(269)] Gtk: gtk_widget_add_accelerator: assertion 'GTK_IS_ACCEL_GROUP (accel_group)' failed
Oct 14 12:41:11 101451 ubuntu-appindicators@ubuntu.com[3096]: unable to update icon for teams-for-linux1
Oct 14 12:41:12 101451 teams-for-linux.desktop[28825]: libva error: vaGetDriverNameByIndex() failed with unknown libva error, driver_name = (null)
Oct 14 12:41:16 101451 teams-for-linux.desktop[28825]: [28825:1014/124116.471319:ERROR:gl_surface_presentation_helper.cc(260)] GetVSyncParametersIfAvailable() failed for 1 times!
Oct 14 12:41:23 101451 teams-for-linux.desktop[28825]: [28825:1014/124123.273056:ERROR:gl_surface_presentation_helper.cc(260)] GetVSyncParametersIfAvailable() failed for 2 times!
Oct 14 12:41:24 101451 teams-for-linux.desktop[28825]: [28825:1014/124124.561995:ERROR:gl_surface_presentation_helper.cc(260)] GetVSyncParametersIfAvailable() failed for 3 times!
Oct 14 12:45:05 101451 ubuntu-appindicators@ubuntu.com[3096]: unable to update icon for teams-for-linux1
Oct 14 12:45:14 101451 teams-for-linux.desktop[34258]: [34258:1014/124514.334997:ERROR:browser_main_loop.cc(269)] Gtk: gtk_widget_add_accelerator: assertion 'GTK_IS_ACCEL_GROUP (accel_group)' failed
Oct 14 12:45:14 101451 teams-for-linux.desktop[34258]: [34258:1014/124514.335281:ERROR:browser_main_loop.cc(269)] Gtk: gtk_widget_add_accelerator: assertion 'GTK_IS_ACCEL_GROUP (accel_group)' failed
Oct 14 12:45:14 101451 teams-for-linux.desktop[34258]: [34258:1014/124514.335357:ERROR:browser_main_loop.cc(269)] Gtk: gtk_widget_add_accelerator: assertion 'GTK_IS_ACCEL_GROUP (accel_group)' failed
Oct 14 12:45:14 101451 teams-for-linux.desktop[34258]: [34258:1014/124514.335423:ERROR:browser_main_loop.cc(269)] Gtk: gtk_widget_add_accelerator: assertion 'GTK_IS_ACCEL_GROUP (accel_group)' failed
Oct 14 12:45:14 101451 teams-for-linux.desktop[34258]: [34258:1014/124514.335499:ERROR:browser_main_loop.cc(269)] Gtk: gtk_widget_add_accelerator: assertion 'GTK_IS_ACCEL_GROUP (accel_group)' failed
Oct 14 12:45:14 101451 ubuntu-appindicators@ubuntu.com[3096]: unable to update icon for teams-for-linux1
Oct 14 12:45:14 101451 teams-for-linux.desktop[34319]: libva error: vaGetDriverNameByIndex() failed with unknown libva error, driver_name = (null)
Oct 14 12:45:38 101451 teams-for-linux.desktop[34319]: [34319:1014/124538.980804:ERROR:gl_surface_presentation_helper.cc(260)] GetVSyncParametersIfAvailable() failed for 1 times!
Oct 14 12:45:38 101451 teams-for-linux.desktop[34319]: [34319:1014/124538.989745:ERROR:gl_surface_presentation_helper.cc(260)] GetVSyncParametersIfAvailable() failed for 2 times!
Oct 14 12:45:38 101451 teams-for-linux.desktop[34319]: [34319:1014/124538.990040:ERROR:gl_surface_presentation_helper.cc(260)] GetVSyncParametersIfAvailable() failed for 3 times!`

**Comment by jgmGit** [comment] 2022-10-26 12:43
I have the same issue as well.

```
teams-for-linux.desktop[118095]: [118095:1026/141419.755308:ERROR:browser_main_loop.cc(269)] Gtk: gtk_widget_add_accelerator: assertion 'GTK_IS_ACCEL_GROUP (accel_group)' failed
teams-for-linux.desktop[118095]: [118095:1026/141419.755477:ERROR:browser_main_loop.cc(269)] Gtk: gtk_widget_add_accelerator: assertion 'GTK_IS_ACCEL_GROUP (accel_group)' failed
teams-for-linux.desktop[118095]: [118095:1026/141419.755537:ERROR:browser_main_loop.cc(269)] Gtk: gtk_widget_add_accelerator: assertion 'GTK_IS_ACCEL_GROUP (accel_group)' failed
teams-for-linux.desktop[118095]: [118095:1026/141419.755600:ERROR:browser_main_loop.cc(269)] Gtk: gtk_widget_add_accelerator: assertion 'GTK_IS_ACCEL_GROUP (accel_group)' failed
teams-for-linux.desktop[118095]: [118095:1026/141419.755653:ERROR:browser_main_loop.cc(269)] Gtk: gtk_widget_add_accelerator: assertion 'GTK_IS_ACCEL_GROUP (accel_group)' failed
teams-for-linux.desktop[118248]: libva error: vaGetDriverNameByIndex() failed with unknown libva error, driver_name = (null)
teams-for-linux.desktop[118248]: [118248:1026/141628.396681:ERROR:gl_surface_presentation_helper.cc(260)] GetVSyncParametersIfAvailable() failed for 1 times!
teams-for-linux.desktop[118248]: [118248:1026/141644.367744:ERROR:gl_surface_presentation_helper.cc(260)] GetVSyncParametersIfAvailable() failed for 2 times!
teams-for-linux.desktop[118248]: [118248:1026/141644.380446:ERROR:gl_surface_presentation_helper.cc(260)] GetVSyncParametersIfAvailable() failed for 3 times!
teams-for-linux.desktop[118250]: [118250:1026/141752.604485:ERROR:socket_tcp.cc(328)] Error when reading from TCP socket: -101
teams-for-linux.desktop[124852]: [124852:1026/142459.374430:ERROR:browser_main_loop.cc(269)] Gtk: gtk_widget_add_accelerator: assertion 'GTK_IS_ACCEL_GROUP (accel_group)' failed
teams-for-linux.desktop[124852]: [124852:1026/142459.374558:ERROR:browser_main_loop.cc(269)] Gtk: gtk_widget_add_accelerator: assertion 'GTK_IS_ACCEL_GROUP (accel_group)' failed
teams-for-linux.desktop[124852]: [124852:1026/142459.374598:ERROR:browser_main_loop.cc(269)] Gtk: gtk_widget_add_accelerator: assertion 'GTK_IS_ACCEL_GROUP (accel_group)' failed
teams-for-linux.desktop[124852]: [124852:1026/142459.374634:ERROR:browser_main_loop.cc(269)] Gtk: gtk_widget_add_accelerator: assertion 'GTK_IS_ACCEL_GROUP (accel_group)' failed
teams-for-linux.desktop[124852]: [124852:1026/142459.374668:ERROR:browser_main_loop.cc(269)] Gtk: gtk_widget_add_accelerator: assertion 'GTK_IS_ACCEL_GROUP (accel_group)' failed
teams-for-linux.desktop[124919]: libva error: vaGetDriverNameByIndex() failed with unknown libva error, driver_name = (null)
teams-for-linux.desktop[124919]: [124919:1026/142501.924839:ERROR:gl_surface_presentation_helper.cc(260)] GetVSyncParametersIfAvailable() failed for 1 times!
teams-for-linux.desktop[124919]: [124919:1026/142514.221742:ERROR:gl_surface_presentation_helper.cc(260)] GetVSyncParametersIfAvailable() failed for 2 times!
teams-for-linux.desktop[124919]: [124919:1026/142514.232358:ERROR:gl_surface_presentation_helper.cc(260)] GetVSyncParametersIfAvailable() failed for 3 times!

```

Operating System: Manjaro Linux                   
Kernel: Linux 5.15.74-3-MANJARO
Architecture: x86-64
Hardware Vendor: Lenovo
Hardware Model: ThinkPad E480

**Comment by joaquinodz** [comment] 2022-10-26 13:00
I managed to make it work in Google Chrome by going to `chrome://flags/#enable-webrtc-pipewire-capturer` and setting it to `Enabled`.

**Comment by jgmGit** [comment] 2022-10-26 16:34
> I managed to make it work in Google Chrome by going to `chrome://flags/#enable-webrtc-pipewire-capturer` and setting it to `Enabled`.

@joaquinodz  I tried the same. It didn't help

**Comment by pallebone** [comment] 2022-10-26 20:19
> I managed to make it work in Google Chrome by going to `chrome://flags/#enable-webrtc-pipewire-capturer` and setting it to `Enabled`.

Did that fix the snap package or just chrome?

**Comment by joaquinodz** [comment] 2022-10-26 20:21
> > I managed to make it work in Google Chrome by going to `chrome://flags/#enable-webrtc-pipewire-capturer` and setting it to `Enabled`.
> 
> Did that fix the snap package or just chrome?

Just Chrome. I'm using Fedora 36

**Comment by pallebone** [comment] 2022-10-26 20:31
Im glad you got teams working in chrome via ms website, that is great news, but Im confused as to how this is related to the teams-for-linux package. Perhaps clarify what clue this gives us in fixing the deb or snap package?

**Comment by joaquinodz** [comment] 2022-10-29 00:47
> Im glad you got teams working in chrome via ms website, that is great news, but Im confused as to how this is related to the teams-for-linux package. Perhaps clarify what clue this gives us in fixing the deb or snap package?

I thought there was something like the chrome:flags in electron that could be enabled by default to fix this 
i don't know much about Electron so i apologize in advance if this isn't relevant ^^'

**Comment by pallebone** [comment] 2022-10-29 14:19
> > Im glad you got teams working in chrome via ms website, that is great news, but Im confused as to how this is related to the teams-for-linux package. Perhaps clarify what clue this gives us in fixing the deb or snap package?
> 
> I thought there was something like the chrome:flags in electron that could be enabled by default to fix this i don't know much about Electron so i apologize in advance if this isn't relevant ^^'

Interesting. I dont know either.

**Comment by IsmaelMartinez** [comment] 2022-11-03 21:02
did you try with another package? like deb or rpm? snap installations can be a bit iffy. Thanks

**Comment by yudjinn** [comment] 2022-11-07 00:54
I ended up just fresh installing and it works fine. Was unable to figure out what was causing my issues. I used the base install, not snap

**Comment by jgmGit** [comment] 2022-11-07 15:50
I switched over to Ubuntu 22.10 with Wayland and there it works properly. I can share the screen etc.

I think the problem, when I installed Manjaro was maybe because of the missing pipe-wire installation. I am not 100 percent sure of this. But I suspect this.

**Comment by yudjinn** [comment] 2022-11-07 16:29
I definitely had pipe wire, so I don't know if that was the same issue

**Comment by enricojonas** [comment] 2022-12-07 09:44
Same issue here, screen sharing when installing with snap is not working. Screen sharing dialog pops up but when you select something it just doesn't share it. I have now re-installed 1.0.46 .deb package and screen sharing works on Ubuntu 22.10 under Wayland. Got also the new Teams UI, some good improvements have been done.

**Comment by IsmaelMartinez** [comment] 2022-12-07 13:43
It must be something todo with the permissions or pipewire. strange but glad its working with the deb package.

**Comment by enricojonas** [comment] 2022-12-07 14:01
Yes in a way it's working. However I just tried and it seems that I cannot stop sharing my screen... It was still showing the screen sharing icon on the top right (Ubuntu bar, system icon), so I guess it was still sharing in some way.

**Comment by DerXteMensch** [comment] 2022-12-21 13:12
I can confirm that while using the deb package, it works. When using the snap version, it doesn't. Working with Ubuntu 22.04.

**Comment by zeitounator** [comment] 2023-01-14 09:35
The .deb package does not work for me. When I click on screen sharing, nothing is shown. But if I do this while a screen sharing is ongoing from an other participant, the screen sharing stops as if I started to take it over but never succeeded.

Currently, I'm exploring the error reported by libva to see if this would fix the problem and there is something I quite don't understand. Here is where I am.

1. I was seeing in my teams-for-linux output the following error: `libva error: vaGetDriverNameByIndex() failed with unknown libva error, driver_name = (null)`
2. I ran `vainfo` for my user which was giving the folllowing output
```none
$ vainfo
libva info: VA-API version 1.14.0
libva info: Trying to open /usr/lib/x86_64-linux-gnu/dri/iHD_drv_video.so
libva info: Found init function __vaDriverInit_1_7
libva error: /usr/lib/x86_64-linux-gnu/dri/iHD_drv_video.so init failed
libva info: va_openDriver() returns 1
libva info: Trying to open /usr/lib/x86_64-linux-gnu/dri/i965_drv_video.so
libva info: Found init function __vaDriverInit_1_10
libva info: va_openDriver() returns 0
vainfo: VA-API version: 1.14 (libva 2.12.0)
vainfo: Driver version: Intel i965 driver for Intel(R) Haswell Desktop - 2.4.1
vainfo: Supported profile and entrypoints
      VAProfileMPEG2Simple            :	VAEntrypointVLD
      VAProfileMPEG2Simple            :	VAEntrypointEncSlice
      VAProfileMPEG2Main              :	VAEntrypointVLD
      VAProfileMPEG2Main              :	VAEntrypointEncSlice
      VAProfileH264ConstrainedBaseline:	VAEntrypointVLD
      VAProfileH264ConstrainedBaseline:	VAEntrypointEncSlice
      VAProfileH264Main               :	VAEntrypointVLD
      VAProfileH264Main               :	VAEntrypointEncSlice
      VAProfileH264High               :	VAEntrypointVLD
      VAProfileH264High               :	VAEntrypointEncSlice
      VAProfileH264MultiviewHigh      :	VAEntrypointVLD
      VAProfileH264MultiviewHigh      :	VAEntrypointEncSlice
      VAProfileH264StereoHigh         :	VAEntrypointVLD
      VAProfileH264StereoHigh         :	VAEntrypointEncSlice
      VAProfileVC1Simple              :	VAEntrypointVLD
      VAProfileVC1Main                :	VAEntrypointVLD
      VAProfileVC1Advanced            :	VAEntrypointVLD
      VAProfileNone                   :	VAEntrypointVideoProc
      VAProfileJPEGBaseline           :	VAEntrypointVLD
```
3. Following some [instructions I could find on AskUbuntu](https://askubuntu.com/questions/1395620/chrome-libva-error-usr-lib-x86-64-linux-gnu-dri-ihd-drv-video-so-init-failed), I removed the unnecessary livba drivers provided by `intel-media-va-driver`, `intel-media-va-driver-non-free` (i.e. `apt remove --purge`).
4. Following [@jijojosephk advice](https://github.com/IsmaelMartinez/teams-for-linux/issues/629#issuecomment-1279641817), I've set `LIBVA_DRIVER_NAME=i965` in my environment. Here's the new `vainfo` output after the above steps:
```none
$ vainfo 
libva info: VA-API version 1.14.0
libva info: User environment variable requested driver 'i965'
libva info: Trying to open /usr/lib/x86_64-linux-gnu/dri/i965_drv_video.so
libva info: Found init function __vaDriverInit_1_10
libva info: va_openDriver() returns 0
vainfo: VA-API version: 1.14 (libva 2.12.0)
vainfo: Driver version: Intel i965 driver for Intel(R) Haswell Desktop - 2.4.1
vainfo: Supported profile and entrypoints
      VAProfileMPEG2Simple            :	VAEntrypointVLD
      VAProfileMPEG2Simple            :	VAEntrypointEncSlice
      VAProfileMPEG2Main              :	VAEntrypointVLD
      VAProfileMPEG2Main              :	VAEntrypointEncSlice
      VAProfileH264ConstrainedBaseline:	VAEntrypointVLD
      VAProfileH264ConstrainedBaseline:	VAEntrypointEncSlice
      VAProfileH264Main               :	VAEntrypointVLD
      VAProfileH264Main               :	VAEntrypointEncSlice
      VAProfileH264High               :	VAEntrypointVLD
      VAProfileH264High               :	VAEntrypointEncSlice
      VAProfileH264MultiviewHigh      :	VAEntrypointVLD
      VAProfileH264MultiviewHigh      :	VAEntrypointEncSlice
      VAProfileH264StereoHigh         :	VAEntrypointVLD
      VAProfileH264StereoHigh         :	VAEntrypointEncSlice
      VAProfileVC1Simple              :	VAEntrypointVLD
      VAProfileVC1Main                :	VAEntrypointVLD
      VAProfileVC1Advanced            :	VAEntrypointVLD
      VAProfileNone                   :	VAEntrypointVideoProc
      VAProfileJPEGBaseline           :	VAEntrypointVLD
```
5. But now I get a new error when launching a fresh teams for linux which seems to fail intializing the driver despite vainfo reporting everything looks fine
```none
$ teams-for-linux --trace-warnings --clearStorage
libva error: /usr/lib/x86_64-linux-gnu/dri/i965_drv_video.so init failed
[3577107:0114/103350.106586:ERROR:browser_main_loop.cc(269)] Gtk: gtk_widget_add_accelerator: assertion 'GTK_IS_ACCEL_GROUP (accel_group)' failed
[3577107:0114/103350.106825:ERROR:browser_main_loop.cc(269)] Gtk: gtk_widget_add_accelerator: assertion 'GTK_IS_ACCEL_GROUP (accel_group)' failed
[3577107:0114/103350.106929:ERROR:browser_main_loop.cc(269)] Gtk: gtk_widget_add_accelerator: assertion 'GTK_IS_ACCEL_GROUP (accel_group)' failed
[3577107:0114/103350.107002:ERROR:browser_main_loop.cc(269)] Gtk: gtk_widget_add_accelerator: assertion 'GTK_IS_ACCEL_GROUP (accel_group)' failed
[3577107:0114/103350.107073:ERROR:browser_main_loop.cc(269)] Gtk: gtk_widget_add_accelerator: assertion 'GTK_IS_ACCEL_GROUP (accel_group)' failed
[3577223:0114/103355.030827:ERROR:gl_surface_presentation_helper.cc(260)] GetVSyncParametersIfAvailable() failed for 1 times!
[3577223:0114/103404.757674:ERROR:gl_surface_presentation_helper.cc(260)] GetVSyncParametersIfAvailable() failed for 2 times!

```

**Comment by Maher4Ever** [comment] 2023-02-03 08:58
I can also confirm that on Ubuntu 22.10 screen sharing doesn't work when installing through `snap`. Switching to the `deb` package from the release page resolved the issue. Both packages are at version `1.0.49`.

**Comment by zeitounator** [comment] 2023-02-11 15:40
I have strictly no idea what has changed on my system since I posted my above comment but I tried screen sharing yesterday and it now works with the deb package.

**Comment by jijojosephk** [comment] 2023-05-02 02:15
@yudjinn can you confirm if this is working now? There are issues related to `snap`. #765 Closing this for now. Re-open if you think deb also having the issue. I have not seen people reporting issues with deb or other native packages.

**Closed by jijojosephk** 2023-05-02 02:15 UTC
Labels: question, not an issue, ubuntu

**Comment by celvin** [comment] 2023-06-03 20:32
still can't share desktop without disabling Wayland :(

**Comment by jijojosephk** [comment] 2023-06-05 06:15
@celvin  if the problem you're facing on `snap` ? the we suggest you to switch to another package.
