### ISSUE TITLE
Share sound from your computer

### ISSUE THREAD

**Issue by luiser8** [IsmaelMartinez/teams-for-linux#911] opened 2023-08-03 12:14 UTC
You can include audio from your device while you're sharing content in a meeting. You'll want to do this if you're playing a video as part of a presentation, for example. Read on to learn how.
https://support.microsoft.com/en-au/office/share-sound-from-your-computer-in-microsoft-teams-meetings-or-live-events-dddede9f-e3d0-4330-873a-fa061a0d8e3b#:~:text=Select%20Share%20Tray%20%3E%20Screen%2C%20window,coming%20from%20the%20entire%20computer.

Desktop (please complete the following information):
OS: Fedora 38 KDE Plasma 5.27.6
Installation .rpm
Version latest

**Comment by Alex-Bujorianu** [comment] 2023-11-09 12:48
Any updates on this? This is an important feature.

**Comment by mahihossain** [comment] 2023-12-01 07:00
> You can include audio from your device while you're sharing content in a meeting. You'll want to do this if you're playing a video as part of a presentation, for example. Read on to learn how. https://support.microsoft.com/en-au/office/share-sound-from-your-computer-in-microsoft-teams-meetings-or-live-events-dddede9f-e3d0-4330-873a-fa061a0d8e3b#:~:text=Select%20Share%20Tray%20%3E%20Screen%2C%20window,coming%20from%20the%20entire%20computer.
> 
> Desktop (please complete the following information): OS: Fedora 38 KDE Plasma 5.27.6 Installation .rpm Version latest

I would also "up vote" for it. In my case the desktop app was not much of a use in a presentation because of this issue. One can do this in PWA. I would say this is not even an "enhancement", rather a very necessary feature! 

Thanks all for the valuable work!

**Comment by IsmaelMartinez** [comment] 2023-12-12 22:13
can any of you confirm if this works in the web version?, If it does, it might be some electron shenanigans.

**Comment by mahihossain** [comment] 2023-12-13 06:06
> can any of you confirm if this works in the web version?, If it does, it might be some electron shenanigans.

Yes, I can confirm that. In web version, when you share there is a toggle button also to share the sound of any opnened tab in the browser. So if you have a video or audio in a presentation opened in the browser, you can share it and the sound would be shared. 

However the browser doesn't allow you to share sound from other windows outside of the opened browser tabs. So if you are presenting from you computer you can not share your sound. In that case the toggel button is there but disabled. That a is pain but it is better that having no option at all. 

In the Mac or Windows desktop app one can share all the sounds one wants! In the linux desktop app there is no toggle button for it. I have tried to give the app all the permissions...it still doesn't have any button which says "include system sound". That would be great inhancement in my opinion.

**Comment by IsmaelMartinez** [comment] 2023-12-18 10:35
I suspect that then sharing the teams-for-linux will share your sound, but nothing else. I suspect is a permissions issue not allowing to get hold of the sound that is outside of the window context. But this is just a wild guess.

**Comment by luiser8** [comment] 2023-12-18 17:33
I hope they can add this functionality that exists in the web version. It is very helpful for these cases of sharing the screen and we need system audio.

**Comment by IsmaelMartinez** [comment] 2024-01-23 10:34
This might be possible, as we did phase some "echo" issues when implementing the new version of screenshare for wayland. If someone wants to play around this, https://github.com/IsmaelMartinez/teams-for-linux/pull/1077 fixed the echo. Maybe we can add a menu option that enables the sharing the screen audio, but will need to handle the echo.

**Comment by herbiejhopkins** [comment] 2024-01-28 16:20
I just spent a few mins playing around with the audio settings that I switched off in #1077 and while I can recreate the nice echo effect it does not appear to be able to capture system audio. So no reason to ever switch these on in teams-for-linux really. This is presumably because the audio is generated from a separate application. Teams in the browser allows this because it's the browser that's producing the sound in the first place - it's all the same application.

What does work though is using pipewire to route the output from one application to the teams-for-linux input. This obviously only works if you're using pipewire for you audio system but this seems to be pretty standard these days. When in a teams meeting if you open something like [qpwgraph](https://github.com/rncbc/qpwgraph) you can manually route the audio from e.g. your browser to the teams-for-linux input (shows up as chromium input) - just click and drag to create a link.
![image](https://github.com/IsmaelMartinez/teams-for-linux/assets/56479007/6be178a9-94c4-4655-b0ec-6361148981e6)
Also, this works regardless of whether you're sharing you're screen or not. You could just share some audio if you liked.

It's possible this is something that could be automated from within teams-for-linux. e.g. using the pipewire socket directly or cli tools - pw-link ?

**Comment by buster** [comment] 2024-02-23 06:16
I'm confused about the state and goal:
Since a few releases i cannot share my screen anymore because of an echo in my sound.
Is there a way to fix this with a current release or not?

As nice as it may seem to also share the sound from the computer, don't you all think that basic screen sharing with the ability to talk is more important?

Anyway, i'm grateful for this project and would like to know if there is some setting to disable this? If not, i'll have to stay with 1.4.2.

**Comment by jijojosephk** [comment] 2024-02-23 10:49
This issue in `wayland` was fixed by @herbiejhopkins So the latest versions should work.

**Comment by IsmaelMartinez** [comment] 2024-03-21 10:39
closing due inactivity

**Closed by IsmaelMartinez** 2024-03-21 10:39 UTC
Labels: enhancement
