### ISSUE TITLE
Teams opens meeting link 8 times

### ISSUE THREAD

**Issue by josefschabasser** [IsmaelMartinez/teams-for-linux#341] opened 2020-04-08 08:13 UTC
**Describe the bug**
I experience similar issues like #322 (looking at the log of #322 it tries 8 times). I click the meeting link in Evolution or Firefox, teams-for-linux opens 8 new instances, even though it is already running. If I click `Continue in this browser` I can join the meeting anonymously, I am not logged in. Using `Open with Microsoft Teams` it displays the `not found or moved` error.
If I copy&paste the link like mentioned in issue #318, this behaviour is not shown. It just joins the meeting (and the user is still logged in).

**To Reproduce**
1. Generate meeting link
2. Click on meeting link
3. Watch teams-for-linux open 8 new instances
4. Choose one of them and click `Continue with this Browser` (or similar, topmost button) - Success!
5. User is not logged in and joined anonymously - Partial Success...

**Expected behavior**
Teams opens links in existing window, not 8 new ones.
Teams logging the user in before joining meeting.

**Screenshots**
![grafik](https://user-images.githubusercontent.com/45227795/78759819-83122280-7980-11ea-8394-fc9655c8d035.png)
As you can see, teams-for-linux didn't open the meeting with the existing instance (rightmost icon in top panel). Instead it opened 8 new ones. The 8 new instances aren't logging me in, I join the meeting anonymously (notice the missing avatar).
![grafik](https://user-images.githubusercontent.com/45227795/78760507-8fe34600-7981-11ea-89ba-d0faa4654c67.png)
When I end the call, the login button (german `Anmelden`) is displayed.

**Desktop (please complete the following information):**
 - OS: Manjaro Linux (up to date)
 - Installation package: Flatpak
 - Version: 1.0.0

**Comment by IsmaelMartinez** [comment] 2020-04-08 19:01
that is pretty strange. for other packages that opening a link doesn't even
work.

The workaround is to copy/paste the invitation link into teams and open it
from there. If its an event in the calendar you just open from the calendar
withing teams (that also works)

thanks for reporting. can you confirm if the copy/paste works as a
workaround? (I know.. not ideal but its a workaround)

**Comment by josefschabasser** [comment] 2020-04-09 07:23
Yes, the copy/paste workaround from #318 works like a charm, but I already mentioned this in the initial post ;-)

**Comment by IsmaelMartinez** [comment] 2020-04-09 13:28
sorry, read it in my phone and miss that bit. I will say its the same issue as #318 but it shows slighly different symptoms in flatpak. I will see if I get some time this week to investigate a bit more but I am a bit low on extra time.

**Comment by IsmaelMartinez** [comment] 2020-04-15 08:05
I am looking at #318 and have identified where the issue is but it's a bit of a precision work... Meaning, adding the fix is breaking other functionality... But I am working on it.

**Comment by josefschabasser** [comment] 2020-04-27 07:50
I don't know how to flag a package outdated on flathub. Do I really have to sign up and open a thread in the forum? Anyways, please create a release on github. You increased the version string from 1.0.2 to 1.0.3, on flathub it's still 1.0.0 (like on the github releases page).

**Comment by IsmaelMartinez** [comment] 2020-04-27 08:31
the master release still on 1.0.0. 

Once I get some time, I will try to release 1.0.3 to dev and then master. Then, more or less, follow the steps in here:

https://github.com/IsmaelMartinez/teams-for-linux/issues/41#issuecomment-498018941

or just create an issue in the flatpak repository once its out there... but not before or they will ignore/close it.
https://github.com/flathub/com.github.IsmaelMartinez.teams_for_linux/issues/6

**Comment by josefschabasser** [comment] 2020-04-27 10:52
> the master release still on 1.0.0.
> 
> Once I get some time, I will try to release 1.0.3 to dev and then master. Then, more or less, follow the steps in here:
> 
> [#41 (comment)](https://github.com/IsmaelMartinez/teams-for-linux/issues/41#issuecomment-498018941)
> 
> or just create an issue in the flatpak repository once its out there... but not before or they will ignore/close it.
> [flathub/com.github.IsmaelMartinez.teams_for_linux#6](https://github.com/flathub/com.github.IsmaelMartinez.teams_for_linux/issues/6)

Thanks for pointing me in the right direction :-)

**Comment by josefschabasser** [comment] 2020-05-04 09:47
Well I just moved to `snapd` because of full sandboxing and integration in Manjaro Linux.
I used this command to install version 1.0.4:
```
sudo snap install teams-for-linux --edge
```
When I click a meeting link, the Teams window is moved to foreground (if it is open). Nothing else happens.

**Comment by IsmaelMartinez** [comment] 2020-05-05 06:10
Both comments are related to snap not the app. I hope I can create a release at some point this week (month) might do a pre-release so people can try it.

**Comment by IsmaelMartinez** [comment] 2020-05-05 06:18
Pre release ready in here https://github.com/IsmaelMartinez/teams-for-linux/releases/tag/v1.0.4

Can someone test it? I have been running it for 11 days with no issues but there are quite a few changes... internally

**Comment by michaelmassee** [comment] 2020-05-21 23:02
runs very good.
better then the preview version von MS
is there any chance to enable passthrough sound when share an aplication ??

**Comment by IsmaelMartinez** [comment] 2020-06-04 19:28
released as version 1.0.5. Closing

**Closed by IsmaelMartinez** 2020-06-04 19:28 UTC
Labels: bug, duplicate
