### ISSUE TITLE
Unable to use GitHub connector buttons 

### ISSUE THREAD

**Issue by HarlemSquirrel** [IsmaelMartinez/teams-for-linux#107] opened 2019-04-12 20:59 UTC
**Describe the bug**
Clicking buttons on posts made by the GitHub connector has no effect. 

Using [Ctrl] + click opens in a new mini browser window with no addressbar instead of opening in my default browser.

Right-clicking opens a context menu with options like "Copy" but clicking "Copy" does not copy the URL (or anything) to the clipboard. 

**To Reproduce**
1. Go to a channel with posts from the GitHub connector
2. Click on any button
3. Watch nothing happen

Opening the console and performing the above shows lots of errors like `Authorization error: Nonce in profile is not the same as whats in storage`. 

**Expected behavior**
1. Go to a channel with posts from the GitHub connector
2. Click on any button
3. See GitHub page in default browser

**Desktop (please complete the following information):**
 - OS: Fedora 29 GNOME
 - Installation package: rpm
 - Version 0.2.0

**Comment by IsmaelMartinez** [comment] 2019-04-12 21:53
Hi @HarlemSquirrel ,

This is a limitation of using electron wrapping the webpage. If you are opening without the "Ctrl" it does try to open the link in a external window without passing the credentials, etc.

Using the Ctrl+click is the only available solution at the moment. That should show you the content and work as intended.

Code is here, and it is basically the case that is not handle ('background-tab'):
https://github.com/IsmaelMartinez/teams-for-linux/blob/develop/app/index.js#L44

It might be possible to improve that a bit, and I encourage you to have a play, but I couldn't find a way of using shell.openExternal and persist the context/session/cookies.

**Comment by IsmaelMartinez** [comment] 2019-04-13 13:46
closing as I don't think it is easily possible to improve the current situation. Do re-open if required. Thanks

**Comment by HarlemSquirrel** [comment] 2019-05-10 14:10
I've made some progress but need some help. 

I can intercept the event opening the new window like so

```js
window.webContents.on('new-window', (event, url, frame, disposition, options, additionalFeatures, referrer) => {
  console.log('START new-window...');
  console.log('URL: ' + url);
  console.log('Frame: ' + frame);
  console.log('disposition: ' + disposition);
  console.log('options: ' + Object.keys(options));
  console.log('options webContents: ' + Object.keys(options.webContents));
  console.log('options webContents webContents: ' + Object.keys(options.webContents.webContents));
  console.log('options webContents history: ' + options.webContents.history);
  console.log('options webPreferences: ' + JSON.stringify(options.webPreferences));
  console.log('options webPreferences preload: ' + options.webPreferences.preload);
  console.log('additionalFeatures: ' + additionalFeatures);
  console.log('referrer: ' + JSON.stringify(referrer));
  if (url.startsWith('https://teams.microsoft.com/l/meetup-join')) {
    event.preventDefault();
    window.loadURL(url);
  } else if (url !== 'about:blank' && disposition !== 'background-tab') {
    console.log('opening external link to ' + url)
    event.preventDefault();
    shell.openExternal(url);
  }
});
```

But, I don't see the URL anywhere. 

```
START new-window...
URL: about:blank
Frame: 
disposition: foreground-tab
options: show,x,y,width,height,webContents,webPreferences,autoHideMenuBar,icon
options webContents: webContents,history,currentIndex,pendingIndex,inPageIndex,_events,_eventsCount,_maxListeners
options webContents webContents: webContents,history,currentIndex,pendingIndex,inPageIndex,_events,_eventsCount,_maxListeners
options webContents history: 
options webPreferences: {"partition":"persist:teams-4-linux","preload":"/home/kem2028/code/teams-for-linux/app/browser/index.js","nativeWindowOpen":true,"plugins":true,"nodeIntegration":false,"webviewTag":false,"openerId":2}
options webPreferences preload: /home/user/code/teams-for-linux/app/browser/index.js
additionalFeatures: undefined
referrer: {"url":"","policy":"default"}
```

I suspect there's another event I need to intercept but I'm not sure what that would be.

**Comment by IsmaelMartinez** [comment] 2019-05-10 14:54
This is the "about:blank" issue. Not sure how the angular part in the website works, but it is basically hidding the url somewhere in within it. Maybe someone with angular experience can have a look? we might need to intercept this calls in the javascript part as it seems to be too late in the node/electron part.

**Comment by HarlemSquirrel** [comment] 2019-05-10 18:11
I've also tried these two with no luck yet. It doesn't seem to intercept the requests. 

https://electronjs.org/docs/api/web-request

```js
// Modify the user agent for all requests to the following urls.
const filter = {
  urls: ['*github.com/*', '*://electron.github.io']
}

session.defaultSession.webRequest.onBeforeRequest(filter, (details, callback) => {
	console.log('DEBUG - webRequest grabbed for ' + details.url)
	callback({ response: { cancel: true } })
})
```

https://electronjs.org/docs/api/protocol

```js
protocol.interceptHttpProtocol("https", (request, callback) => {
	console.log('DEBUG - Intercepted http request: ' + request.url)
	if (! request.url.startsWith('https://teams.microsoft.com/')) {
		console.log('DEBUG - Intercepted https request: ' + request.url)
		// event.preventDefault();
		// window.loadURL(url);
	}
});
```

**Comment by HarlemSquirrel** [comment] 2019-05-10 18:51
I've made some progress. I was able to grab the URL and open in a new window! 

```js
window.webContents.on('new-window', (event, url, frame, disposition) => {
	if (url.startsWith('https://teams.microsoft.com/l/meetup-join')) {
		event.preventDefault();
		window.loadURL(url);
	} else if (url !== 'about:blank' && disposition !== 'background-tab') {
		console.log('opening external link to ' + url)
		event.preventDefault();
		shell.openExternal(url);
	}
});

// Modify the user agent for all requests to the following urls.
const filter = {
	urls: ['https://github.com/*']
}

window.webContents.session.webRequest.onBeforeRequest(filter, (details, callback) => {
	console.log('DEBUG - webRequest grabbed for ' + details.url);
	shell.openExternal(details.url);
	callback({ cancel: true })
});
```

This does open a new window in electron first before the request to github is made so I think we'll need handle that somehow by closing the window after it opens perhaps or somehow opening it in the background. 

```
DEBUG - new-window triggered
DEBUG - webRequest grabbed for https://github.com/...
```

**Comment by IsmaelMartinez** [comment] 2019-07-11 22:00
Check comments in PRs. Thanks again for you contribution!

**Closed by IsmaelMartinez** 2019-07-11 22:00 UTC
Labels: bug, known issue/workaround

**Comment by HarlemSquirrel** [comment] 2019-07-17 15:48
So the latest code in develop allows the buttons on the GitHub integration posts to open a new window, but since I'm not logged in to GitHub there I get a 404 for private repositories. I don't see an easy way to grab the URL to open in my browser.

**Comment by IsmaelMartinez** [comment] 2019-07-17 15:58
The only way I see on this is to log in in the team github integration (on the applications menu, not on the chat option), and then you should be able to see those pages (as you will be still log in)

Doing Ctrl+click will open in the browser and then it depends on what you have done in Chrome/Firefox for the authentication. Unfortunately and due security, electron doesn't allow passing the authentication out of its "chrome" to the external window.... if that make much sense to you. Hope helps

**Comment by HarlemSquirrel** [comment] 2019-07-17 19:35
Ugh, I was hoping it would open in Firefox :cry:

**Comment by IsmaelMartinez** [comment] 2019-07-17 19:52
yeah, sorry is an electron limitation (or feature depending how you look at it) :/
