### ISSUE TITLE
0.1.5 not authenticating to O365 properly.

### ISSUE THREAD

**Issue by docsmooth** [IsmaelMartinez/teams-for-linux#3] opened 2018-10-19 21:26 UTC
0.1.4 from your releases works.  But 0.1.5 is throwing an error "This endpoint only accepts POST, and recieved a GET".

I'll see if I can enable teams on my personal O365 install and try there instead, but that may take a few days.

**Comment by IsmaelMartinez** [comment] 2018-10-19 21:34
Strange... can you provide more info? (screenshots/etc). I don't think I will be able to look at much during this weekend but hopefully someone can have a look.

Maybe try using persist option, something like 
`teams --partition persist:teams-linux`

By the way, it does look like JamieMagee is rewriting the app so I might need to concentrate in migrating the changes from here into there, but I will try to support this at least until that rewrite is ready.

**Comment by IsmaelMartinez** [comment] 2018-10-22 09:04
Hi @docsmooth , 

Could you provide steps of how to recreate the issue (including screenshots if/where possible)? Also, could you confirm this is not happening in the browser (ideally, Chrome/Chromium).

And last, could you confirm if by using the option that I provide in my previous message, you don't have the issue with version 0.1.5 ?

Thanks!

**Comment by Raizo62** [comment] 2018-10-22 10:01
I have the same error message.
I am on Debian (LiveRaizo Distribution) behind a proxy/firewall

![image](https://user-images.githubusercontent.com/7449584/47287337-3141d500-d5f2-11e8-9c37-75f097004ef6.png)

**Comment by IsmaelMartinez** [comment] 2018-10-22 13:36
Does it work in the browser?

Can you confirm that starting the teams using the following doesn't solve the issue?

`teams --partition persist:teams-linux`

**Comment by Raizo62** [comment] 2018-10-22 14:28
Teams works on Win7 with Firefox in the same network.

Your command doesn't solve the issue.
I have tried the old version 0.1.4 without success

I had white page authentication with last ivelkov/teams-for-linux

**Comment by docsmooth** [comment] 2018-10-22 14:56
![image](https://user-images.githubusercontent.com/2999684/47299781-9f7d9c00-d5e0-11e8-9e5c-4ba619b38967.png)

Of note: I have a personal account and a work-provided account with the same email address. I wonder if others in this thread have the same situation?

**Comment by docsmooth** [comment] 2018-10-22 15:00
0.1.4 does work fine, but does throw the same "did-fail-load" message as 0.1.5, so that's an unrelated message.  Here's the sharable output from 0.1.4 - 0.1.5 stops with the screenshot and the "did-fail-load" message:

> did-fail-load { preventDefault: [Function: preventDefault],
  sender:
   WebContents {
     webContents: [Circular],
     history:
[ 'https://login.microsoftonline.com ... ],
     currentIndex: 2,
     pendingIndex: -1,
     inPageIndex: -1,
     _events:
      { 'navigation-entry-commited': [Function],
        'ipc-message': [Function],
        'ipc-message-sync': [Function],
        'pepper-context-menu': [Function],
        '-did-get-response-details': [Function],
        '-did-get-redirect-request': [Function],
        'devtools-reload-page': [Function],
        'will-navigate': [Function],
        'did-navigate': [Function],
        destroyed: [Function],
        'devtools-opened': [Function],
        '-new-window': [Function],
        '-web-contents-created': [Function],
        '-add-new-contents': [Function],
        move: [Function],
        activate: [Function],
        'page-title-updated': [Function],
        'did-fail-load': [Function],
        'new-window': [Function],
        login: [Function],
        'did-finish-load': [Function] },
     _eventsCount: 21,
     _maxListeners: 0,
     browserWindowOptions:
      { x: 1095,
        y: 276,
        width: 800,
        height: 800,
        show: false,
        iconPath:
         '/opt/teams-for-linux/resources/app/lib/assets/icons/icon-96x96.png',
        autoHideMenuBar: true,
        icon:
         '/opt/teams-for-linux/resources/app/lib/assets/icons/icon-96x96.png',
        webPreferences: [Object] } } } -3  https://login.microsoftonline.com/5683fad6-d462-468d-9daa-809d2d98368e/login true 7 3

**Comment by IsmaelMartinez** [comment] 2018-10-22 16:09
Hi @docsmooth and @Raizo62 

The "did-fail-load. Trying to reload." is quite a common message. I was printing much more data in version 0.1.4 but it should not be related.

Now,  I assume those are 2 different issues.

The changes between version 0.1.4 and 0.1.5 are:
* disabling session persistence (that is why the command that I put there that will enable it again) @docsmooth , could you confirm if that command solves the issue for you or not?
* adding back command arguments. 0.1.4 will ignore the arguments
* enabling asar. This could be causing the issue but I will be incline to ignore it at the moment.

This link makes me think is related to the persistence (https://social.msdn.microsoft.com/Forums/en-US/98350e5d-07cf-4d5e-bbba-9fd707cb0107/aadsts90056-this-endpoint-only-accepts-post-requests-received-a-get-request)

@Raizo62 , could you check that you can use chromium in the Linux box that in that network. Your case could be related to that Linux configuration and not the network.

It might be wise to open another issue, @Raizo62 , if the partition issue doesn't work for you.

Version 0.1.2 can be use also to test if is related to the userAgent [probably more for @Raizo62 ] (moved from edge to chrome as it was causing an issue with mentions). 

Ignore version 0.1.3 as it doesn't add much to it.

Lets see if we can find what is the issue, unfortunately this is one of those that is pretty hard to debug.

**Comment by docsmooth** [comment] 2018-10-22 16:38
OK, this is interesting, after removing the .config/teams-for-linux folder, now 0.1.4 isn't logging in either.  I see the "Do you want to remember this signin" page, but it immediately submits and refreshes with the error linked above.

is there any additional logging I can generate, even from the source code?

**Comment by docsmooth** [comment] 2018-10-22 18:01
Downgrading to 0.0.7 (my fallback "last known good") work, but doesn't restore operation to 0.1.4

**Comment by IsmaelMartinez** [comment] 2018-10-22 20:06
that is even more interesting then. I have tried removing the .config/teams-for-linux folder and still all works fine in my end with 0.1.5, 0.1.4 and 0.1.2. 

A few things that might help you trace the issue:
* if you click in the top bar (the one that says sign up in your account in your picture) and then the Alt key, you should be able to see a menu where you can activate the developer tools (chrome ones)
* if you get the code, it might be worth seen if it works by commenting the lines that says: 
`
app.commandLine.appendSwitch('auth-server-whitelist', '*');
app.commandLine.appendSwitch('enable-ntlm-v2', 'true');
`

I am trying to see if I can reproduce the error by getting a hotmail account, but is taking some time.

**Comment by IsmaelMartinez** [comment] 2018-10-22 20:41
Interestingly enough, I couldn't log in in a "personal" account, was kicking me back to the login page... and the issue was I added a reload  when the page failed to load. I will create a pre-release 0.1.6 and I invite you guys to try it as both issues might be related. 

I added that a few versions back to try to solve an issue where sometimes it will stop loading the page after a few of those "did-fail-to-load" but seems like in some account is "OK" to get a few of those. 

Lets see if that fixes both issues (hopefully it does).

**Comment by IsmaelMartinez** [comment] 2018-10-22 21:00
I am not going to be able to check during the day but could you @docsmooth and @Raizo62 check if version https://github.com/IsmaelMartinez/teams-for-linux/releases/tag/v0.1.6 solves the problem? 

The only change is removing that "did-fail-load" part that was retrying. That is not present in any of the other repositories (that I fork from) and it was intended to solve an issue where sometimes it was hanging loading and you had to "refresh" the page (right click in the tray icon and click reload).

**Comment by docsmooth** [comment] 2018-10-22 21:11
0.1.6: Success, but I have to log on for every launch.

The first load of 0.1.6 allowed me to click the "save my login" information, and launched properly, when I used the "teams --partition persist:teams-linux" command.

Launching without the "persist:teams-linux" flag also works.

**Comment by IsmaelMartinez** [comment] 2018-10-23 06:35
If you could log another issue for the persist I will see if I can have a look at it tomorrow or later today. A few people experience "loosing" history with the persist on. A fair bigger issue, but enabling the persist from the command line should persist!! (But is not doing it). I will close this issue but let's see if @Raizo62 issue was also related to the reload. Cheers!

**Closed by IsmaelMartinez** 2018-10-23 06:35 UTC

**Comment by IsmaelMartinez** [comment] 2018-11-01 15:12
@docsmooth ,  version [0.1.9](https://github.com/IsmaelMartinez/teams-for-linux/releases/tag/v0.1.9) persists the session by default (and a couple of other improvements. Hope helps,
