### ISSUE TITLE
Teams APT repository does not work well with apt-cacher-ng

### ISSUE THREAD

**Issue by JakubVanek** [IsmaelMartinez/teams-for-linux#898] opened 2023-07-18 17:30 UTC
**Describe the bug**
I am using apt-cacher-ng at home to cache package downloads from multiple other machines. Unfortunately, apt-cacher-ng serves the old package version to its clients when the package is updated in the new Teams repo. This does not happen for other repositories.

Running `apt update && apt full-upgrade` on a machine behind the cache now yields an error message like this:
```
Get:1 http://repo.teamsforlinux.de/debian stable/main amd64 teams-for-linux amd64 1.2.6 [68.8 MB]
Err:1 http://repo.teamsforlinux.de/debian stable/main amd64 teams-for-linux amd64 1.2.6
  File has unexpected size (68775814 != 68757582). Mirror sync in progress? [IP: 10.0.0.89 3142]
  Hashes of expected file:
   - SHA512:e94a5b303715cac5b783fa9dfb2b1d1a9937e56a2ba473fea30fca726c3d7fa69c539de7834d6d9d2caef55f39d8511524db2c6c53258ad0cfff43d17d1d3f18
   - SHA256:a666a8c506728b1e8efa606b8190e07225cada31435303029e716466148e29d6
   - SHA1:49cf157560dc97ae6a463052264c1858520d2599 [weak]
   - MD5Sum:2a8814ff4f5232b1acfe9bcd8887c1ae [weak]
   - Filesize:68757582 [weak]
E: Failed to fetch http://repo.teamsforlinux.de/debian/pool/main/t/teams-for-linux/teams-for-linux_amd64.deb  File has unexpected size (68775814 != 68757582). Mirror sync in progress? [IP: 10.0.0.89 3142]
   Hashes of expected file:
    - SHA512:e94a5b303715cac5b783fa9dfb2b1d1a9937e56a2ba473fea30fca726c3d7fa69c539de7834d6d9d2caef55f39d8511524db2c6c53258ad0cfff43d17d1d3f18
    - SHA256:a666a8c506728b1e8efa606b8190e07225cada31435303029e716466148e29d6
    - SHA1:49cf157560dc97ae6a463052264c1858520d2599 [weak]
    - MD5Sum:2a8814ff4f5232b1acfe9bcd8887c1ae [weak]
    - Filesize:68757582 [weak]
E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?
```

This can be worked around by stopping apt-cacher-ng on the caching server, deleting the cached package there and then starting apt-cacher-ng again.

I think this might be caused by the way the package is stored in the Teams APT repository - the package is always named `teams-for-linux_amd64.deb`. Files in other APT repositories have package version in their name. This way the cache cannot serve the old package when the new one is requested.

**To Reproduce**
1. Install apt-cacher-ng `3.7.4-1build1`/`3.7.4-1build1` from Ubuntu 20.04/22.04 to a machine in your network
2. Configure a test machine to use that apt-cacher-ng instance for downloading APT packages
3. Add the `http://repo.teamsforlinux.de/debian/` repo (HTTP instead of HTTPS) to APT sources list on the test machine
4. Install the `teams-for-linux` package on the test machine
5. Wait for new `teams-for-linux` package release
6. Try to update the package via `apt update && apt full-upgrade`. The upgrade will fail when it tries to download the updated package.

**Expected behavior**
Ideally, apt-cacher-ng would cache every package version separately. This would require having the packages in the upstream APT repo named like `teams-for-linux_1.2.5_amd64.deb` and `teams-for-linux_1.2.6_amd64.deb`.

**Environment**
Client: Xubuntu 22.04, teams-for-linux 1.2.5
APT caching server: Ubuntu 20.04, apt-cacher-ng package 3.3.1-2build1; also tried to update to 3.7.4-1build1, but that didn't help

**Additional context**
From a pure HTTP standpoint, it looks like the Teams repo server handles things correctly (`Last-Modified` and `Etag` headers). However, I'm assuming that apt-cacher-ng assumes that files under `/pool/` never change.

**Comment by JakubVanek** [comment] 2023-07-18 21:38
I did some digging and I think I've found why the cache behaves like this. Apt-cacher-ng does consider some URLs as static / never changing. The patterns for matching these URLs are configured via a `PFilePattern` option (docs: "static data that doesn't change silently on the server"). This option has the default defined here https://salsa.debian.org/blade/apt-cacher-ng/-/blob/debian/sid/src/acfg_defaults.cc#L38 . IIUC it considers all `.deb` files as non-changing. This assumption does hold for packages including version within their name, but here the assumption is invalid.

**Comment by jijojosephk** [comment] 2023-07-19 06:18
@nbuechner, Is this something you can fix?

**Comment by nbuechner** [comment] 2023-07-19 08:11
This is how aptly create the repo. I could not find any option for force version numbers in the .deb names. If anyone finds such an option i can add it of course.

**Comment by JakubVanek** [comment] 2023-07-19 08:27
I'll try to look into it later; there appears to be a way to achieve this, because Aptly's own repository has packages with version numbers (https://repo.aptly.info/dists/squeeze/main/binary-amd64/Packages points to https://repo.aptly.info/pool/main/a/aptly/aptly_1.5.0_amd64.deb).

**Comment by jijojosephk** [comment] 2023-07-20 04:47
Thanks @nbuechner. @JakubVanek, I assume the problem is resolved hence closing this.

**Closed by jijojosephk** 2023-07-20 04:47 UTC

**Comment by JakubVanek** [comment] 2023-07-20 08:47
It works, thank you!
