### ISSUE TITLE
warning that inflight module is not supported: Do not use it

### ISSUE THREAD

**Issue by Blu3wolf** [IsmaelMartinez/teams-for-linux#1302] opened 2024-06-15 01:21 UTC
**Describe the bug**
I get some warnings from npm when building this, one of which explicitly says not to use the module: ==> Starting build()... npm warn deprecated inflight@1.0.6: This module is not supported, and leaks memory. Do not use it. Check out lru-cache if you want a good and tested way to coalesce async requests by a key value, which is much more comprehensive and powerful. npm warn deprecated glob@7.2.3: Glob versions prior to v9 are no longer supported

**To Reproduce**
Build https://aur.archlinux.org/packages/teams-for-linux

**Expected behavior**
Build process to complete without warnings saying to not use a module

**Desktop (please complete the following information):**
 - OS: Manjaro Unstable
 - Installation package: https://aur.archlinux.org/packages/teams-for-linux
 - Version: 1.6.1-1

**Comment by IsmaelMartinez** [comment] 2024-06-15 06:31
Hi @Blu3wolf , Thanks for reporting.

This is for eslint that is a build step. The issue is here https://github.com/eslint/eslint/issues/18573 

We regularly update the packages. Once they fix this, we will get it.

Marking as blocked and closing as there isn't anything we can do now, and it doesn't affect other than build time.

**Closed by IsmaelMartinez** 2024-06-15 06:31 UTC
Labels: blocked, dependencies
