### ISSUE TITLE
`Payment required` while trying to install apt repository

### ISSUE THREAD

**Issue by drupol** [IsmaelMartinez/teams-for-linux#875] opened 2023-06-30 07:50 UTC
Hello,

I get this error message this morning while trying to install using `curl -1sLf 'https://dl.cloudsmith.io/public/teams-for-linux/packages/setup.deb.sh' | sudo -E bash`

`E: Failed to fetch https://dl.cloudsmith.io/public/teams-for-linux/packages/deb/ubuntu/dists/mantic/InRelease  402  Payment Required [IP: 18.65.39.112 443]`

![image](https://github.com/IsmaelMartinez/teams-for-linux/assets/252042/3fb0bd7a-ab5c-4503-8123-7d9502cc36df)

**Comment by RolandRosenfeld** [comment] 2023-06-30 08:02
I can confirm this issue with an repository that was working for 6 weeks now since today:
```
Err:16 https://dl.cloudsmith.io/public/teams-for-linux/packages/deb/debian bullseye InRelease                                                                                    
  402  Payment Required [IP: 2600:9000:225f:1c00:e:f4d2:20c0:93a1 443]
[...]
E: Failed to fetch https://dl.cloudsmith.io/public/teams-for-linux/packages/deb/debian/dists/bullseye/InRelease  402  Payment Required [IP: 2600:9000:225f:1c00:e:f4d2:20c0:93a1 443]
E: The repository 'https://dl.cloudsmith.io/public/teams-for-linux/packages/deb/debian bullseye InRelease' is no longer signed.
```

**Comment by eXt73** [comment] 2023-06-30 08:17
Ja can confirm too ...

E: Nie udało się pobrać https://dl.cloudsmith.io/public/teams-for-linux/packages/deb/ubuntu/dists/jammy/InRelease  402  Payment Required [IP: 108.138.51.41 443]
E: The repository 'https://dl.cloudsmith.io/public/teams-for-linux/packages/deb/ubuntu jammy InRelease' is no longer signed.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.

**Comment by jijojosephk** [comment] 2023-06-30 08:51
We may need to move from cloudsmith to some other service. Thought it was free for open source but looks like some rate limit applies.

**Comment by SorinSu** [comment] 2023-06-30 09:09
+1

**Comment by jijojosephk** [comment] 2023-06-30 09:51
Kindly get the suitable package from the releases page.

**Comment by zelimir86** [comment] 2023-06-30 11:29
Also, confirming issue:

![image](https://github.com/IsmaelMartinez/teams-for-linux/assets/16905384/68136d1e-efdd-495a-8be8-3f5b8cdf4666)

**Comment by bratkartoffel** [comment] 2023-06-30 12:13
Maybe using PPA on `Launchpad` is an alternative?
https://en.wikipedia.org/wiki/Launchpad_%28website%29 / https://launchpad.net/ubuntu/+ppas

**Comment by jijojosephk** [comment] 2023-06-30 12:38
> Maybe using PPA on `Launchpad` is an alternative, at least for Debian / Ubuntu? https://en.wikipedia.org/wiki/Launchpad_%28website%29 and https://launchpad.net/ubuntu/+ppas

The problem is we can't upload the binaries to launchpad. Only the source code and electron build process is not supported there as far as I know.

**Comment by nbuechner** [comment] 2023-06-30 12:46
If you have a rough estimate about required bandwidth and traffic i can maybe help with hosting. Feel free to contact me. https://buechner.me/

**Comment by jijojosephk** [comment] 2023-06-30 13:50
Thanks @nbuechner, we added deb and rpm repositories quite recently. Average bandwidth is difficult to calculate at the moment. In cloudsmith, FOSS limited at 200GB/month.

As you can see from the screenshot below, first month was fine, obvious! But now more and more people use it so bandwidth is consumed quite fast. 6 more days before it gets reset. So the repo is going to be down for next 6-7 days.

![image](https://github.com/IsmaelMartinez/teams-for-linux/assets/11662148/fffdc086-132a-46f6-8ca9-f0ea48567553)

For now everyone needs to use the releases page https://github.com/IsmaelMartinez/teams-for-linux/releases

I think we might need TBs of bandwidth per month to keep the repo runninng. Sad!

**Comment by jijojosephk** [comment] 2023-06-30 13:58
> a few TB are not a problem. is a 1gbit uplink enough or do you need 10?

More than enough I suppose.

**Comment by nbuechner** [comment] 2023-06-30 14:00
We can work something out then. Can i contact you somewhere?

**Comment by jijojosephk** [comment] 2023-06-30 14:04
We have a community room in matrix. @IsmaelMartinez you must join the discussion you're the owner of the repo :smile: 

https://matrix.to/#/#teams-for-linux_community:gitter.im

Well, I invite everyone. It's boring there :laughing: come join the party.

**Comment by drupol** [comment] 2023-06-30 15:56
Don't forget that it's also available in Nix/NixOS, without requiring a third party server !

Just run the app by doing: `nix run github:NixOS/nixpkgs#teams-for-linux`

**Comment by nbuechner** [comment] 2023-06-30 21:50
Repo for Debian/Ubuntu is available for testing. Please report any issues. Still a work in progress.

`sudo wget -qO /etc/apt/trusted.gpg.d/teams-for-linux.asc https://repo.teamsforlinux.de/debian/teams-for-linux.asc`

`echo "deb [signed-by=/etc/apt/trusted.gpg.d/teams-for-linux.asc arch=$(dpkg --print-architecture)] https://repo.teamsforlinux.de/debian/ stable main" \
   | sudo tee /etc/apt/sources.list.d/teams-for-linux-packages.list`

**Comment by bratkartoffel** [comment] 2023-07-01 07:51
Why did the GPG key change? @IsmaelMartinez can you confirm that this is indeed your key, you created it and no one else has access to it?

**Comment by IsmaelMartinez** [comment] 2023-07-01 08:28
I didn't change anything. @jijojosephk maybe? GitHub did change their keys not too long ago, check if it's not that what you are seeing.

**Comment by bratkartoffel** [comment] 2023-07-01 09:33
Just to clarify, the GPG key used in the new repository at "teamsforlinux.de" is different than the one used to sign the debs at cloudsmith. I'm not that happy to add an unknown, potentially untrusted repository to my system just from a github comment ;)

Old KeyID: 8821a9a98ef1ab9d
New KeyID: 2fd80e00e6a6e47d

It has nothing to do with the changed SSH-Keys by github.

**Comment by RolandRosenfeld** [comment] 2023-07-01 10:16
The old cloudsmith Repo used
```
pub   rsa3072 2023-05-06 [SCEA]
      31784E77C14ED763A5208E2C8821A9A98EF1AB9D
uid           Cloudsmith Package (teams-for-linux/packages) <support@cloudsmith.io>

```
I think that couldn't be reused, because it was a cloudsmith key.  The new one uses:
```
pub   rsa4096 2023-06-30 [SC]
      D112747BDF6269C845972E5C2FD80E00E6A6E47D
uid           Teams for Linux Repo <ijojosephk@hotmail.com>
sub   rsa4096 2023-06-30 [E]
```
Maybe the latter key should be included in the github repo, so the user can be sure, that repo.teamsforlinux.de isn't a Phish but really the official apt repo for https://github.com/IsmaelMartinez/teams-for-linux/.

@nbuechner
I'd suggest to change the key path from /etc/apt/trusted.gpg.d to /etc/apt/keyrings, since everything in /etc/apt/trusted.gpg.d is trusted for all apt repos (also without using the signed-by option).  Alternatively you can use /usr/share/keyrings (you will find several sources where this is mentioned instead of /etc/apt/keyrings), but I'd prefer /etc/apt/keyrings, since the key is not shipped by a package, so it should not be placed in /usr (except /usr/local).  Since Debian bookworm /etc/apt/keyrings is the preferred location, see https://manpages.debian.org/unstable/apt/sources.list.5.en.html:

> The recommended locations for keyrings are /usr/share/keyrings for keyrings managed by packages, and /etc/apt/keyrings for keyrings managed by the system operator. If no keyring files are specified the default is the trusted.gpg keyring and all keyrings in the trusted.gpg.d/ directory (see apt-key fingerprint).

**Comment by nbuechner** [comment] 2023-07-01 10:49
i don't have access to the old key.  @jijojosephk  did not replay to me yesterday anymore so i started to work on the new repo alone.

**Comment by jijojosephk** [comment] 2023-07-01 15:24
Peace :laughing: Got busy with some personal stuff. Are we on agreement to get the GPG key from cloudsmith?

![](https://media.giphy.com/media/l4JyXBrPLYGbXGp0s/giphy.gif)

**Comment by jijojosephk** [comment] 2023-07-02 03:29
Documentation updated with a minor bump `1.1.9` please validate if the latest updates are reflected. Thanks a million @nbuechner for your efforts! :heart:

**Comment by nbuechner** [comment] 2023-07-02 04:54
My Ubuntu 22.04 and AlmaLinux 8 got the update. Please send your feedback.

**Comment by jijojosephk** [comment] 2023-07-03 08:18
Closing this as we have a new repo now.

**Closed by jijojosephk** 2023-07-03 08:18 UTC

**Comment by jijojosephk** [comment] 2023-07-03 08:20
Encourage everyone to join the matrix chat room for this project https://matrix.to/#/#teams-for-linux_community:gitter.im
