### ISSUE TITLE
Impossible to submit company login.

### ISSUE THREAD

**Issue by BlackSmith** [IsmaelMartinez/teams-for-linux#538] opened 2022-07-08 05:58 UTC
**Describe the bug**
I can not submit company login in the form (picture is behind). If I click on the button "submit" (or press enter) nothing happen.
In web debug console, I can not see anything. When I try to log in by Firefox, it works fine.

**To Reproduce**
1. Download file teams-for-linux-1.0.24.AppImage
2. Run
   ```
    chmod +x teams-for-linux-1.0.24.AppImage
    ./teams-for-linux-1.0.24.AppImage
    ```
3. Enter your company credentials.

**Expected behavior**
Login to my company account or get some error message

**Screenshots**
![obrazek](https://user-images.githubusercontent.com/192467/177924430-cbd54eed-57c0-4d30-8b13-e665205d511e.png)

**Desktop:**
 - OS: Fedora Linux 36 x86_64 (GNOME 42.2 + Wayland)
 - Installation package AppImage (version 1.0.24)

**Comment by BlackSmith** [comment] 2022-07-11 05:57
Hi @IsmaelMartinez,
It's true, that I had not Chrome installed.  I have tried to install Chrome and login by it works well. But The Teams (*.AppImage version) still does not work. The same problem as I describe above (I can not submit login form).

I use Teams (flatpak version) for many years, but with upgrade to Fedora 36 (from Fedora 35) I have problem with it. The application start, but I don't see any window. The same situation when I use pure RPM package.   I don't want open ticket for this, because I have got non-full Linux supported graphic card and I already had same problems with it (with rendering). It is the reason, why I try to use AppImage, because it shows windows.

**Comment by FrostbittenKing** [comment] 2022-07-13 09:45
Hi @IsmaelMartinez , I have the exact same problem with a fully updated Arch Linux.

**Comment by IsmaelMartinez** [comment] 2022-07-13 10:42
Hey, can you kill the process and try to open the app via the terminal? That will give you some logs that might help understand the issue. Thanks

**Comment by BlackSmith** [comment] 2022-07-15 04:36
```
> ./teams-for-linux-1.0.24.AppImage                                                        2022-07-15 06:33:21
configPath = /home/user/.config/teams-for-linux
Failed to get the config file, using default values
configFile = {}
INFO: Running under Wayland, switching to PipeWire...
libva error: vaGetDriverNameByIndex() failed with unknown libva error, driver_name = (null)
processArgs [ '/tmp/.mount_teams-Xe1ITk/teams-for-linux' ]
[234459:0715/063326.461355:ERROR:browser_main_loop.cc(269)] Gtk: gtk_widget_add_accelerator: assertion 'GTK_IS_ACCEL_GROUP (accel_group)' failed
[234459:0715/063326.461458:ERROR:browser_main_loop.cc(269)] Gtk: gtk_widget_add_accelerator: assertion 'GTK_IS_ACCEL_GROUP (accel_group)' failed
[234459:0715/063326.461497:ERROR:browser_main_loop.cc(269)] Gtk: gtk_widget_add_accelerator: assertion 'GTK_IS_ACCEL_GROUP (accel_group)' failed
[234459:0715/063326.461537:ERROR:browser_main_loop.cc(269)] Gtk: gtk_widget_add_accelerator: assertion 'GTK_IS_ACCEL_GROUP (accel_group)' failed
[234459:0715/063326.461571:ERROR:browser_main_loop.cc(269)] Gtk: gtk_widget_add_accelerator: assertion 'GTK_IS_ACCEL_GROUP (accel_group)' failed
did-finish-load
did-finish-load
window close
```

**Comment by BlackSmith** [comment] 2022-07-15 10:01
OK. Thank you very much.

BTW: I played with flatpak version and I have fixed it. :)  
It helped me to remove all unnecessary freedesktop flatpak packages and voilà I can see the teams windows.

```
org.freedesktop.Platform.GL.default             21.3.8              21.08      system
org.freedesktop.Platform.GL.nvidia-510-60-02                     1.4        system
org.freedesktop.Platform.GL.nvidia-515-48-07                     1.4        system
org.freedesktop.Platform.GL.nvidia-515-57                          1.4        system
org.freedesktop.Platform.ffmpeg-full                                     21.08      system
org.freedesktop.Platform.openh264              2.1.0                2.0
```

**Comment by volkflo** [comment] 2022-07-29 05:14
@BlackSmith Could you please explain how you removed these packages or maybe even contribute your changes ? :)

**Comment by BlackSmith** [comment] 2022-07-29 05:49
@volkflo It is not so complicated. 
1. I checked flatpak teams package
```
> flatpak info com.microsoft.Teams
  ....
  Runtime: org.freedesktop.Platform/x86_64/21.08
  ...
```
2. And I saw, that I had a mess in `org.freedesktop.Platform` flatpak packages from previous Fedora version.
```
> flatpak list
...
Freedesktop Platform       org.freedesktop.Platform                            21.08.14             21.08      system
Mesa                                org.freedesktop.Platform.GL.default           21.3.8               21.08      system
nvidia-515-60-02              org.freedesktop.Platform.GL.nvidia-510-60-02                     1.4        system
nvidia-515-48-07              org.freedesktop.Platform.GL.nvidia-515-48-07                     1.4        system
nvidia-515-57                   org.freedesktop.Platform.GL.nvidia-515-57                          1.4        system
ffmpeg-full                        org.freedesktop.Platform.ffmpeg-full                                     21.08      system
openh264                         org.freedesktop.Platform.openh264              2.1.0                2.0
...
```

3. I uninstalled `com.microsoft.Teams`,  all `org.freedesktop.Platform.*` and all useless  flatpak packages, one per others. If some them is a requirement of other flatpak packages, I skipped them. I think the problem was with many versions of `org.freedesktop.Platform.GL.nvidia-*` packages.
```
> flatpak uninstall com.microsoft.Teams
> flatpak uninstall org.freedesktop.Platform.GL.nvidia-515-48-07
> flatpak uninstall org.freedesktop.Platform.GL.nvidia-510-60-02
> flatpak uninstall org.freedesktop.Platform.ffmpeg-full
> org.freedesktop.Platform.openh264
...
``` 
4. After reboot and I installed `com.microsoft.Teams` packages again.
```
> flatpak install com.microsoft.Teams
```

These steps helped me, I hope that they help you as well.

**Comment by volkflo** [comment] 2022-07-29 05:51
Thanks a lot @BlackSmith! I will try that as well :rocket:

**Comment by jijojosephk** [comment] 2022-08-03 08:25
Do we need company login?

**Comment by jijojosephk** [comment] 2022-08-10 18:29
Closing this as there's a work around. Feel free to open if you need more help.

**Comment by jijojosephk** [comment] 2022-08-14 05:09
I have a question though, when this popup shows?

**Comment by BlackSmith** [comment] 2022-08-14 06:52
I'm not administrator of our Microsoft Office 365 accounts, but I guess when our company use SAML authentication.

**Comment by joschi36** [comment] 2022-08-17 11:57
I have the same issue, but I'm using deb and do not see the error @BlackSmith did see. I suspect there is a different problem:
```
configPath = /home/***/.config/teams-for-linux
Failed to get the config file, using default values
configFile = {}
INFO: Running under Wayland, switching to PipeWire...
processArgs [ '/opt/teams-for-linux/teams-for-linux' ]
[45118:0817/133336.677606:ERROR:browser_main_loop.cc(270)] Gtk: gtk_widget_add_accelerator: assertion 'GTK_IS_ACCEL_GROUP (accel_group)' failed
[45118:0817/133336.677760:ERROR:browser_main_loop.cc(270)] Gtk: gtk_widget_add_accelerator: assertion 'GTK_IS_ACCEL_GROUP (accel_group)' failed
[45118:0817/133336.677793:ERROR:browser_main_loop.cc(270)] Gtk: gtk_widget_add_accelerator: assertion 'GTK_IS_ACCEL_GROUP (accel_group)' failed
[45118:0817/133336.677824:ERROR:browser_main_loop.cc(270)] Gtk: gtk_widget_add_accelerator: assertion 'GTK_IS_ACCEL_GROUP (accel_group)' failed
[45118:0817/133336.677852:ERROR:browser_main_loop.cc(270)] Gtk: gtk_widget_add_accelerator: assertion 'GTK_IS_ACCEL_GROUP (accel_group)' failed
did-finish-load
did-finish-load
[45177:0817/133400.649675:ERROR:gl_surface_presentation_helper.cc(260)] GetVSyncParametersIfAvailable() failed for 1 times!
[45177:0817/133550.118620:ERROR:gl_surface_presentation_helper.cc(260)] GetVSyncParametersIfAvailable() failed for 2 times!
[45177:0817/133553.374248:ERROR:gl_surface_presentation_helper.cc(260)] GetVSyncParametersIfAvailable() failed for 3 times!
window close
before-quit
window close
window closed
will-quit
quit
```

Tried reinstalling and also cleaning config path without luck.
The Request is hanging and the submit button is doing nothing:
![image](https://user-images.githubusercontent.com/4538306/185112042-1b67ad00-9170-4b39-add9-67f09fdbc714.png)

Also, I did not see any messages in JavaScript Developer Console.

Distribution: Debian Testing (bookworm)
Kernel: 5.18.0-2-amd64

**Comment by AzureOrange404** [comment] 2022-09-01 13:11
Could anyone resolve this issue?

I am having this issue on Arch as well (@FrostbittenKing ), clicking the "Submit" button and nothing happens. (This issue is with every teams version in the AUR and with the Appimage of teams-for-linux as well.)

This is the terminal output I get.

```
configPath = /home/azure/.config/teams-for-linux
Failed to get the config file, using default values
configFile = {}
processArgs [ '/tmp/.mount_teams-idQ7et/teams-for-linux' ]
[45040:0901/145725.791259:ERROR:browser_main_loop.cc(270)] Gtk: gtk_widget_add_accelerator: assertion 'GTK_IS_ACCEL_GROUP (accel_group)' failed
[45040:0901/145725.791501:ERROR:browser_main_loop.cc(270)] Gtk: gtk_widget_add_accelerator: assertion 'GTK_IS_ACCEL_GROUP (accel_group)' failed
[45040:0901/145725.791614:ERROR:browser_main_loop.cc(270)] Gtk: gtk_widget_add_accelerator: assertion 'GTK_IS_ACCEL_GROUP (accel_group)' failed
[45040:0901/145725.791682:ERROR:browser_main_loop.cc(270)] Gtk: gtk_widget_add_accelerator: assertion 'GTK_IS_ACCEL_GROUP (accel_group)' failed
[45040:0901/145725.791743:ERROR:browser_main_loop.cc(270)] Gtk: gtk_widget_add_accelerator: assertion 'GTK_IS_ACCEL_GROUP (accel_group)' failed
[45040:0901/145726.217515:ERROR:browser_main_loop.cc(270)] Gdk: gdk_window_thaw_toplevel_updates: assertion 'window->update_and_descendants_freeze_count > 0' failed
did-finish-load
```

Kind regards

**Comment by jijojosephk** [comment] 2022-09-01 17:19
@AzureOrange404 aren't you using office365? If not, could you share how to reproduce, if this specific to any organisational settings, we need to know.

**Comment by AzureOrange404** [comment] 2022-09-02 22:18
@jijojosephk In my organisation, where I study, we "use" office365 and the credentials are the same as for teams.
When I use teams via browser everything works fine, I get redirected to my organisations login page and login with password and then with OAuth 2FA.

Until beginning of this summer I was using debian 11 and everything worked there on the desktop app. Now on Arch I installed the application with paru, and as an AppImage and I get the same behavior as @joschi36 with the console output seen above.

This means when I start the application, I get prompted for login from Microsoft and then it says redirecting to Organisation login. Then a popup appears asking for username and password. I enter my credential but when I try to submit, nothing happens. The submit button does not seem to be clickable and the popup window does not disappear. Also there is no error displayed.

**Comment by jijojosephk** [comment] 2022-09-04 16:37
@AzureOrange404 I know you're genuinely stuck and I wanted to help. But I don't see that popup for me may be due to the login method used by the org. What I see is this.

![image](https://user-images.githubusercontent.com/11662148/188323744-f9fc7b29-fdfe-4c8c-8065-7f4989f07406.png)

Are you redirected to the popup from this page? I just wanted to understand the flow.

**Comment by joschi36** [comment] 2022-09-04 18:09
@jijojosephk @AzureOrange404 Hi
Maybe I can help. 
O365 sends the auth request to the ADFS server which sends a basic auth form. In this basic auth dialog the submit button doesn't work.
As far as I know you need to integrate it somehow in Electron, see: https://github.com/electron/electron/issues/1362
![image](https://user-images.githubusercontent.com/4538306/188327205-f16e20d1-4c0a-4ca9-8a56-3c150078fbf3.png)
More information about ADFS AzureAD Auth: https://o365blog.com/post/aad-deepdive/

**Comment by AzureOrange404** [comment] 2022-09-04 19:59
@jijojosephk 
> Are you redirected to the popup from this page? I just wanted to understand the flow.
Yes, I enter my email address in this prompt and then I get redirected.

> Hi Maybe I can help. O365 sends the auth request to the ADFS server which sends a basic auth form. In this basic auth dialog the submit button doesn't work. As far as I know you need to integrate it somehow in Electron, see: [electron/electron#1362](https://github.com/electron/electron/issues/1362) 

Then as @joschi36 said, I get the popup from the ADFS server (adfs22.organisation.topdomain), this is where I cannot login due to the submit button not working. (This problem is with all the teams applications there are for Arch (From the AUR and flatpak). In the browser the authentication process works as normal.)
I guess I could use teams via browser for now.

**Comment by jijojosephk** [comment] 2022-09-05 01:58
I get it now. But for me to reproduce, I need to know the domain name which you're using. 

userid`@domain`, Could you help with @domain part?

**Comment by AzureOrange404** [comment] 2022-09-05 07:51
> I get it now. But for me to reproduce, I need to know the domain name which you're using.
> 
> userid`@domain`, Could you help with @Domain part?

Of course, for me I connect to phsg.ch.

**Comment by jijojosephk** [comment] 2022-09-05 08:37
Thanks @AzureOrange404, I'm seeing the popup now. I'm not sure how to test though because multiple attempts during the testing might block me from further testing. Let's see.

**Closed** 2022-09-05 09:33 UTC

**Comment by jijojosephk** [comment] 2022-09-05 09:34
@AzureOrange404 version `1.0.31` being built. You may test once it's out. I'm unable to test the complete functionality but could fix the submit button.

**Comment by AzureOrange404** [comment] 2022-09-05 10:02
> @AzureOrange404 version `1.0.31` being built. You may test once it's out. I'm unable to test the complete functionality but could fix the submit button.

Okay sounds great, I will test it once it's out and then I will reply here. :)

**Comment by jijojosephk** [comment] 2022-09-05 10:04
@AzureOrange404 grab it from [here](https://github.com/IsmaelMartinez/teams-for-linux/releases/tag/v1.0.31)

**Comment by AzureOrange404** [comment] 2022-09-05 10:54
> @AzureOrange404 grab it from [here](https://github.com/IsmaelMartinez/teams-for-linux/releases/tag/v1.0.31)

I did grab the AppImage. 
On the first run, I kinda got stuck on a white screen after logging in (Did not start from console, so I missed any log. But I could wipe it and try again if interested.), 
when I restarted though everything worked like a charm. 

Thank you very much!!
