### ISSUE TITLE
Unable to use screen sharing on Debian 12 (bookworm) [Snap package]

### ISSUE THREAD

**Issue by pallebone** [IsmaelMartinez/teams-for-linux#624] opened 2022-10-11 19:12 UTC
**Describe the bug**
Unable to launch screen sharing from teams app

**To Reproduce**
Join meeting, select screen share option.

**Expected behavior**
Screen share.

**Desktop (please complete the following information):**
 - OS: Debian 12 bookworm (wayland)
 - Snap
 - Latest stable snap

Something to do with pipewire?
Error in terminal is the following:
aragorn@Aragorn:~$ teams-for-linux 
WARNING: Kernel has no file descriptor comparison support: Operation not permitted
[8250:1011/150647.658872:ERROR:browser_main_loop.cc(269)] Gtk: gtk_widget_add_accelerator: assertion 'GTK_IS_ACCEL_GROUP (accel_group)' failed
[8250:1011/150647.659113:ERROR:browser_main_loop.cc(269)] Gtk: gtk_widget_add_accelerator: assertion 'GTK_IS_ACCEL_GROUP (accel_group)' failed
[8250:1011/150647.659195:ERROR:browser_main_loop.cc(269)] Gtk: gtk_widget_add_accelerator: assertion 'GTK_IS_ACCEL_GROUP (accel_group)' failed
[8250:1011/150647.659276:ERROR:browser_main_loop.cc(269)] Gtk: gtk_widget_add_accelerator: assertion 'GTK_IS_ACCEL_GROUP (accel_group)' failed
[8250:1011/150647.659363:ERROR:browser_main_loop.cc(269)] Gtk: gtk_widget_add_accelerator: assertion 'GTK_IS_ACCEL_GROUP (accel_group)' failed
[8250:1011/150710.992873:ERROR:shared_screencast_stream.cc(402)] One of following libraries is missing on your system:
 - PipeWire (libpipewire-0.3.so.0)
 - drm (libdrm.so.2)
[8250:1011/150710.992896:ERROR:base_capturer_pipewire.cc(60)] ScreenCastPortal failed: 1

**Comment by jijojosephk** [comment] 2022-10-12 02:56
@pallebone could you try running with additional flags?

`teams-for-linux --appLogLevels=error,info,warn,debug`

**Comment by SlavikZ** [comment] 2022-10-12 09:43
I have a similar problem with the snap package on ubuntu 22.04. My log with additional flags is
```
[212313:1012/120111.282632:ERROR:bus.cc(562)] Failed to get the ownership of org.mpris.MediaPlayer2.chromium.instance212313: Connection ":1.576" is not allowed to own the service "org.mpris.MediaPlayer2.chromium.instance212313" due to AppArmor policy
[DEBUG] Power save is disabled.
[212459:1012/120119.301820:ERROR:socket_tcp.cc(328)] Error when reading from TCP socket: -101
[OpenH264] this = 0x0x369c11e12460, Warning:Actual input framerate 0.000000 is different from framerate in setting 15.000000, suggest to use other rate control modes
[OpenH264] this = 0x0x369c11e12460, Warning:Actual input framerate 0.000000 is different from framerate in setting 16.000000, suggest to use other rate control modes
[OpenH264] this = 0x0x369c11e12460, Warning:Actual input framerate 0.000000 is different from framerate in setting 16.000000, suggest to use other rate control modes
[212313:1012/120138.589913:ERROR:shared_screencast_stream.cc(402)] One of following libraries is missing on your system:
 - PipeWire (libpipewire-0.3.so.0)
 - drm (libdrm.so.2)
[212313:1012/120138.589945:ERROR:base_capturer_pipewire.cc(60)] ScreenCastPortal failed: 1
[OpenH264] this = 0x0x369c11e12460, Warning:Actual input framerate 0.000000 is different from framerate in setting 13.000000, suggest to use other rate control modes
[OpenH264] this = 0x0x369c11e12460, Warning:Actual input framerate 0.000000 is different from framerate in setting 15.000000, suggest to use other rate control modes

```

**Comment by jijojosephk** [comment] 2022-10-12 10:20
> I have a similar problem with the snap package on ubuntu 22.04. My log with additional flags is
> 
> ```
> [212313:1012/120111.282632:ERROR:bus.cc(562)] Failed to get the ownership of org.mpris.MediaPlayer2.chromium.instance212313: Connection ":1.576" is not allowed to own the service "org.mpris.MediaPlayer2.chromium.instance212313" due to AppArmor policy
> [DEBUG] Power save is disabled.
> [212459:1012/120119.301820:ERROR:socket_tcp.cc(328)] Error when reading from TCP socket: -101
> [OpenH264] this = 0x0x369c11e12460, Warning:Actual input framerate 0.000000 is different from framerate in setting 15.000000, suggest to use other rate control modes
> [OpenH264] this = 0x0x369c11e12460, Warning:Actual input framerate 0.000000 is different from framerate in setting 16.000000, suggest to use other rate control modes
> [OpenH264] this = 0x0x369c11e12460, Warning:Actual input framerate 0.000000 is different from framerate in setting 16.000000, suggest to use other rate control modes
> [212313:1012/120138.589913:ERROR:shared_screencast_stream.cc(402)] One of following libraries is missing on your system:
>  - PipeWire (libpipewire-0.3.so.0)
>  - drm (libdrm.so.2)
> [212313:1012/120138.589945:ERROR:base_capturer_pipewire.cc(60)] ScreenCastPortal failed: 1
> [OpenH264] this = 0x0x369c11e12460, Warning:Actual input framerate 0.000000 is different from framerate in setting 13.000000, suggest to use other rate control modes
> [OpenH264] this = 0x0x369c11e12460, Warning:Actual input framerate 0.000000 is different from framerate in setting 15.000000, suggest to use other rate control modes
> ```

This one looks like AppArmor rejecting the permission.

**Comment by jijojosephk** [comment] 2022-10-12 10:25
@SlavikZ can you try removing and installing again with the following command.

`sudo snap install teams-for-linux --devmode` just to find the cause of it.

**Comment by jijojosephk** [comment] 2022-10-12 10:27
May be you can try a clean install.

`sudo snap remove teams-for-linux`
`rm -rf ~/snap/teams-for-linux`
`sudo snap install teams-for-linux`

**Comment by SlavikZ** [comment] 2022-10-12 11:53
Made a clean install. AppArmor error gone, but the problem still exists. Just after my approval to share screen in the Gnome screen share dialog, the following error appear in the log:
```
[292064:1012/143613.264413:ERROR:shared_screencast_stream.cc(402)] One of following libraries is missing on your system:
 - PipeWire (libpipewire-0.3.so.0)
 - drm (libdrm.so.2)
[292064:1012/143613.264454:ERROR:base_capturer_pipewire.cc(60)] ScreenCastPortal failed: 1
[OpenH264] this = 0x0x1b0415fc7a80, Warning:Actual input framerate 0.000000 is different from framerate in setting 15.000000, suggest to use other rate control modes
```
Could it be related to the absence of `libpipewire-0.3.so.0` and `libdrm.so.2` libraries in the snap?

**Comment by pallebone** [comment] 2022-10-12 12:21
Unsure if apparmor is related. In dmesg all I see when doing a screenshare (I did share screen twice, hence 2 messages) is the following:
```
[60981.778070] Lockdown: rpc-libvirtd: debugfs access is restricted; see man kernel_lockdown.7
[60984.772488] Lockdown: rpc-libvirtd: debugfs access is restricted; see man kernel_lockdown.7
[60987.780313] Lockdown: rpc-libvirtd: debugfs access is restricted; see man kernel_lockdown.7
[60989.254243] audit: type=1326 audit(1665576961.658:460): auid=1000 uid=1000 gid=1000 ses=4 subj=snap.teams-for-linux.teams-for-linux (enforce) pid=203071 comm="teams-for-linux" exe="/snap/teams-for-linux/267/teams-for-linux" sig=0 arch=c000003e syscall=330 compat=0 ip=0x7f12543174e7 code=0x50000
[60990.779517] Lockdown: rpc-libvirtd: debugfs access is restricted; see man kernel_lockdown.7
[60993.786377] Lockdown: rpc-libvirtd: debugfs access is restricted; see man kernel_lockdown.7
[60994.845604] audit: type=1326 audit(1665576967.250:461): auid=1000 uid=1000 gid=1000 ses=4 subj=snap.teams-for-linux.teams-for-linux (enforce) pid=203099 comm="teams-for-linux" exe="/snap/teams-for-linux/267/teams-for-linux" sig=0 arch=c000003e syscall=330 compat=0 ip=0x7f7ff77294e7 code=0x50000
[60996.784871] Lockdown: rpc-libvirtd: debugfs access is restricted; see man kernel_lockdown.7
[60999.784612] Lockdown: rpc-libvirtd: debugfs access is restricted; see man kernel_lockdown.7
```


Running with debug on:
```
aragorn@Aragorn:~$ teams-for-linux --appLogLevels=error,info,warn,debug
[DEBUG] configPath:,/home/aragorn/snap/teams-for-linux/267/.config/teams-for-linux
[INFO] Failed to get the config file, using default values
[DEBUG] configFile:,[object Object]
[INFO] Running under Wayland, switching to PipeWire...
[DEBUG] processArgs:,/snap/teams-for-linux/267/teams-for-linux,--appLogLevels=error,info,warn,debug,--no-sandbox
[203199:1012/081734.237883:ERROR:browser_main_loop.cc(269)] Gtk: gtk_widget_add_accelerator: assertion 'GTK_IS_ACCEL_GROUP (accel_group)' failed
[203199:1012/081734.238051:ERROR:browser_main_loop.cc(269)] Gtk: gtk_widget_add_accelerator: assertion 'GTK_IS_ACCEL_GROUP (accel_group)' failed
[203199:1012/081734.238111:ERROR:browser_main_loop.cc(269)] Gtk: gtk_widget_add_accelerator: assertion 'GTK_IS_ACCEL_GROUP (accel_group)' failed
[203199:1012/081734.238167:ERROR:browser_main_loop.cc(269)] Gtk: gtk_widget_add_accelerator: assertion 'GTK_IS_ACCEL_GROUP (accel_group)' failed
[203199:1012/081734.238225:ERROR:browser_main_loop.cc(269)] Gtk: gtk_widget_add_accelerator: assertion 'GTK_IS_ACCEL_GROUP (accel_group)' failed
WARNING: Kernel has no file descriptor comparison support: Operation not permitted
[DEBUG] did-finish-load
[DEBUG] did-finish-load
[DEBUG] Power save is disabled.
[DEBUG] Playing file: /snap/teams-for-linux/267/resources/assets/sounds/meeting_started.wav
[203199:1012/081802.926401:ERROR:shared_screencast_stream.cc(402)] One of following libraries is missing on your system:
 - PipeWire (libpipewire-0.3.so.0)
 - drm (libdrm.so.2)
[203199:1012/081802.926421:ERROR:base_capturer_pipewire.cc(60)] ScreenCastPortal failed: 1
[DEBUG] Power save is restored
[DEBUG] window close
[DEBUG] window closed
[DEBUG] before-quit
[DEBUG] will-quit
[DEBUG] quit
aragorn@Aragorn:~$ 
```

To me this reads as apparmor not being at fault but happy to be corrected. Normally if apparmor is preventing something I expect to see something like:

audit: type=1400 audit(1654866935.001:11322): apparmor="DENIED" operation="open" profile="snap.NameOfSnap" name="/var/lib/snapd/hostfs/usr/lib/x86_64-linux-gnu/" pid=3402935 comm="x86_64-linux-gn" requested_mask="r" denied_mask="r" fsuid=1000 ouid=0

**Comment by jijojosephk** [comment] 2022-10-13 04:34
@IsmaelMartinez any clue on this one? Is pipewire properly installed @pallebone?

**Comment by IsmaelMartinez** [comment] 2022-10-13 06:26
No idea but sounds more of a snap shenanigans. Can you try one of the other packages (Deb, etc) and see if it works?

**Comment by SlavikZ** [comment] 2022-10-13 06:29
AppImage works without any problems.

**Comment by IsmaelMartinez** [comment] 2022-10-13 15:36
Then is probably snap and maybe some strange permission. To test this, try to install the app with sudo. if it works that will indicate your snap installation is a bit "particular". Just a guess

**Comment by IsmaelMartinez** [comment] 2022-10-13 15:38
Ignore, I just saw your previous message... Now, you should not need to install packages in snap as sudo. If they aren't working without sudo, that means something is off with the installation.

**Comment by pallebone** [comment] 2022-10-13 16:01
It is normal to need to use sudo to install a snap app. If you omit sudo all that happens is the password prompt appears on the screen graphically with a prompt.

**Comment by IsmaelMartinez** [comment] 2022-10-14 02:30
I am not in Linux anymore reason why I am a bit blind on this. Check if you
can enable the screen share permission in the snap app. Maybe it didn't
trigger in your installation.

Again, I remember snap been a pain for some people.

**Comment by pallebone** [comment] 2022-10-14 12:57
I have tried to do this but have not been able to find a solution to the issue or enable it in any way with things like passing arguments (enable-webrtc-pipewire-capturer) or installing libraries. Still the error persists that : 
"One of following libraries is missing on your system:
 - PipeWire (libpipewire-0.3.so.0)
 - drm (libdrm.so.2)"

unsure how to proceed. Nothing I try is able to resolve.

**Comment by IsmaelMartinez** [comment] 2022-10-14 21:43
It must be related to your snap installation if it works using a Deb package. I suggest you try to uninstall snap and install/config it again. That is a pain tbh, so will understand if that is a no go. Check if another snap apps that share (or record) the screen works as they might give you another clue of where to look for. Sorry I can't help much more.

**Comment by pallebone** [comment] 2022-10-15 11:21
Interesting. Unsure how I could have setup snap wrong as its fairly basic to install. I wonder if other users will begin to have this issue when the next version of ubuntu comes out as it pulls from debian testing. 

As we dont know what to do next I will leave this issue open but wait to see if anyone else reports the issue as I imagine other people might. 

You dont think it has anything to do with missing libraries as per the initial snap error? Seems rather specific. 

Either way happy to wait for a while and see what happens.

- P

**Comment by pallebone** [comment] 2023-03-03 20:51
maybe they can be added in a hope to fix the issue?

**Comment by IsmaelMartinez** [comment] 2023-03-12 20:04
I have no idea how we can add that to the snap package. I thought snap will do it for you, but feels strange. Have you check you have given the right permission to the snap package?

**Comment by pallebone** [comment] 2023-03-14 18:25
@IsmaelMartinez snap packages require the developer to bundle the dependencies within the snap. That is why they are larger, there is no way for the self contained snap package to avoid this as the entire idea is a snap package contains everything it needs to run in a single package.

**Comment by dmurzaikins** [comment] 2023-03-14 18:43
> I thought snap will do it for you

Looks like it tries to guess (but might fail?), but still require manually list packages: https://snapcraft.io/docs/build-and-staging-dependencies#heading--missing-staging
I tried adding [`stagePackages`](https://www.electron.build/configuration/snap) section to `package.json`, but was unable to resolve build errors.

**Comment by IsmaelMartinez** [comment] 2023-03-15 13:24
Would you be able to take a look at the 'CONTRIBUTING.md' file on the following GitHub repository: https://github.com/IsmaelMartinez/teams-for-linux/blob/develop/CONTRIBUTING.md? I am wondering if you could create a local snap package using the instructions provided in the 'snap-build' section of the file and test it to see if it works. If it does, it would be fantastic if you could create a pull request with the necessary changes. The community would be very grateful for your contribution.

**Comment by pallebone** [comment] 2023-04-05 12:34
I have retested this issue on the latest teams (latest/stable:    1.0.55 2023-03-22 (300) 85MB) and it is now working so something has changed between 1.0.45 and 1.0.55 to make it work. Anyone else now have it working?

Kind regards
Peter

**Comment by dmurzaikins** [comment] 2023-04-05 13:11
Not working on my end, tried 1.0.55 and 1.0.58 from edge.

**Comment by pallebone** [comment] 2023-04-05 15:31
> Not working on my end, tried 1.0.55 and 1.0.58 from edge.

Do you have both libraries installed?
sudo apt-get install libpipewire-0.3-0 libdrm2

**Comment by jijojosephk** [comment] 2023-05-02 02:11
Duplicate of #765

**Comment by jijojosephk** [comment] 2023-05-12 03:05
@pallebone I tried every possible things to fix. Snap team has to fix the underlying issues. Closing this for now. If you're ok, please switch to flatpak or even any native package. If you later find some fix is available in electron or snap, please re-open this issue.

**Closed by jijojosephk** 2023-05-12 03:05 UTC
Labels: snap, wayland, ubuntu
