### ISSUE TITLE
screen share broken on ubuntu 22.04 with snap package.

### ISSUE THREAD

**Issue by petersilva** [IsmaelMartinez/teams-for-linux#526] opened 2022-03-31 19:36 UTC
**Describe the bug**
I have a ubuntu 22.04 installed, and everything seems fine, when I try to share content
in a call ... it gives me the first dialog for sharing screens, then a second dialog where I can choose
the entire screen or a single window.  It doesn't matter which one I pick, share never works.

**To Reproduce**
1. Install from Snap Store
2. Click on Share Content
3. Choose screen or window to share.
4. othe people on the call do not see the shared content.

**Expected behavior**
People should see the screen or window I am trying to share.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: ubuntu 22.04
 - Installation package snap
 - Version 1.0.24
**Additional context**

**Comment by IsmaelMartinez** [comment] 2022-04-01 06:36
Can you check the closed issues? Some people had a similar issue and was
sorted (something to do with Wayland). It could also be a snap
configuration issue.

If the later, you can check if that works fine using another package
distribution. Hope helps

**Comment by kon14** [comment] 2022-04-04 18:35
I bet this is the exact same bug I've been hitting in Fedora 36 (Gnome 42).
Happens consistently across Chromium/Electron and OBS, with FF working fine and all of them working perfectly in Fedora 35 (Gnome 41).

OBS pretty much rules out being a Chromium-specific regression, but it's also not a full-blown PipeWire/xdg-desktop-portal one either as FF remains functional and it can't be an app regression as same versions remain functional if a roll back to 35 🤔.

I'll try out Sway to confirm whether it's a Gnome 42 regression, otherwise it's probably a portal/pw update thing.

**Comment by luis-alves** [comment] 2022-05-16 14:30
Since upgrading to Fedora 36 I've the same problem.

**Comment by whisperity** [comment] 2022-05-18 10:59
Ubuntu 18.04 with KDE, X11. It was broken for a while, then started working again, then now broken again.

**Comment by IsmaelMartinez** [comment] 2022-05-18 18:41
Hi, have any of you tried with another package manager?

**Comment by whisperity** [comment] 2022-05-19 07:50
> Hi, have any of you tried with another package manager? 

@IsmaelMartinez Hey! I have the thing installed natively.

**Comment by hierr** [comment] 2022-05-23 21:59
Also stopped working for me after updating to Ubuntu 22.04 from 21.10. Installed via .deb package.

**Comment by josemcvgh** [comment] 2022-06-18 11:12
Hi, I have had the same problem, I got an error when trying to share the screen from teams-for-linux, I am not an expert in linux, but by insisting in the end I got a (temporary) way to share the desktop screen.
 
I have used as a bridge a **Firefox window with google meet** capturing the screen. I give to present without microphone and without webcam.

Then, in a **chrome browser window, I launch teams online**, and activate the microphone and webcam. Then I present the previous firefox tab that contains the screenshot.

This has worked for me now.

I did several tests and among other things I installed the following:

- lsb_release -a    #### Distributor ID:    Ubuntu    #### Description:    Ubuntu 22.04 LTS    #### Release:    22.04    #### Codename:    jammy
 
- cat /proc/version    #### Linux version 5.15.0-39-generic (buildd@lcy02-amd64-069) (gcc (Ubuntu 11.2.0-19ubuntu1) 11.2.0, GNU ld (GNU Binutils for Ubuntu) 2.38) #42-Ubuntu SMP Thu Jun 9 23:42:32 UTC 2022
 
- teams-for-linux    #### 1.0.24
 
- microsoft teams    #### teams_1.5.00.10453_amd64.deb
 
- teams online, con una cuenta profesional (https://teams.microsoft.com)    #### Versión 1.0
 
- google-chrome --version    #### Google Chrome 102.0.5005.115
 
- firefox --version    #### Mozilla Firefox 101.0.1

- ffmpeg -version    #### ffmpeg version 4.4.2-0ubuntu0.22.04.1 Copyright (c) 2000-2021 the FFmpeg developers    #### built with gcc 11 (Ubuntu 11.2.0-19ubuntu1)


I hope someone finds it helpful.

**Comment by ThePsyjo** [comment] 2022-08-04 14:35
This might be the solution, it fixes screen sharing for me: https://github.com/IsmaelMartinez/teams-for-linux/pull/545

**Comment by jijojosephk** [comment] 2022-08-05 13:50
@ThePsyjo you just renamed an IPC message name. It should not fix the actual problem.

**Comment by kon14** [comment] 2022-08-05 16:04
> @ThePsyjo you just renamed an IPC message name. It should not fix the actual problem.

I'll test this as soon as I get the chance to do so.
I had already previously rebased `v1.0.24` to Electron `v19.0.9` for a custom Flatpak build of mine and everything worked as expected, so hopefully this one will do so as well.

**Comment by jijojosephk** [comment] 2022-08-14 02:05
Closing this as there's no activity. Please re-open if required.

**Comment by jijojosephk** [comment] 2022-08-20 04:47
@petersilva @kon14 @luis-alves @whisperity @hierr @josemcvgh could you check if the latest version works? `1.0.29`

**Comment by luis-alves** [comment] 2022-08-20 08:40
It works now @jijojosephk

**Comment by jijojosephk** [comment] 2022-08-20 08:46
@luis-alves Thanks, closing this.

**Closed by jijojosephk** 2022-08-20 08:46 UTC
Labels: bug, snap
