### ISSUE TITLE
Loop when launching

### ISSUE THREAD

**Issue by crochut** [IsmaelMartinez/teams-for-linux#98] opened 2019-04-09 09:25 UTC
**Describe the bug**
When i run teams for linux the connexion page is opened and close with infinite loop,
this happening after version 0.1.11. The version 0.1.11 works fine after this version, i have this issue. 
I've tried to clean all installation and configuration but nothing works.
I don't know how to solve this issue. 
Anyone can help me ?

Best regards

**To Reproduce**
1. Install package by yum
2. launch teams

**Expected behavior**
Teams start and launch.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Centos 7.4
 - Installation package [rpm]
 - Version [e.g. 0.1.17]

**Additional context**

**Comment by IsmaelMartinez** [comment] 2019-04-09 15:44
Hi, is it possible for you to try from source? I think it might be the online/offline check but that was introduced on version 0.1.13. 

If you can't try from source, the best I can do is to add an option to disable that online/offline but will need you to test that version 0.1.12 works fine (otherwise, it will be another issue)

**Comment by crochut** [comment] 2019-04-09 16:03
Hi, thank for your answer.

I confirm that the 0.1.12 works.

But i needed to force a refresh to see the interface (before the force refresh i had a violet page).

After the refresh, the interface was appeared.

So i think you're right, the issue is probably due to  online/offline check.

Best regards

Cyrille ROCHUT
Service Support Métier
GFIT

Prélodis 3 - 27 rue marcel Mérieux - 69960 Corbas

T : 04 37 23 60 96

[cid:part1.EF29F9A3.B759E6F1@gfit.fr]
Retrouvez nous sur wwww.grandfrais.com<http://wwww.grandfrais.com>
Le 09/04/2019 à 17:44, IsmaelMartinez a écrit :

Hi, is it possible for you to try from source? I think it might be the online/offline check but that was introduced on version 0.1.13.

If you can't try from source, the best I can do is to add an option to disable that online/offline but will need you to test that version 0.1.12 works fine (otherwise, it will be another issue)

**Comment by IsmaelMartinez** [comment] 2019-04-09 20:49
Ok, so this will need to wait until I got time to implement that config option/flag. Probably end of this month or early next month (then I am on holidays for a few weeks)

If you (or someone reading this) got the time, you can try to do a PR. The change is to add another config option for onlineOfflineReload (or something down those lines) and add it in this file.

https://github.com/IsmaelMartinez/teams-for-linux/blob/master/app/index.js#L54

Following the same pattern as the webDebug. (just a few lines below that one)

You will need to add that option to the index.js config file 
https://github.com/IsmaelMartinez/teams-for-linux/blob/master/app/config/index.js

and update the README.md in that config folder.

**Comment by crochut** [comment] 2019-04-10 06:10
Thanks !

I'll try to find some times to implements that feature and push it on git....

BR


Cyrille ROCHUT
Service Support Métier
GFIT

Prélodis 3 - 27 rue marcel Mérieux - 69960 Corbas

T : 04 37 23 60 96

[cid:part1.270FD6F2.07EE0D22@gfit.fr]
Retrouvez nous sur wwww.grandfrais.com<http://wwww.grandfrais.com>
Le 09/04/2019 à 22:49, IsmaelMartinez a écrit :

Ok, so this will need to wait until I got time to implement that config option/flag. Probably end of this month or early next month (then I am on holidays for a few weeks)

If you (or someone reading this) got the time, you can try to do a PR. The change is to add another config option for onlineOfflineReload (or something down those lines) and add it in this file.

https://github.com/IsmaelMartinez/teams-for-linux/blob/master/app/index.js#L54

Following the same pattern as the webDebug. (just a few lines below that one)

You will need to add that option to the index.js config file
https://github.com/IsmaelMartinez/teams-for-linux/blob/master/app/config/index.js

and update the README.md in that config folder.

**Comment by IsmaelMartinez** [comment] 2019-04-10 06:52
Shout if you got any questions! Thanks

**Comment by crochut** [comment] 2019-04-11 08:42
Hi, 
i've tried to disable the online/offline check and it's still looping. 
So the issue is elsewhere ...

**Comment by IsmaelMartinez** [comment] 2019-04-11 19:10
can you make sure that you clean the app installation before running from source (I assume you are running from source to be able to disable the online/offline check)? is there any logs in the console? Thanks

**Comment by crochut** [comment] 2019-04-12 07:51
Ok i'll try to do that, and give you the result

**Comment by crochut** [comment] 2019-04-12 12:58
Same comportement after that. 
The console stop and the electron stop and start (new pid on each occurence).

**Comment by IsmaelMartinez** [comment] 2019-04-12 13:30
that is strange, I have added the option to stop that online/offline stuff as that was the only real change between version 0.1.2 and 0.1.3. 

I will releease it just next in version 0.2.0. Can you try it (with `teams-for-linux --onlineOfflineReload false` ) and see if that works? Thanks

**Comment by crochut** [comment] 2019-04-12 13:45
Ok i will try it.

Thanks

Cyrille ROCHUT
Service Support Métier
GFIT

Prélodis 3 - 27 rue marcel Mérieux - 69960 Corbas

T : 04 37 23 60 96

[cid:part1.73CE6C22.ED17AFEB@gfit.fr]
Retrouvez nous sur wwww.grandfrais.com<http://wwww.grandfrais.com>
Le 12/04/2019 à 15:30, IsmaelMartinez a écrit :

that is strange, I have added the option to stop that online/offline stuff as that was the only real change between version 0.1.2 and 0.1.3.

I will releease it just next in version 0.2.0. Can you try it (with teams-for-linux --onlineOfflineReload false ) and see if that works? Thanks

**Comment by crochut** [comment] 2019-05-13 08:41
Hi Ismael, 
i've installed the 2.0 version and running it with --onlineOfflineReload=false option. 
Same issue. 
I've made a screencast video to help you. 
![Capture d’écran vidéo de 13-05-2019 10_26_05](https://user-images.githubusercontent.com/37068009/57607488-75370000-756b-11e9-9eaf-0f3154221a2f.gif)


I've a segmation fault before the loop start. 

Best regards

**Comment by crochut** [comment] 2019-05-13 08:44
I can't reopen this issue due to github rules 

"you cannot re-open your own issues if a repo collaborator closed them"

**Comment by IsmaelMartinez** [comment] 2019-05-18 19:57
Still pretty puzzle by this. Can you run from source and make sure you are using node 10 and electron 4? Might be one of those strange Linux dependencies

**Comment by StefanTT** [comment] 2019-05-23 09:41
I have the same issue. Arch linux, which installs it from source.
Could it be that proxy is not supported?

**Comment by IsmaelMartinez** [comment] 2019-05-27 11:24
I wonder if this is an issue with this https://github.com/IsmaelMartinez/teams-for-linux/issues/51

When blocking hte app from running twice, we are just trying to bring it into focus.

We are not doing anything special for proxy, so maybe is time to check if related.

maybe check electron configuration and see if it can be fixed that way.
https://electronjs.org/docs/api/session#sessetproxyconfig-callback

**Comment by crochut** [comment] 2019-05-29 14:12
I think that proxy is a good track ...

I will try this asap.

Best regards

Cyrille ROCHUT
Service Support Métier
GFIT

Prélodis 3 - 27 rue marcel Mérieux - 69960 Corbas

T : 04 37 23 60 96

[cid:part1.459AC576.5F399ED2@gfit.fr]
Retrouvez nous sur wwww.grandfrais.com<http://wwww.grandfrais.com>
Le 27/05/2019 à 13:24, IsmaelMartinez a écrit :

I wonder if this is an issue with this #51<https://github.com/IsmaelMartinez/teams-for-linux/issues/51>

When blocking hte app from running twice, we are just trying to bring it into focus.

We are not doing anything special for proxy, so maybe is time to check if related.

maybe check electron configuration and see if it can be fixed that way.
https://electronjs.org/docs/api/session#sessetproxyconfig-callback

**Comment by IsmaelMartinez** [comment] 2019-06-27 06:14
Did you manage to test the proxy part?

**Comment by StefanTT** [comment] 2019-06-27 06:50
I updated to the current master version. It looks like the proxy works now :+1:
I can do the usual login stuff and the web development console's network view shows
the javascript bundles being downloaded. So everything seems fine.

However I end up with a white window and some nasty looking javascript errors, but this is probably not a proxy issue and therefore off topic in this case.

**Comment by IsmaelMartinez** [comment] 2019-06-27 07:31
Hi, 

If you then do Ctrl+R (or refresh in the task bar menu) does it go then throw?

Initial loads are sometimes temperamental ta

**Comment by crochut** [comment] 2019-06-27 07:41
Hi Stefan,

Which master version did you update ? Electron ?

I've tried to install last version of teams for linux, and i've the same issue.

I've tried to do what Ismeal recommanded, but so hard for me, not enough time ...

Cyrille ROCHUT
Service Support Métier
GFIT

Prélodis 3 - 27 rue marcel Mérieux - 69960 Corbas

T : 04 37 23 60 96

[cid:part1.885B05C7.0DE082BF@gfit.fr]
Retrouvez nous sur wwww.grandfrais.com<http://wwww.grandfrais.com>
Le 27/06/2019 à 08:50, Stefan Taferner a écrit :

I updated to the current master version. It looks like the proxy works now 👍
I can do the usual login stuff and the web development console's network view shows
the javascript bundles being downloaded. So everything seems fine.

However I end up with a white window and some nasty looking javascript errors, but this is probably not a proxy issue and therefore off topic in this case.

**Comment by StefanTT** [comment] 2019-06-27 09:57
I use Arch on this machine. I took the package build script for teams-for-linux and replaced the release version 0.3.0 with the latest master that I downloaded manually. The package build does not fiddle with anything so it's the package.json and stuff as it is checked in.

I try to write down the steps I see during initial login:

Started the app in a terminal with teams-for-linux --webDebug=true

The application opens with a small dialog for email or domain\username and password.
In the background I see network traffic for prelogin (http 200), authorize (http 302), ?login_hint (http 302), wia (pending).

I enter my email and password, the dialog closes and some loading happens. Then the white main page shows and the network dialog has a bunch of entries for the "_" document, 3.2-app.min. extra.js .... all with http 200. Inspecting the white main page shows that the Angular application got loaded, it's not simply an empty page.

Pressing Ctrl-R reloads the page with the same set of document + scripts, nothing more.

The javascript console shows several errors (hopefully this is readable with copy&paste):

```
The Content-Security-Policy directive 'prefetch-src' is implemented behind a flag which is currently disabled.

_:367 index.html: register for events
_:373 index.html: check for appcache update. State: 2
_:383 index.html: update not ready, continue with app start
_:440 index.html: unregister all service workers
_:1 Adding master entry to Application Cache with manifest https://teams.microsoft.com/skypespaces.web.appcache
bootstrap.min.js:1 Uncaught Error: Bootstrap's JavaScript requires jQuery
    at bootstrap.min.js:1
(anonymous) @ bootstrap.min.js:1
internal/modules/cjs/loader.js:584 Uncaught Error: Cannot find module 'angular'
    at Module._resolveFilename (internal/modules/cjs/loader.js:584)
    at Function.Module._resolveFilename (/opt/teams-for-linux/resources/electron.asar/common/reset-search-paths.js:43)
    at Function.Module._load (internal/modules/cjs/loader.js:510)
    at Module.require (internal/modules/cjs/loader.js:640)
    at require (internal/modules/cjs/helpers.js:20)
    at angucomplete-alt.min.js:1
    at angucomplete-alt.min.js:1
Module._resolveFilename @ internal/modules/cjs/loader.js:584
Module._resolveFilename @ /opt/teams-for-linux/resources/electron.asar/common/reset-search-paths.js:43
Module._load @ internal/modules/cjs/loader.js:510
Module.require @ internal/modules/cjs/loader.js:640
require @ internal/modules/cjs/helpers.js:20
(anonymous) @ angucomplete-alt.min.js:1
(anonymous) @ angucomplete-alt.min.js:1
app.min.js:1 Uncaught ReferenceError: Mousetrap is not defined
    at teamspace (app.min.js:1)
    at app.min.js:1
teamspace @ app.min.js:1
(anonymous) @ app.min.js:1
msteams-web-bridge.min.js:1 Uncaught TypeError: Cannot read property 'Services' of undefined
    at Object.8942317fc3a8f9a4d48e (msteams-web-bridge.min.js:1)
    at n (msteams-web-bridge.min.js:1)
    at Object.4c259643f4d55b331b73 (msteams-web-bridge.min.js:1)
    at n (msteams-web-bridge.min.js:1)
    at 038c6930ca24f8acf886 (msteams-web-bridge.min.js:1)
    at msteams-web-bridge.min.js:1
8942317fc3a8f9a4d48e @ msteams-web-bridge.min.js:1
n @ msteams-web-bridge.min.js:1
4c259643f4d55b331b73 @ msteams-web-bridge.min.js:1
n @ msteams-web-bridge.min.js:1
038c6930ca24f8acf886 @ msteams-web-bridge.min.js:1
(anonymous) @ msteams-web-bridge.min.js:1
_:1 Application Cache NoUpdate event
extra.js:10642 Uncaught TypeError: Cannot read property 'push' of undefined
    at extra.js:10642
(anonymous) @ extra.js:10642
_:1159 Loading stylesheet: https://statics.teams.microsoft.com/hashedcss/stylesheets.theme-default.min-0b520117.css
_:1204 Uncaught ReferenceError: $ is not defined
    at _:1204
(anonymous) @ _:1204
_:1180 Loaded stylesheet: https://statics.teams.microsoft.com/hashedcss/stylesheets.theme-default.min-0b520117.css
_:349 index.html: cache up-to-date
_:356 index.html: remove startup cache listeners
_:1200 Uncaught ReferenceError: $ is not defined
    at _:1200
    at lodash.min.js:21
(anonymous) @ _:1200
(anonymous) @ lodash.min.js:21
setTimeout (async)
jo @ lodash.min.js:81
xt @ lodash.min.js:21
(anonymous) @ lodash.min.js:86
r @ lodash.min.js:1
(anonymous) @ lodash.min.js:59
(anonymous) @ _:1199
fnDoneWrapper @ _:1162
link.onload @ _:1184
load (async)
setStylesheetFromCookie @ _:1179
(anonymous) @ _:1198
```
After a while the oops page gets loaded. When I click logout there then I am adviced to close the application. I do it and start it again. I am then prompted to select my identity. Then I am back at the start with the enter email/password dialog.

**Comment by crochut** [comment] 2019-06-27 10:08
@Stefan : The logs says that angular is not found, it is the main front framework, if this framework is not found, the app cannot start.

I think that you need to build the project from source, if you want to start the master branch.

@Ismael : is that ok ?

Best regards

Cyrille ROCHUT
Service Support Métier
GFIT

Prélodis 3 - 27 rue marcel Mérieux - 69960 Corbas

T : 04 37 23 60 96

[cid:part1.F948F77C.C2F1EC3A@gfit.fr]
Retrouvez nous sur wwww.grandfrais.com<http://wwww.grandfrais.com>
Le 27/06/2019 à 11:57, Stefan Taferner a écrit :

I use Arch on this machine. I took the package build script for teams-for-linux and replaced the release version 0.3.0 with the latest master that I downloaded manually. The package build does not fiddle with anything so it's the package.json and stuff as it is checked in.

I try to write down the steps I see during initial login:

Started the app in a terminal with teams-for-linux --webDebug=true

The application opens with a small dialog for email or domain\username and password.
In the background I see network traffic for prelogin (http 200), authorize (http 302), ?login_hint (http 302), wia (pending).

I enter my email and password, the dialog closes and some loading happens. Then the white main paget ashows and the network dialog has a bunch of entries for the "_" document, 3.2-app.min. extra.js .... all with http 200. Inspecting the white main page shows that the Angular application got loaded, it's not simply an empty page.

Pressing Ctrl-R reloads the page with the same set of document + scripts, nothing more.

The javascript console shows several errors (hopefully this is readable with copy&paste):

The Content-Security-Policy directive 'prefetch-src' is implemented behind a flag which is currently disabled.

_:367 index.html: register for events
_:373 index.html: check for appcache update. State: 2
_:383 index.html: update not ready, continue with app start
_:440 index.html: unregister all service workers
_:1 Adding master entry to Application Cache with manifest https://teams.microsoft.com/skypespaces.web.appcache
bootstrap.min.js:1 Uncaught Error: Bootstrap's JavaScript requires jQuery
    at bootstrap.min.js:1
(anonymous) @ bootstrap.min.js:1
internal/modules/cjs/loader.js:584 Uncaught Error: Cannot find module 'angular'
    at Module._resolveFilename (internal/modules/cjs/loader.js:584)
    at Function.Module._resolveFilename (/opt/teams-for-linux/resources/electron.asar/common/reset-search-paths.js:43)
    at Function.Module._load (internal/modules/cjs/loader.js:510)
    at Module.require (internal/modules/cjs/loader.js:640)
    at require (internal/modules/cjs/helpers.js:20)
    at angucomplete-alt.min.js:1
    at angucomplete-alt.min.js:1
Module._resolveFilename @ internal/modules/cjs/loader.js:584
Module._resolveFilename @ /opt/teams-for-linux/resources/electron.asar/common/reset-search-paths.js:43
Module._load @ internal/modules/cjs/loader.js:510
Module.require @ internal/modules/cjs/loader.js:640
require @ internal/modules/cjs/helpers.js:20
(anonymous) @ angucomplete-alt.min.js:1
(anonymous) @ angucomplete-alt.min.js:1
app.min.js:1 Uncaught ReferenceError: Mousetrap is not defined
    at teamspace (app.min.js:1)
    at app.min.js:1
teamspace @ app.min.js:1
(anonymous) @ app.min.js:1
msteams-web-bridge.min.js:1 Uncaught TypeError: Cannot read property 'Services' of undefined
    at Object.8942317fc3a8f9a4d48e (msteams-web-bridge.min.js:1)
    at n (msteams-web-bridge.min.js:1)
    at Object.4c259643f4d55b331b73 (msteams-web-bridge.min.js:1)
    at n (msteams-web-bridge.min.js:1)
    at 038c6930ca24f8acf886 (msteams-web-bridge.min.js:1)
    at msteams-web-bridge.min.js:1
8942317fc3a8f9a4d48e @ msteams-web-bridge.min.js:1
n @ msteams-web-bridge.min.js:1
4c259643f4d55b331b73 @ msteams-web-bridge.min.js:1
n @ msteams-web-bridge.min.js:1
038c6930ca24f8acf886 @ msteams-web-bridge.min.js:1
(anonymous) @ msteams-web-bridge.min.js:1
_:1 Application Cache NoUpdate event
extra.js:10642 Uncaught TypeError: Cannot read property 'push' of undefined
    at extra.js:10642
(anonymous) @ extra.js:10642
_:1159 Loading stylesheet: https://statics.teams.microsoft.com/hashedcss/stylesheets.theme-default.min-0b520117.css
_:1204 Uncaught ReferenceError: $ is not defined
    at _:1204
(anonymous) @ _:1204
_:1180 Loaded stylesheet: https://statics.teams.microsoft.com/hashedcss/stylesheets.theme-default.min-0b520117.css
_:349 index.html: cache up-to-date
_:356 index.html: remove startup cache listeners
_:1200 Uncaught ReferenceError: $ is not defined
    at _:1200
    at lodash.min.js:21
(anonymous) @ _:1200
(anonymous) @ lodash.min.js:21
setTimeout (async)
jo @ lodash.min.js:81
xt @ lodash.min.js:21
(anonymous) @ lodash.min.js:86
r @ lodash.min.js:1
(anonymous) @ lodash.min.js:59
(anonymous) @ _:1199
fnDoneWrapper @ _:1162
link.onload @ _:1184
load (async)
setStylesheetFromCookie @ _:1179
(anonymous) @ _:1198


After a while the oops page gets loaded. When I click logout there then I am adviced to close the application. I do it and start it again. I am then prompted to select my identity. Then I am back at the start with the enter email/password dialog.

**Comment by StefanTT** [comment] 2019-06-27 10:17
It is built from source to my understanding. These two commands get executed when packaging:
```
yarn install --non-interactive --pure-lockfile --cache-folder ../yarn-cache
yarn build --x64 --linux dir
```
But I am fine if you say this is not related to the problem, I do not want to mix issues.

**Comment by IsmaelMartinez** [comment] 2019-07-02 15:24
hi, i think the develop branch was a bit funny for a few days.

I did update some packages (minor versions) but that seems to have broke the initialization (that not he build). 

I have revert it so the "angular" issue should be sorted now. Can you check if the latests  0.3.2 works for you ? if using snap it should be the one that is in the edge channel (I can't use snap myself due company constrains)

**Comment by StefanTT** [comment] 2019-07-02 18:00
I will try the latest git version tomorrow @work and report back.

**Comment by StefanTT** [comment] 2019-07-03 08:30
Success!

The current GIT master properly works with a proxy, I think the issue is fixed.

A quick test of screen sharing and voice conference also looks fine btw (under X11).

**Comment by IsmaelMartinez** [comment] 2019-07-03 10:35
But I think your issue @StefanTT  and @crochut  are different so not closing this for now.

**Comment by StefanTT** [comment] 2019-07-03 10:40
ok, if you say so ....

I tried it on the same computer back then: with proxy I got the infinite loop, without proxy it worked. Now it is fixed for me with proxy. But let's see what @crochut says :-)

**Comment by crochut** [comment] 2019-07-05 09:56
Hi,

i work on centos 7, when i trie to build master branch i've got this error:

$ electron-builder --linux
Configuring yargs through package.json is deprecated and will be removed in the next major release, please use the JS API instead.
Configuring yargs through package.json is deprecated and will be removed in the next major release, please use the JS API instead.
/home/crochut/projets/teams-for-linux/node_modules/read-config-file/out/main.js:71
async function readConfig(configFile, request) {
      ^^^^^^^^

SyntaxError: Unexpected token function
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:549:28)
    at Object.Module._extensions..js (module.js:586:10)
    at Module.load (module.js:494:32)
    at tryModuleLoad (module.js:453:12)
    at Function.Module._load (module.js:445:3)
    at Module.require (module.js:504:17)
    at require (internal/module.js:20:19)
    at _readConfigFile (/home/crochut/projets/teams-for-linux/node_modules/electron-builder/src/cli/cli.ts:10:1)
    at Object.args [as handler] (/home/crochut/projets/teams-for-linux/node_modules/electron-builder/src/cli/cli.ts:45:5)
    at Object.runCommand (/home/crochut/projets/teams-for-linux/node_modules/yargs/lib/command.js:242:26)
    at Object.parseArgs [as _parseArgs] (/home/crochut/projets/teams-for-linux/node_modules/yargs/yargs.js:1104:24)
    at Object.get [as argv] (/home/crochut/projets/teams-for-linux/node_modules/yargs/yargs.js:1012:21)
    at Object.<anonymous> (/home/crochut/projets/teams-for-linux/node_modules/electron-builder/src/cli/cli.ts:19:1)
    at Module._compile (module.js:577:32)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

npm version : 3.10.10

node version : v6.17.1 (so old but offical version on centos)

yarn version : v1.16.0



Cyrille ROCHUT
Service Support Métier
GFIT

Prélodis 3 - 27 rue marcel Mérieux - 69960 Corbas

T : 04 37 23 60 96

[cid:part1.7692F9D4.F6388958@gfit.fr]
Retrouvez nous sur wwww.grandfrais.com<http://wwww.grandfrais.com>
Le 03/07/2019 à 12:40, Stefan Taferner a écrit :

ok, if you say so ....

I tried it on the same computer back then: with proxy I got the infinite loop, without proxy it worked. Now it is fixed for me with proxy. But let's see what @crochut<https://github.com/crochut> says :-)

**Comment by IsmaelMartinez** [comment] 2019-07-05 12:38
Electron builder requires node V8 (recommended 10). 

Can you try getting the snap package from edge channel??

**Comment by crochut** [comment] 2019-07-05 12:50
hi i've installed nvm and install node v10.16,

so i can build but not package it into rpm

{:timestamp=>"2019-07-05T14:20:58.955126+0200", :message=>"Need executable 'rpmbuild' to convert dir to rpm", :level=>:error}

So i install rpmbuild but got this error;

warning rpmbuild > graceful-fs@2.0.3<mailto:graceful-fs@2.0.3>: please upgrade to graceful-fs 4 for compatibility with current and future versions of Node.js
warning rpmbuild > glob-stream > minimatch@2.0.10<mailto:minimatch@2.0.10>: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
warning rpmbuild > glob-stream > glob > minimatch@2.0.10<mailto:minimatch@2.0.10>: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
warning rpmbuild > fs.extra > walk > forEachAsync@2.2.1<mailto:forEachAsync@2.2.1>: Please use 'foreachasync' instead. See https://www.npmjs.com/package/foreachasync
[2/4] Fetching packages...
warning forEachAsync@2.2.1<mailto:forEachAsync@2.2.1>: The engine "ender" appears to be invalid.
warning sequence@2.2.1<mailto:sequence@2.2.1>: The engine "ender" appears to be invalid.
[3/4] Linking dependencies...
[4/4] Building fresh packages...
warning "rpmbuild@0.0.22"<mailto:rpmbuild@0.0.22> has no binaries

So i run it directly from dist/linux-unpacked

AN IT WORKS !

No loop even if i don't precise proxy option.

Just have this error

(teams-for-linux:14509): libappindicator-WARNING **: 14:42:51.375: Unable to get the session bus: Transport « disabled » inconnu ou non pris en charge pour l’adresse « disabled: »

(teams-for-linux:14509): LIBDBUSMENU-GLIB-WARNING **: 14:42:51.375: Unable to get session bus: Transport « disabled » inconnu ou non pris en charge pour l’adresse « disabled: »

(teams-for-linux:14509): libnotify-WARNING **: 14:44:48.677: Failed to connect to proxy

(teams-for-linux:14509): libnotify-WARNING **: 14:44:48.677: Failed to connect to proxy

(teams-for-linux:14509): libnotify-WARNING **: 14:44:48.677: Failed to connect to proxy

(teams-for-linux:14509): libnotify-WARNING **: 14:45:13.047: Failed to connect to proxy

(teams-for-linux:14509): libnotify-WARNING **: 14:45:13.047: Failed to connect to proxy

(teams-for-linux:14509): libnotify-WARNING **: 14:45:13.047: Failed to connect to proxy

(teams-for-linux:14509): libnotify-WARNING **: 14:45:16.409: Failed to connect to proxy

(teams-for-linux:14509): libnotify-WARNING **: 14:45:16.409: Failed to connect to proxy

But everything work fine !


I will try to package it on rpm to install it properly, if can't, i will wait for your next release !

Best regards

Cyrille ROCHUT
Service Support Métier
GFIT

Prélodis 3 - 27 rue marcel Mérieux - 69960 Corbas

T : 04 37 23 60 96

[cid:part1.C162C96A.E13B8644@gfit.fr]
Retrouvez nous sur wwww.grandfrais.com<http://wwww.grandfrais.com>
Le 05/07/2019 à 14:38, IsmaelMartinez a écrit :

Electron builder requires node V8 (recommended 10).

Can you try getting the snap package from edge channel??

**Comment by IsmaelMartinez** [comment] 2019-07-05 15:12
just remove all the targets (minus deb) in the package.json

https://github.com/IsmaelMartinez/teams-for-linux/blob/develop/package.json#L63

**Comment by crochut** [comment] 2019-07-05 15:24
but in centos the package format is rpm

:p


Cyrille ROCHUT
Service Support Métier
GFIT

Prélodis 3 - 27 rue marcel Mérieux - 69960 Corbas

T : 04 37 23 60 96

[cid:part1.F5958F8A.809E18FA@gfit.fr]
Retrouvez nous sur wwww.grandfrais.com<http://wwww.grandfrais.com>
Le 05/07/2019 à 17:12, IsmaelMartinez a écrit :

just remove all the targets (minus deb) in the package.json

https://github.com/IsmaelMartinez/teams-for-linux/blob/develop/package.json#L63

**Comment by IsmaelMartinez** [comment] 2019-07-05 16:42
the opposite then!!

**Comment by crochut** [comment] 2019-07-08 07:23
Yes but rpm is package who cannot be generated due to module version.

;)

Cyrille ROCHUT
Service Support Métier
GFIT

Prélodis 3 - 27 rue marcel Mérieux - 69960 Corbas

T : 04 37 23 60 96

[cid:part1.1C8C7067.F85D84D1@gfit.fr]
Retrouvez nous sur wwww.grandfrais.com<http://wwww.grandfrais.com>
Le 05/07/2019 à 18:42, IsmaelMartinez a écrit :
the opposite then!!

**Comment by IsmaelMartinez** [comment] 2019-07-08 08:00
I guess then that the best option is for me to do a release and see how it goes. I will see how I got it this week, hopefully I can make it happen. Alternatively drop me an email (my email is in my profile) and I can send you the rpm.

**Comment by IsmaelMartinez** [comment] 2019-07-11 21:47
Hi, can you confirm if it did work? Preparing to release that 0.4.0 so, as no news is normally good news, I will close this as fixed. Let me know otherwise. Thanks!

**Closed by IsmaelMartinez** 2019-07-11 21:47 UTC
Labels: bug, help wanted, question

**Comment by crochut** [comment] 2019-07-12 07:40
Hi, yes i confim it works,

i use the compiled version from master all this week, and everything work fine.


Cyrille ROCHUT
Service Support Métier
GFIT

Prélodis 3 - 27 rue marcel Mérieux - 69960 Corbas

T : 04 37 23 60 96

[cid:part1.5F35EEED.F3705081@gfit.fr]
Retrouvez nous sur wwww.grandfrais.com<http://wwww.grandfrais.com>
Le 11/07/2019 à 23:47, IsmaelMartinez a écrit :

Hi, can you confirm if it did work? Preparing to release that 0.4.0 so, as no news is normally good news, I will close this as fixed. Let me know otherwise. Thanks!
