### ISSUE TITLE
App is crashing when trying to share screen/window.

### ISSUE THREAD

**Issue by gwozniak** [IsmaelMartinez/teams-for-linux#1490] opened 2024-11-22 07:22 UTC
Hi, I installed pre-release  1.12 and app started to crash (not always) when trying to select screen/windows to share.
Probably it was occurring  when I was already sharing smth in the session, then somebody took the screen and I wanted take it back. Not sure 100% that's the only case but this I remembered and it was always during meeting in the work so no time to debug :(
I'm using debian 12 with X11.
Please give me some advices how to start teams (flags to enable logs,change levels), which logs/files deliver etc. to help you investigate problem - unfortunately I got very busy time now and have no time to RTFM :)

Thanks in advance gw.

**Comment by Moonnz** [comment] 2024-11-22 10:02
I can confirm, on ubuntu with the latest version, the program crash half the time when i try to share my screen

**Comment by IsmaelMartinez** [comment] 2024-11-22 13:53
@gwozniak, the bug template includes all the info. If you can edit your message and provide this content we can have a look:

```
**Describe the bug**
A clear and concise description of what the bug is.

**To Reproduce**
Steps to reproduce the behavior:
1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See error

**Expected behavior**
A clear and concise description of what you expected to happen.

**Screenshots**
If applicable, add screenshots to help explain your problem.

**Desktop (please complete the following information):**
 - OS: [e.g. iOS]
 - Installation package [deb, rpm, snap, AppImage, tar.gz, source...]
 - Version [e.g. 0.1.17]

**Debug**
When possible, please run the application from the terminal using `--webDebug` and try to reproduce the error.

The provide in this section the output from both the terminal and the browser debug console.

```bash
teams-for-linux --webDebug --logConfig='{}'
```

*IMPORTANT:* Ensure that you mask any sensitive information before posting the output.

**Additional context**
Add any other context about the problem here.

```

@Moonnz you are also using the pre-release?

**Comment by Moonnz** [comment] 2024-11-27 08:40
Yes, i'm using the pre-release too.


My log with webDebug when the crash happen :

```
[433796:1127/093614.107029:ERROR:CONSOLE(1)] "Request Autofill.enable failed. {"code":-32601,"message":"'Autofill.enable' wasn't found"}", source: devtools://devtools/bundled/core/protocol_client/protocol_client.js (1)
[433796:1127/093614.107087:ERROR:CONSOLE(1)] "Request Autofill.setAddresses failed. {"code":-32601,"message":"'Autofill.setAddresses' wasn't found"}", source: devtools://devtools/bundled/core/protocol_client/protocol_client.js (1)
09:36:14.107 › did-frame-finish-load {} false
[433942:1127/093614.723379:ERROR:gles2_cmd_decoder_passthrough.cc(1053)] [GroupMarkerNotSet(crbug.com/242999)!:A0F02300DC290000]Automatic fallback to software WebGL has been deprecated. Please use the --enable-unsafe-swiftshader flag to opt in to lower security guarantees for trusted content.
09:36:15.551 › did-frame-finish-load {} false
09:36:15.572 › did-frame-finish-load {} false
[433796:1127/093615.735607:ERROR:CONSOLE(1)] "Request Autofill.enable failed. {"code":-32601,"message":"'Autofill.enable' wasn't found"}", source: devtools://devtools/bundled/core/protocol_client/protocol_client.js (1)
[433796:1127/093615.735671:ERROR:CONSOLE(1)] "Request Autofill.setAddresses failed. {"code":-32601,"message":"'Autofill.setAddresses' wasn't found"}", source: devtools://devtools/bundled/core/protocol_client/protocol_client.js (1)
[433796:1127/093615.746156:ERROR:CONSOLE(1)] "Request Autofill.enable failed. {"code":-32601,"message":"'Autofill.enable' wasn't found"}", source: devtools://devtools/bundled/core/protocol_client/protocol_client.js (1)
[433796:1127/093615.746215:ERROR:CONSOLE(1)] "Request Autofill.setAddresses failed. {"code":-32601,"message":"'Autofill.setAddresses' wasn't found"}", source: devtools://devtools/bundled/core/protocol_client/protocol_client.js (1)
09:36:17.336 › did-frame-finish-load {} false
09:36:17.393 › did-frame-finish-load {} false
09:36:18.628 › GetSystemIdleState => IdleTimeout: 300s, IdleTimeoutPollInterval: 10s, ActiveCheckPollInterval: 2s, IdleTime: 0s, IdleState: 'active'
09:36:22.313 › Badge count set to '0'
09:36:26.085 › Badge count set to '0'
09:36:28.629 › GetSystemIdleState => IdleTimeout: 300s, IdleTimeoutPollInterval: 10s, ActiveCheckPollInterval: 2s, IdleTime: 0s, IdleState: 'active'
09:36:29.755 › Badge count set to '0'
[433987:1127/093637.637862:ERROR:sdp_offer_answer.cc(424)] A BUNDLE group contains a codec collision for payload_type='101. All codecs must share the same type, encoding name, clock rate and parameters. (INVALID_PARAMETER)
09:36:38.632 › GetSystemIdleState => IdleTimeout: 300s, IdleTimeoutPollInterval: 10s, ActiveCheckPollInterval: 2s, IdleTime: 0s, IdleState: 'active'
09:36:48.711 › GetSystemIdleState => IdleTimeout: 300s, IdleTimeoutPollInterval: 10s, ActiveCheckPollInterval: 2s, IdleTime: 0s, IdleState: 'active'
[433942:1127/093650.986292:ERROR:shared_image_manager.cc(356)] SharedImageManager::ProduceMemory: Trying to Produce a Memory representation from a non-existent mailbox.
[433942:1127/093650.986791:ERROR:shared_image_manager.cc(356)] SharedImageManager::ProduceMemory: Trying to Produce a Memory representation from a non-existent mailbox.
[433942:1127/093650.986894:ERROR:shared_image_manager.cc(356)] SharedImageManager::ProduceMemory: Trying to Produce a Memory representation from a non-existent mailbox.
[433942:1127/093650.987344:ERROR:shared_image_manager.cc(356)] SharedImageManager::ProduceMemory: Trying to Produce a Memory representation from a non-existent mailbox.
[433942:1127/093650.987404:ERROR:shared_image_manager.cc(356)] SharedImageManager::ProduceMemory: Trying to Produce a Memory representation from a non-existent mailbox.
[433942:1127/093650.987433:ERROR:shared_image_manager.cc(356)] SharedImageManager::ProduceMemory: Trying to Produce a Memory representation from a non-existent mailbox.
[1]    433796 segmentation fault (core dumped)  teams-for-linux --webDebug --logConfig='{}'
[433855:0100/000000.148534:ERROR:zygote_linux.cc(639)] Zygote could not fork: process_type renderer numfds 4 child_pid -1
[433855:0100/000000.148632:ERROR:zygote_linux.cc(671)] write: Broken pipe (32)
```

And just in case :

```
9:39:56 ➜  ~ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 24.04.1 LTS
Release:	24.04
Codename:	noble
```

**Comment by IsmaelMartinez** [comment] 2024-11-28 09:35
Hi @Moonnz , that looks like a memory crash. There are a couple of things to try to see if it is only this pre-release changes or if there is anything else in play here:
* I assume this is using snap, can you try with another packaging option? we provide a few.
* Been Ubuntu 24, can you confirm if you got an apparmour profile? (more info in https://github.com/IsmaelMartinez/teams-for-linux/issues/1426#issuecomment-2453340003) 
* I see a couple of suggestions on the logs
** Pass the `enable-unsafe-swiftshader` flag (see the config options on the how) from this message: `[433942:1127/093614.723379:ERROR:gles2_cmd_decoder_passthrough.cc(1053)] [GroupMarkerNotSet(crbug.com/242999)!:A0F02300DC290000]Automatic fallback to software WebGL has been deprecated. Please use the --enable-unsafe-swiftshader flag to opt in to lower security guarantees for trusted content.`
** maybe try `--disableGpu`because of that same error.

I suspect this is an electron issue, so looking into their side might also be a good idea. Hope helps!

**Comment by IsmaelMartinez** [comment] 2024-11-30 09:59
On top of the previous comment, could you check with the latest [pre-release (1.12.3)](https://github.com/IsmaelMartinez/teams-for-linux/releases/tag/v1.12.3) as it has a bug fix that might sort this problem. Let me know how you get on.

**Comment by gwozniak** [comment] 2024-12-05 06:43
> On top of the previous comment, could you check with the latest [pre-release (1.12.3)](https://github.com/IsmaelMartinez/teams-for-linux/releases/tag/v1.12.3) as it has a bug fix that might sort this problem. Let me know how you get on.

@IsmaelMartinez  - on my side I installed 1.12.3 on Sunday and since then I was participating few meetings with sharing screen - no crash, seem resolved for me :) 
Lets  @Moonnz confirm and issue could be closed IMHO.

**Comment by IsmaelMartinez** [comment] 2024-12-09 16:26
I marked the 1.12.3 as a release, so closing this. We can always re-open if still not working. thanks for the update and glad it is working again for you.

**Closed by IsmaelMartinez** 2024-12-09 16:26 UTC
