### ISSUE TITLE
Screen Sharing No Longer Working

### ISSUE THREAD

**Issue by JoaoRXFernandes** [IsmaelMartinez/teams-for-linux#194] opened 2019-08-02 08:26 UTC
**Describe the bug**
Stopped working yesterday with "Desktop sharing isn't supported in your browser yet"

**Desktop (please complete the following information):**
 - OS: Xubuntu
 - Installation package deb
 - Version 0.4.0

**Comment by IsmaelMartinez** [comment] 2019-08-02 09:02
yeah, seems like MS have changed the underneath implementation of it so our "hack" doesn't work anymore. 

I got no time currently so it might take a wee while to get this supported.

**Comment by JoaoRXFernandes** [comment] 2019-08-02 09:22
If you point me in the right direction I can try and have a look?

**Comment by IsmaelMartinez** [comment] 2019-08-02 09:30
The best place to start is in https://github.com/IsmaelMartinez/teams-for-linux/issues/19 

All the code is under the "browser" folder.

**Comment by CarlosLanderas** [comment] 2019-08-02 10:29
It's happening to me as well! :_(

**Comment by paulgrove** [comment] 2019-08-02 11:53
Just adding a not very useful "me too"

**Comment by lumeche** [comment] 2019-08-02 13:34
I'm in the same ship. The desktop sharing is no not working for me neither

**Comment by IsmaelMartinez** [comment] 2019-08-02 19:06
ok, can someone test branch fix-194-screensharing-not-working ? is another hack (telling that we are the desktop client) but it works on my case... so it might work again on yours. You will need to build from source and I don't have the time this weekend for more than this hack. Maybe on Monday I can have a deeper look/test, and/or if it works, release it.

**Comment by IsmaelMartinez** [comment] 2019-08-02 19:08
you will need to clean your ~/.config/Electron space as there is a userAgent change... if you have ever build this from source. Thanks in advance!

**Comment by v-ymarchanka** [comment] 2019-08-02 19:33
I can confirm that issue fixed in branch `fix-194-screensharing-not-working`
Thank you so much!

**Comment by IsmaelMartinez** [comment] 2019-08-02 21:25
thanks for testing. can people test that mentions and 1-on-1 meetings still work? (including desktop share). Those are the things that in the past have suffer from changes in that area. I will open now the PR and if I see people not reporting issue from that branch I might even merge it into develop (so available in snap/edge channel). I will be surprised if I manage to fix it in just a few hours without breaking something else.

**Comment by IsmaelMartinez** [comment] 2019-08-03 21:39
I had another quick check and reverted the comments (but still "telling" we are a desktop).

That works for me so I will be merging to snap edge soon. I really need you people to confirm this works in edge before I release it. Thanks in advance!

**Comment by JoaoRXFernandes** [comment] 2019-08-04 08:46
Hi @IsmaelMartinez 

Sorry about the delay, I'm very happy to report that branch is working for me as well!

Please do merge it in; would be grand if you could roll out a deb package as well when you have a chance.

Thanks so much for this project, great example of how open source can work wonders!

Now if only MS would learn to not only take but also give a little back (as in starting with supporting their systems on the platform that they keep on taking from...)...

Thanks again,

Joao

**Comment by IsmaelMartinez** [comment] 2019-08-04 10:08
It's in snap edge. I will try to prepare the release Monday. Please report either way if snap edge is working or not. Did a few tests yesterday night and couldn't find any issues.

**Comment by IsmaelMartinez** [comment] 2019-08-05 09:15
it should be released soon as 0.5.0. Check later today for a deb package. Thanks for testing.

**Closed by IsmaelMartinez** 2019-08-05 09:15 UTC
Labels: bug, help wanted

**Comment by yalla** [comment] 2019-08-05 09:51
Works for me! :+1:
