### ISSUE TITLE
away after a couple minutes

### ISSUE THREAD

**Issue by sdirkwinkel** [IsmaelMartinez/teams-for-linux#577] opened 2022-09-12 08:46 UTC
Teams shows away status after a couple minutes when using the computer, but not teams.
This might only be happening on wayland and also happens in chromium.

In chromium I'm using a userscript as a workaround:
```
setInterval(() => {unsafeWindow.angular.element(document.body).injector().get('presenceService').setMyStatus(1, null, true); }, 15000)
```

**Comment by jijojosephk** [comment] 2022-09-12 09:20
I guess the same script can be implemented here as well. Thanks.

**Comment by jijojosephk** [comment] 2022-09-12 09:20
But, could you clarify this `when using the computer, but not teams`

**Comment by sdirkwinkel** [comment] 2022-09-12 09:30
> But, could you clarify this `when using the computer, but not teams`

Using other windows, moving mouse etc, but not having teams in focus

> I guess the same script can be implemented here as well. Thanks.

Hm, the script forces online state all the time. Maybe something else can be done or this could be an option like --force-online

**Comment by mstroecker** [comment] 2022-09-29 13:34
> Using other windows, moving mouse etc, but not having teams in focus

Maybe `powerMonitor.getSystemIdleTime()` could be helpful. 
https://www.electronjs.org/docs/latest/api/power-monitor#powermonitorgetsystemidletime

**Comment by Andrioshe** [comment] 2022-10-14 17:27
@sdirkwinkel How does your Script exactly work? I can't find any information about presenceService.

**Comment by jijojosephk** [comment] 2022-10-15 02:52
> @sdirkwinkel How does your Script exactly work? I can't find any information about presenceService.

I haven't checked that but it must be there. Or try this one `injector().get('appStateService').setActive()`

**Comment by sdirkwinkel** [comment] 2022-11-11 10:26
> @sdirkwinkel How does your Script exactly work? I can't find any information about presenceService.

Sorry for not seeing this earlier. Doing `angular.element(document.body).injector().get('presenceService').setMyStatus(1, null, true);
` calls the teams function to set your online state. The rest is just about how to do it on a timer in the userscript.

There aren't really any docs on that since the presenceService is part of ms teams code.

**Comment by IsmaelMartinez** [comment] 2022-11-11 15:44
you can probably modify the app to allow that sort of script to run on a timer.

Similar to this but might require a bit more logic (magic) 

https://github.com/IsmaelMartinez/teams-for-linux/blob/develop/app/mainAppWindow/index.js#L95

**Comment by rodricels** [comment] 2023-01-13 13:07
I've tried to add the powerMonitor control but my electron-fu is near to zero, but at least there are the possible Presence Status values. 

0 = "offline",
**1 = "online",**
**2 = "busy",**
**3 = "away",**
4 = "idle",
5 = "on-the-phone",
**6 = "do-not-disturb",**
**7 = "be-right-back",**
8 = "hidden",
9 = "disabled",
10 = "unknown",
11 = "appear-away",
12 = "reset",
13 = "out-of-office",
14 = "presenting",
15 = "busy",
16 = "on-shift",
17 = "off-shift",
18 = "focusing",
19 = "blocked",
**20 = "appear-offline",**

According to https://learn.microsoft.com/en-us/microsoftteams/presence-admins you can only use the subset: Available (online), Busy, Do not disturb, Away, Be right back, Appear offline.

**Comment by lectrode** [comment] 2023-03-09 21:56
just a quick fyi: lack  of this functionality is currently prohibitive, as teams will not emit notifications when your status is "away". this means that notifications are not shown until you manually check this client, which makes them completely useless.

another workaround i've found is that other clients can override your status, so if you have another client open that doesn't have this issue that sets your status as "online", the `teams-for-linux` client will show the notifications as expected.

**Comment by 31337-4554551n** [comment] 2023-04-11 05:13
I am also showing an interest in this issue-I fought  hard to be allowed to use linux as a work computer, and now constantly showing as away on teams is not a good look :(

**Comment by lectrode** [comment] 2023-04-11 06:48
@31337-4554551n if you need an immediate workaround for that issue, the (now unmaintained) official client can still be downloaded from the [web archive](https://web.archive.org/web/20221130115842if_/https://packages.microsoft.com/repos/ms-teams/pool/main/t/teams/teams_1.5.00.23861_amd64.deb). It works decently, albeit not quite as snappy as `teams-for-linux`, and it still uses an older interface (and, for me at least, shows an annoying "Custom Setup" notification on top of any meetings I join, but that's a minor hindrance at worst). At the very least, it does not have this status issue and correctly keeps your status as "Online" as long as you are using your computer.


Arch Linux (or derivative distro) users can still use the [teams AUR package](https://aur.archlinux.org/packages/teams) based on the above deb installer.

Personally, I'm using this running in conjunction with the new client to workaround the status issue while still being able to use the newer client. As much as I hate running 2 separate instances of teams, it beats missing notifications (running only `teams-for-linux`) or having the meeting screen obstructed (only running the abandoned one).

**Comment by lectrode** [comment] 2023-04-12 19:05
As this is (for me at least) the only issue with this client that prevents me from solely relying on it, I've opened the following bounty on it to hopefully provide some incentive for prioritizing this:
https://app.bountysource.com/issues/119136878-away-after-a-couple-minutes

Required for payout:
* Status should stay "Online" as long as the system is being interacted with
* If the timeout is manually implemented in the client, it should have an option to be disabled (rely on PWA's default behavior)
* User should still have the ability to override the status by setting it manually (i.e. "Away", "Busy", "Offline", etc)

Optional:
If the timeout has to be manually implemented in the client, I would love to see the timeout value exposed as a configurable option (show away after X minutes). Not strictly necessary for the resolution of this bug, but I'll chip in extra if that is implemented with this.

**Comment by jijojosephk** [comment] 2023-04-13 02:34
@lectrode the only difficulty is to find whether the status 'away' or any other set by user manually. I'm yet to figure out. But this issue will be handled very soon.

**Comment by 31337-4554551n** [comment] 2023-04-13 03:51
> @lectrode the only difficulty is to find whether the status 'away' or any other set by user manually. I'm yet to figure out. But this issue will be handled very soon.

This shouldn't matter to get the users the core fix of "don't auto set away status", should it?

Something in the client which would mimic a 1 pixel mouse move or some form of event would prevent it from setting auto away without interfering with any custom set statuses. If the screen is locked-it would set away as normal.

**Comment by jijojosephk** [comment] 2023-04-13 05:05
All we need to know the changed status.

1. 'Away' is 3
2. If 3 check if it's triggered from user action 'Interactive' or 'Inactive'.
3. If not from user check if system idle crossed the preferred threshold set by the user
4. If not crossed, prevent from being set to 3 other wise allow.

**Comment by lectrode** [comment] 2023-04-13 05:10
Sounds reasonable. I'll keep the bounty open in part so I learn how to handle those going forward (I've never created one before, only contributed to others, and want to know how it handles payouts), and in part as a "thank you" for this effort.

**Comment by jijojosephk** [comment] 2023-04-13 14:16
@lectrode @31337-4554551n  @rodricels @ocelik94 @mstroecker @sdirkwinkel can you test `1.5.60` once published? If someone is using flatpak I can publish a test build in flathub as well.

**Comment by ocelik94** [comment] 2023-04-13 14:17
Flatpak would be great

**Comment by jijojosephk** [comment] 2023-04-13 14:35
Run it this way
`flatpak run --log-session-bus com.github.IsmaelMartinez.teams_for_linux`

We can catch any dbus errors as it tries to get the system idle time.

**Comment by jijojosephk** [comment] 2023-04-13 16:05
Weird, not it never tries to change the status. :laughing:

**Comment by lectrode** [comment] 2023-04-14 03:17
@jijojosephk thank you. i've been testing the official client, 1.0.58, and 1.0.60 all day to see what's changed behavior-wise.

Test details:
I made a 2nd teams account to see what my status looks like from the outside, and also better test various ways of trying to contact my main account through this client (send message, call, schedule meeting, start meeting, etc). When switching between Teams for Linux (TfL) versions, the config would be wiped to ensure an accurate test.

Minutes stated below describe the duration of time that the client is minimized **while the system is in use**. Actual idle time not yet tested.

| Feature | Official 1.5.00.23861 | TfL 1.0.58 | TfL 1.0.60 |
| ---- | ---- | ---- | ---- |
| Status shown to **self** | Online as long as interacting with system | Away after 5min | Always Online |
| Status shown to **others** | Online as long as interacting with system | Away after 5min | Away after 20min |
| Notify on new message | As long as Online |  Up to 30 min | Up to 30 min |

One other thing I noticed when testing 1.0.58 and 1.0.60 were that "<Name of Person> started the meeting" notifications do not appear at all. They only appear in the official client. That has nothing to do with this status issue, however.

**Comment by jijojosephk** [comment] 2023-04-14 03:39
@lectrode thanks for the detailed test. To study the behaviour further, let's not set the status from code, also instead of logging in developer tools, we can log to terminal. When we try to see the logs from developer tools, application gets focus and our test scenarios may fail. Let's see.

**Comment by liedekef** [comment] 2023-04-14 10:17
Is this actually fixed in 1.0.60 ?  My status is "away" all the time now ... even when setting "available" and then "reset status", it switches back to "away"

**Comment by jijojosephk** [comment] 2023-04-14 11:42
> Is this actually fixed in 1.0.60 ? My status is "away" all the time now ... even when setting "available" and then "reset status", it switches back to "away"

Though it cannot be called a fix yet, it will not block setting any status by manual intervention. In a few minutes I'll release another build on `1.0.60`. Can you try when it happens?

**Comment by liedekef** [comment] 2023-04-14 11:45
When setting manual status, it works ok. But then chosing "reset status" reverts back to away (while I'm obiously in the interface clicking on it). Even now: status is marked away, moving my mouse around in the window or clicking on teams, chat, calendar: status stays "away" ...

**Comment by jijojosephk** [comment] 2023-04-14 12:04
@liedekef can you check the latest build (pre-release)? version number is same. https://github.com/IsmaelMartinez/teams-for-linux/releases/tag/v1.0.60

**Comment by liedekef** [comment] 2023-04-14 12:07
Uodated (using "rpm --reinstall XXX.rpm"). Currently status is "green" (available), let's see what happens :-)

**Comment by jijojosephk** [comment] 2023-04-14 12:14
> Uodated (using "rpm --reinstall XXX.rpm"). Currently status is "green" (available), let's see what happens :-)

Fingers crossed. Very difficult to reverse engineer MBs of JavaScript written by MS team. Let's see.

**Comment by jijojosephk** [comment] 2023-04-14 12:27
We may have a success. I'm using a flatpak test build and seems good so far. @lectrode  can you try the latest one? if flatpak this one (test):
`flatpak install --user https://dl.flathub.org/build-repo/17573/com.github.IsmaelMartinez.teams_for_linux.flatpakref` otherwise please take the latest build on `1.0.60` from releases (pre-release)

**Comment by liedekef** [comment] 2023-04-14 12:50
so far all ok here.

**Comment by jijojosephk** [comment] 2023-04-14 13:22
Seems to be working. I'll wait for others to confirm. Btw, there are 2 new flags.
`--appIdleTimeout` number of seconds to wait before app considers system/user inactive when no user interactions with system. Default is 300 (5 minutes). This has no connection with system screen lock timeout because electron does not know whether user locked/unlocked the system in Linux. It's supported in Win & Darwin only.

`--appIdleTimeoutCheckInterval` interval in number of seconds between checks to see `--appIdleTimeout` has reached or not. Default is 10. 

The flags above to overcome the limitations of Electron API in Linux system.

**Comment by 31337-4554551n** [comment] 2023-04-14 13:50
So it should now check to see if the system as a whole is being interacted with, not just the app itself, correct?

**Comment by jijojosephk** [comment] 2023-04-14 13:59
> So it should now check to see if the system as a whole is being interacted with, not just the app itself, correct?

Yes.

**Comment by jijojosephk** [comment] 2023-04-15 01:27
I mark this as closed. Please re-open if you think the issue is not resolved.

**Comment by lectrode** [comment] 2023-04-15 03:11
@jijojosephk this is much closer to being resolved, as the client will honor local activity to prevent going into away status.

however, there is one last issue with this: if the user idles long enough for the client to switch to the "Away" status, it will not wake up (switch back to Online) until the user specifically interacts with the client again. At this point, we run into the same issue where after 30 minutes of the client status being "Away", you stop receiving notifications.

IMHO this should be re-opened until this last issue is resolved. The client needs to be able to resume Online status without the user having to specifically interact with it.

**Comment by 31337-4554551n** [comment] 2023-04-15 03:17
I agree with the above, and would also add that notifications should continue regardless of status.

**Comment by jijojosephk** [comment] 2023-04-15 03:32
Can you run the app from the terminal using `--appLogLevels debug`. You would see something like this.
`[DEBUG] GetSystemIdleState => IdleTimeout: 300s, IdleTimeoutPollInterval: 10s, IdleTime: 0s, IdleState: 'active'`

See what's the IdleTime and IdleState when the above mentioned scenario occurs.

Also see if setting `--appIdleTimeout` to a higher value than default `300` (5 minutes) can be used as a work around. Ex: 10 minutes should have 10 x 60 `600`.

**Comment by lectrode** [comment] 2023-04-15 04:37
```
$ /opt/teams-for-linux/teams-for-linux --appLogLevels debug
[DEBUG] configPath:,/home/lectrode/.config/teams-for-linux
[DEBUG] configFile:,[object Object]
xdg-settings: default-url-scheme-handler not implemented for xfce
[DEBUG] processArgs:,/opt/teams-for-linux/teams-for-linux,--appLogLevels,debug
[DEBUG] did-finish-load
[DEBUG] did-finish-load
[DEBUG] did-finish-load
[DEBUG] Playing file: /opt/teams-for-linux/resources/assets/sounds/new_message.wav
[DEBUG] Playing file: /opt/teams-for-linux/resources/assets/sounds/new_message.wav
```

Both of those incoming messages were received before the client entered "Away" status. I did not get any output when the client went Away, nor did I get any other output after resuming interacting with my computer (about 30 minutes later). Not even any output when finally interacting with TfL again to wake it up and have it switch back to Online.


Increasing the timeout works in-so-much that it prevents the away status for as long as I set it for (tested and verified up to 30 min). Using a long timeout makes that issue easier to avoid, but anyone using this client without following the issues might not be aware that such an issue exists until they start missing notifications.

**Comment by jijojosephk** [comment] 2023-04-15 04:47
I wonder why there is no entry like this
[DEBUG] GetSystemIdleState => IdleTimeout: 300s, IdleTimeoutPollInterval: 10s, IdleTime: 0s, IdleState: 'active'

**Comment by jijojosephk** [comment] 2023-04-15 05:07
@lectrode  though I can't reproduce the scenario you're talking about, I found a logical issue in which the app was always showing active even after the state becomes 'idle'. I'm just fixing that in `1.0.62`.

1. After 300 seconds (5 minutes) or whatever value passed, app stops controlling the state.
2. As long as it is active you'd see `[DEBUG] GetSystemIdleState => IdleTimeout: 300s, IdleTimeoutPollInterval: 10s, IdleTime: 0s, IdleState: 'active'` in terminal.
3. When app thinks it is idle then you would see something like this `[DEBUG] GetSystemIdleState => IdleTimeout: 300s, IdleTimeoutPollInterval: 10s, IdleTime: 651s, IdleState: 'idle'`
4. It may take again a couple minutes before teams shows 'away'.
5. When the system is active again by keyboard/mouse events, you would not see the status 'active' immediately.
6. The reason is that the check is based on IdleTimeoutPollInterval which is 10 by default. That also can be changed.
7. So that means it may take up to 10 seconds for the app to understand that system is active again. So may something like this:
`[DEBUG] GetSystemIdleState => IdleTimeout: 300s, IdleTimeoutPollInterval: 10s, IdleTime: 651s, IdleState: 'idle'`
`[DEBUG] GetSystemIdleState => IdleTimeout: 300s, IdleTimeoutPollInterval: 10s, IdleTime: 0s, IdleState: 'active'`

Soon after you'd see the icon turns green from yellow.

**Comment by lectrode** [comment] 2023-04-15 05:51
I was previously using the re-release of 1.0.60. Currently re-testing with [latest commit](https://github.com/IsmaelMartinez/teams-for-linux/commit/69a6c5e3e25fb45cc5e6a61292cbf7c849ef630f) as of writing. I can see the debug messages you mentioned.

**Comment by jijojosephk** [comment] 2023-04-15 06:02
Thanks, I'm already on another parameter implementation which can be used to aggressively check is the app active more frequently when it becomes idle.

**Comment by lectrode** [comment] 2023-04-15 07:57
Alright, so upon further testing with that commit, I can no longer produce that issue.

I will say that After a half hour of being away (without interacting with the system), notifications will no longer appear (or sound) for chat messages until you interact with the system (direct interaction with the client is not necessary). This matches the behavior of the original client.

It would be nice if the notification came through regardless of the user being away for half an hour or more, but I do not know how feasible that would be to implement.

As this currently matches the behavior of the original client, I would consider this issue pretty much addressed. If needed, a separate request/issue can be made for enhanced functionality.

**Comment by jijojosephk** [comment] 2023-04-18 05:54
Thanks @lectrode, I would close for now. Please re-open if you face issues.

**Comment by Crescent-Saturn** [comment] 2024-04-30 18:14
Hi, sorry to reopen this again. 

I found that when using multiple monitors, this issue appears again, like:
teams-for-linux on monitor 1, working on monitor 2, then after several minutes, I say my status becomes "away"... but when I move the cursor back to that monitor, it changes back to "online" right way

OS and app versions:
> - Ubuntu 22.04.4 LTS
> - teams-for-linux/stable,now 1.4.31 amd64 [installed]

This is strange because I remember it was like this at the beginning when I installed teams-for-linux about one month ago, it acted like above. 
Then one or two weeks ago when it was updated, its behavior was correct, 
however, after upgrading to the latest version, it came back.

Thank you for your time!

PS: I just look back to that monitor, it becomes "away" now, I may need to move the cursor. See you soon 🥲

**Comment by Crescent-Saturn** [comment] 2024-05-02 14:37
> Hi, sorry to reopen this again.
> 
> I found that when using multiple monitors, this issue appears again, like: teams-for-linux on monitor 1, working on monitor 2, then after several minutes, I say my status becomes "away"... but when I move the cursor back to that monitor, it changes back to "online" right way
> 
> OS and app versions:
> 
> > * Ubuntu 22.04.4 LTS
> > * teams-for-linux/stable,now 1.4.31 amd64 [installed]
![image](https://github.com/IsmaelMartinez/teams-for-linux/assets/18294546/4bf56e2b-ad42-4a6c-80a4-e1c1699b555e)

> 
> This is strange because I remember it was like this at the beginning when I installed teams-for-linux about one month ago, it acted like above. Then one or two weeks ago when it was updated, its behavior was correct, however, after upgrading to the latest version, it came back.
> 
> Thank you for your time!
> 
> PS: I just look back to that monitor, it becomes "away" now, I may need to move the cursor. See you soon 🥲

Hi, I run the Debug to find out this on every several seconds -> `Failed to set Machine State`: 

![image](https://github.com/IsmaelMartinez/teams-for-linux/assets/18294546/c1d00a9f-1907-4f03-9861-3bc9a982c273)

I hope this could help to locate the "away" issue, thank you!

**Comment by mdallaire** [comment] 2024-05-02 17:19
I am seeing the same issue here since this morning (running version v1.4.34)

```
error @ v2/:3
(anonymous) @ /opt/teams-for-linux/resources/app.asar/app/browser/tools/activityHub.js:82
Promise.catch (async)
setMachineState @ /opt/teams-for-linux/resources/app.asar/app/browser/tools/activityHub.js:81
(anonymous) @ /opt/teams-for-linux/resources/app.asar/app/browser/notifications/activityManager.js:26
Promise.then (async)
watchSystemIdleState @ /opt/teams-for-linux/resources/app.asar/app/browser/notifications/activityManager.js:25
(anonymous) @ /opt/teams-for-linux/resources/app.asar/app/browser/notifications/activityManager.js:37
setTimeout (async)
t.originalFunctionApplier @ js-wrapper.js:2
setTimeout @ js-wrapper.js:2
setTimeout @ js-wrapper.js:2
(anonymous) @ /opt/teams-for-linux/resources/app.asar/app/browser/notifications/activityManager.js:37
Promise.then (async)
watchSystemIdleState @ /opt/teams-for-linux/resources/app.asar/app/browser/notifications/activityManager.js:25
(anonymous) @ /opt/teams-for-linux/resources/app.asar/app/browser/notifications/activityManager.js:37
setTimeout (async)
t.originalFunctionApplier @ js-wrapper.js:2
setTimeout @ js-wrapper.js:2
setTimeout @ js-wrapper.js:2
(anonymous) @ /opt/teams-for-linux/resources/app.asar/app/browser/notifications/activityManager.js:37
Promise.then (async)
watchSystemIdleState @ /opt/teams-for-linux/resources/app.asar/app/browser/notifications/activityManager.js:25
(anonymous) @ /opt/teams-for-linux/resources/app.asar/app/browser/notifications/activityManager.js:37
setTimeout (async)
t.originalFunctionApplier @ js-wrapper.js:2
setTimeout @ js-wrapper.js:2
setTimeout @ js-wrapper.js:2
(anonymous) @ /opt/teams-for-linux/resources/app.asar/app/browser/notifications/activityManager.js:37
Promise.then (async)
watchSystemIdleState @ /opt/teams-for-linux/resources/app.asar/app/browser/notifications/activityManager.js:25
(anonymous) @ /opt/teams-for-linux/resources/app.asar/app/browser/notifications/activityManager.js:37
setTimeout (async)
t.originalFunctionApplier @ js-wrapper.js:2
setTimeout @ js-wrapper.js:2
setTimeout @ js-wrapper.js:2
(anonymous) @ /opt/teams-for-linux/resources/app.asar/app/browser/notifications/activityManager.js:37
Promise.then (async)
watchSystemIdleState @ /opt/teams-for-linux/resources/app.asar/app/browser/notifications/activityManager.js:25
(anonymous) @ /opt/teams-for-linux/resources/app.asar/app/browser/notifications/activityManager.js:37
setTimeout (async)
t.originalFunctionApplier @ js-wrapper.js:2
setTimeout @ js-wrapper.js:2
setTimeout @ js-wrapper.js:2
(anonymous) @ /opt/teams-for-linux/resources/app.asar/app/browser/notifications/activityManager.js:37
Promise.then (async)
watchSystemIdleState @ /opt/teams-for-linux/resources/app.asar/app/browser/notifications/activityManager.js:25
(anonymous) @ /opt/teams-for-linux/resources/app.asar/app/browser/notifications/activityManager.js:37
setTimeout (async)
t.originalFunctionApplier @ js-wrapper.js:2
setTimeout @ js-wrapper.js:2
setTimeout @ js-wrapper.js:2
(anonymous) @ /opt/teams-for-linux/resources/app.asar/app/browser/notifications/activityManager.js:37
Promise.then (async)
watchSystemIdleState @ /opt/teams-for-linux/resources/app.asar/app/browser/notifications/activityManager.js:25
(anonymous) @ /opt/teams-for-linux/resources/app.asar/app/browser/notifications/activityManager.js:37
setTimeout (async)
t.originalFunctionApplier @ js-wrapper.js:2
setTimeout @ js-wrapper.js:2
setTimeout @ js-wrapper.js:2
(anonymous) @ /opt/teams-for-linux/resources/app.asar/app/browser/notifications/activityManager.js:37
Promise.then (async)
watchSystemIdleState @ /opt/teams-for-linux/resources/app.asar/app/browser/notifications/activityManager.js:25
(anonymous) @ /opt/teams-for-linux/resources/app.asar/app/browser/notifications/activityManager.js:37
setTimeout (async)
t.originalFunctionApplier @ js-wrapper.js:2
setTimeout @ js-wrapper.js:2
setTimeout @ js-wrapper.js:2
(anonymous) @ /opt/teams-for-linux/resources/app.asar/app/browser/notifications/activityManager.js:37
Promise.then (async)
watchSystemIdleState @ /opt/teams-for-linux/resources/app.asar/app/browser/notifications/activityManager.js:25
(anonymous) @ /opt/teams-for-linux/resources/app.asar/app/browser/notifications/activityManager.js:37
setTimeout (async)
t.originalFunctionApplier @ js-wrapper.js:2
setTimeout @ js-wrapper.js:2
setTimeout @ js-wrapper.js:2
(anonymous) @ /opt/teams-for-linux/resources/app.asar/app/browser/notifications/activityManager.js:37
Promise.then (async)
watchSystemIdleState @ /opt/teams-for-linux/resources/app.asar/app/browser/notifications/activityManager.js:25
(anonymous) @ /opt/teams-for-linux/resources/app.asar/app/browser/notifications/activityManager.js:37
setTimeout (async)
t.originalFunctionApplier @ js-wrapper.js:2
setTimeout @ js-wrapper.js:2
setTimeout @ js-wrapper.js:2
(anonymous) @ /opt/teams-for-linux/resources/app.asar/app/browser/notifications/activityManager.js:37
Promise.then (async)
watchSystemIdleState @ /opt/teams-for-linux/resources/app.asar/app/browser/notifications/activityManager.js:25
(anonymous) @ /opt/teams-for-linux/resources/app.asar/app/browser/notifications/activityManager.js:37
setTimeout (async)
t.originalFunctionApplier @ js-wrapper.js:2
setTimeout @ js-wrapper.js:2
setTimeout @ js-wrapper.js:2
(anonymous) @ /opt/teams-for-linux/resources/app.asar/app/browser/notifications/activityManager.js:37
Promise.then (async)
watchSystemIdleState @ /opt/teams-for-linux/resources/app.asar/app/browser/notifications/activityManager.js:25
(anonymous) @ /opt/teams-for-linux/resources/app.asar/app/browser/notifications/activityManager.js:37
setTimeout (async)
t.originalFunctionApplier @ js-wrapper.js:2
setTimeout @ js-wrapper.js:2
setTimeout @ js-wrapper.js:2
(anonymous) @ /opt/teams-for-linux/resources/app.asar/app/browser/notifications/activityManager.js:37
Promise.then (async)
watchSystemIdleState @ /opt/teams-for-linux/resources/app.asar/app/browser/notifications/activityManager.js:25
(anonymous) @ /opt/teams-for-linux/resources/app.asar/app/browser/notifications/activityManager.js:37
setTimeout (async)
t.originalFunctionApplier @ js-wrapper.js:2
setTimeout @ js-wrapper.js:2
setTimeout @ js-wrapper.js:2
(anonymous) @ /opt/teams-for-linux/resources/app.asar/app/browser/notifications/activityManager.js:37
Promise.then (async)
watchSystemIdleState @ /opt/teams-for-linux/resources/app.asar/app/browser/notifications/activityManager.js:25
(anonymous) @ /opt/teams-for-linux/resources/app.asar/app/browser/notifications/activityManager.js:37
setTimeout (async)
t.originalFunctionApplier @ js-wrapper.js:2
setTimeout @ js-wrapper.js:2
setTimeout @ js-wrapper.js:2
(anonymous) @ /opt/teams-for-linux/resources/app.asar/app/browser/notifications/activityManager.js:37
Promise.then (async)
watchSystemIdleState @ /opt/teams-for-linux/resources/app.asar/app/browser/notifications/activityManager.js:25
(anonymous) @ /opt/teams-for-linux/resources/app.asar/app/browser/notifications/activityManager.js:37
setTimeout (async)
t.originalFunctionApplier @ js-wrapper.js:2
setTimeout @ js-wrapper.js:2
setTimeout @ js-wrapper.js:2
(anonymous) @ /opt/teams-for-linux/resources/app.asar/app/browser/notifications/activityManager.js:37
Promise.then (async)
watchSystemIdleState @ /opt/teams-for-linux/resources/app.asar/app/browser/notifications/activityManager.js:25
(anonymous) @ /opt/teams-for-linux/resources/app.asar/app/browser/notifications/activityManager.js:37

```

**Comment by IsmaelMartinez** [comment] 2024-05-03 05:07
Can you try https://github.com/IsmaelMartinez/teams-for-linux/releases/tag/v1.4.35 and see if that fixes your issue? Thanks

**Comment by mdallaire** [comment] 2024-05-03 13:41
> Can you try https://github.com/IsmaelMartinez/teams-for-linux/releases/tag/v1.4.35 and see if that fixes your issue? Thanks

This seems to have fixed it for me! Thanks!

**Comment by Crescent-Saturn** [comment] 2024-05-03 15:02
> Can you try https://github.com/IsmaelMartinez/teams-for-linux/releases/tag/v1.4.35 and see if that fixes your issue? Thanks

I try with the latest version and it seems to me this issue has been fixed. :rocket: 
Thank you!

**Closed** 2024-05-03 18:29 UTC
Labels: enhancement
