### ISSUE TITLE
Phone notification

### ISSUE THREAD

**Issue by rkozlo** [IsmaelMartinez/teams-for-linux#727] opened 2023-04-06 13:56 UTC
Hi,
lately i ran into weird "bug" or something that i got phone notification about incoming messages even thou i am typing in that chat on desktop.
Any ideas/solution? 
My spec:
openSUSE Tumbleweed
DE: KDE 5.104.0 / Plasma 5.27.3
Wayland

**Comment by acshearer** [comment] 2023-04-06 17:05
+1 I had to disable notifications on my phone, was getting very annoying.

**Comment by jijojosephk** [comment] 2023-04-15 17:05
@rkozlo This looks like an issue with web app itself. I would close this for now, if you think it can be fixed here, please re-open.

**Comment by Sajito** [comment] 2023-04-19 08:08
Having the same issue here too.

I don't think the issue is with the web app itself, because it's working fine when using the web app in the browser. Tried with Firefox and Microsoft Edge.
Having the issue since a few days, not sure when it started.

Specs:
EndeavourOS, KDE 5.105.0 / Plasma 5.27.4
team-for-linux v1.0.65

**Comment by rkozlo** [comment] 2023-05-15 07:33
> @rkozlo This looks like an issue with web app itself. I would close this for now, if you think it can be fixed here, please re-open.

What do you mean? If it would be related with web itself, problem wouldn't be global? By global i mean even opening teams directly from browser.

**Comment by jijojosephk** [comment] 2023-05-15 11:27
> > @rkozlo This looks like an issue with web app itself. I would close this for now, if you think it can be fixed here, please re-open.
> 
> What do you mean? If it would be related with web itself, problem wouldn't be global? By global i mean even opening teams directly from browser.

So you're saying the problems is not present in `google-chrome` or `edge`?

**Comment by rkozlo** [comment] 2023-05-15 12:27
Tested with chromium and didn't receive any phone notification. My coworkers have the same issue

**Comment by jijojosephk** [comment] 2023-05-15 14:05
I'm unable to reproduce this behaviour. If someone else can please shed some more details.

- A is chatting with B on `teams-for-linux`
- A is also having teams installed on mobile. (Android tested)
- B is sending a message to A.
- A gets notification on mobile.

This is how it is currently in `google-chrome` during my test. I'm not sure if the scenario is something else.

**Comment by jijojosephk** [comment] 2023-05-15 14:17
@rkozlo probably this is what you would need to do.

https://td.byui.edu/TDClient/79/ITServicePortal/KB/ArticleDet?ID=11771

Scroll down to see the mobile app settings both in android and ios. I believe this is not defect from `teams-for-linux`.

**Comment by jijojosephk** [comment] 2023-05-15 14:20
`iOS`
![image](https://github.com/IsmaelMartinez/teams-for-linux/assets/11662148/876fb9ac-e1db-468e-8e8b-f04e4a59ac33)

`Android`
![image](https://github.com/IsmaelMartinez/teams-for-linux/assets/11662148/a458a6ea-1f7d-4bc7-8aa5-f0cd5ca98cf8)

UI might look different based on the version of the app. It's basically a setting on the mobile app.

**Comment by Sajito** [comment] 2023-05-15 14:22
@jijojosephk I'm having the same issue. My settings are just like described in your link. When using teams in `firefox` or `edge` it's working fine, but not working with `teams-for-linux`.
When only `teams-for-linux` is active, notifications keep coming to the phone.

**Comment by jijojosephk** [comment] 2023-05-15 14:27
Can you confirm the version you're having. There was an issue with the user presence. User used be 'away' after sometime. Which was fixed few versions before. You must have a version greater than `1.0.60`

**Comment by Sajito** [comment] 2023-05-15 14:31
Should be latest version, currently running `1.0.88` from flatpak.

**Comment by jijojosephk** [comment] 2023-05-15 14:36
I don't know what changed but now flatpak version does not have the notification sound.

**Comment by Sajito** [comment] 2023-05-15 14:37
Can't install `rpm` or `deb`, I'm running an arch based distribution. I could try the AppImage or I'll try building from source.
But can't test today, will try tomorrow.

**Comment by rkozlo** [comment] 2023-05-16 05:26
> @rkozlo probably this is what you would need to do.
> 
> https://td.byui.edu/TDClient/79/ITServicePortal/KB/ArticleDet?ID=11771
> 
> Scroll down to see the mobile app settings both in android and ios. I believe this is not defect from `teams-for-linux`.

Nope. I did it long time ago because was using regular app from MS

**Comment by Sajito** [comment] 2023-05-16 05:35
@jijojosephk Just tested the AppImage and a build from source. Still getting notifications on my phone. As soon as I open teams in the browser, they stop. But after closing it in the browser again and having only `teams-for-linux` running, they start again.

**Comment by jijojosephk** [comment] 2023-05-16 05:57
> @jijojosephk Just tested the AppImage and a build from source. Still getting notifications on my phone. As soon as I open teams in the browser, they stop. But after closing it in the browser again and having only `teams-for-linux` running, they start again.

Instead of `firefox` and `edge` can you try `google-chrome` and report please?

**Comment by rkozlo** [comment] 2023-05-16 06:55
> Can you check if the same with 'rpm' or 'deb' ?

Tested with rpm. The same.


> > @jijojosephk Just tested the AppImage and a build from source. Still getting notifications on my phone. As soon as I open teams in the browser, they stop. But after closing it in the browser again and having only `teams-for-linux` running, they start again.
> 
> Instead of `firefox` and `edge` can you try `google-chrome` and report please?

As i said. I was testing with chromium and didn't get notifications. Test with chromium i treat as the same like with chrome

**Comment by Sajito** [comment] 2023-05-16 07:45
Clean installation of `google-chrome Version 113.0.5672.92`. Notifications not coming, while it's open. Browser closed, notifications coming to the phone again.

**Comment by Blaimi** [comment] 2023-06-15 14:21
I can confirm this issue. I switched from edge PWA to teams-for-linux, now I receive a notification on my android-mobile with every message. I checked the mobile settings, it still mentiones blocked when active on desktop

**Comment by jijojosephk** [comment] 2023-06-15 16:09
Okay, let's re-open and analyse further.

**Comment by SergeyKhrystenko** [comment] 2023-06-23 11:31
same issue. phone settings are exactly the same as on screenshots above, but getting notifications on my phone

**Comment by GrzegorzKozub** [comment] 2023-07-05 05:41
Same problem. Using Arch Linux and installed `teams-for-linux` from AUR. The mobile Teams app setting to block notifications when I'm active on desktop is enabled.

**Comment by jijojosephk** [comment] 2023-07-25 04:23
I know it's super annoying, but can't figure out why it's happening.

**Comment by NgoHuy** [comment] 2023-08-09 07:21
I have same issue on Archlinux, seem to status is away on teams-for-linux, but on browser, it's always available.

**Comment by IsmaelMartinez** [comment] 2023-08-22 20:35
by the way, I have the exact same issue using the official MacOS app and the mobile device. It is annoying but I think Microsoft do call it a feature. :/ I tend to log off my mobile when working (sometimes I even uninstall the app).

**Comment by ZeeHanzo** [comment] 2023-09-04 06:59
If you monitor network activity on the PWA, it makes calls to `https://presence.teams.microsoft.com/v1/me/reportmyactivity/`
Where is the presence logging in this app? I think it might be the issue here

**Comment by NgoHuy** [comment] 2023-09-12 06:41
> by the way, I have the exact same issue using the official MacOS app and the mobile device. It is annoying but I think Microsoft do call it a feature. :/ I tend to log off my mobile when working (sometimes I even uninstall the app).

But it doesnot appear on browser such as firefox, very strange. It worked as expected when firefox active and send notfication when away,

**Comment by NgoHuy** [comment] 2023-12-25 10:08
I see in devtool many error. I encrease timeout but no luck.
I changed user-agent to Edge and encreased timeout, and worked as expected 1 time: group I muted before, but not person message.

**Comment by IsmaelMartinez** [comment] 2024-03-21 10:37
closing this as it is a ms issue and we haven't had any new activity for a few months now.

**Closed by IsmaelMartinez** 2024-03-21 10:37 UTC
Labels: blocked
