### ISSUE TITLE
Clicking on URLs or card buttons doesn't do anything

### ISSUE THREAD

**Issue by peterjanes** [IsmaelMartinez/teams-for-linux#311] opened 2019-11-29 20:31 UTC
**Describe the bug**
Clicking on a link or card button doesn't do anything; in previous versions it opened the link in the default browser. (Control-click, middle-click, and right-click all work as expected.)

**To Reproduce**
1. Click on a link or button in a chat or team discussion.
2. Observe that the link is not opened in an existing browser (if running) or new browser (if not).

**Expected behavior**
The link should have been opened in the default browser.

**Desktop (please complete the following information):**
 - OS: Fedora 31
 - Installation package: snap
 - Version 1.0.0

**Additional context**
`xdg-open [link]` opens in the correct browser.

**Comment by IsmaelMartinez** [comment] 2019-12-01 16:06
Hi @peterjanes, was this working in 0.7.0? There where some changes for the handling of opening of links... So it might have broke that part. 
I will see if I can, at least, put the changes under a "config"option if I can confirm it use to work but isn't working anymore.

**Comment by peterjanes** [comment] 2019-12-02 18:47
It did work in 0.7.0. I couldn't right-click to copy a link in 0.7.0 but I can now, so it's not crippling (but I can't right-click on a card button, so I have lost a bit).

**Comment by IsmaelMartinez** [comment] 2019-12-04 16:23
I will try to have a look tonight but lately I have been pretty busy (and
Xmas is coming what makes it even busier). Microsoft is due to release
their client this month, so your problems might be solved by it (if it does
all the screen share etc).

**Comment by IsmaelMartinez** [comment] 2019-12-04 20:27
Hi @peterjanes, can you try with the deb package? I can see it working perfectly in the deb package and we didn't do any changes around that area, but snap did do some changes in general (for all packages) but they did `Grandfathering` the issue and was related to pulse-audio autoconnection.

**Comment by peterjanes** [comment] 2019-12-04 22:15
The RPM looks good. (I'd gone with the snap option to get automatic updates, rather than having to manually install new releases from here; guess I'll just subscribe!)

**Comment by IsmaelMartinez** [comment] 2019-12-04 22:36
Great! Maybe use flatpack if you want autoupdates (might do the trick). I
don't plan many updates as Microsoft should be hopefully providing a great
client and killing this project. We just need to wait. :)

**Comment by IsmaelMartinez** [comment] 2019-12-05 10:48
Closing as this only affects some snap installations and I, myself, don't actively support snap.

**Closed by IsmaelMartinez** 2019-12-05 10:48 UTC
