### ISSUE TITLE
Doesnt open on ubuntu 22.04

### ISSUE THREAD

**Issue by DGrothe-PhD** [IsmaelMartinez/teams-for-linux#599] opened 2022-09-20 17:43 UTC
**Does not open window on ubuntu**

**To Reproduce**
1. sudo snap command to install teams-for-linux - just today.
2. Opened it once, it worked. I could set up a meeting and check for camera and sound. I could also read existing chat messages and see online status = teams for linux seemed to work fine.
3. Saved icon to favorites on the ubuntu task bar.
4. Some hours later without doing anything, trying to reopen teams for linux again via task bar icon.
5. Teams for linux opens again after re-using the original teams app for a few seconds.

**Expected behavior**
When I click on the Teams task bar icon,Teams window opens and can be used.

**Observation**
No window is opening. On every click on that taskbar icon, this console message is printed:
`second-instance started
processArgs [
  '/snap/teams-for-linux/230/teams-for-linux',
  '--no-sandbox',
  '--enable-crashpad',
  '--allow-file-access-from-files'
]`

**Comment by jijojosephk** [comment] 2022-09-21 03:29
Probably you're having an older version. Could you confirm the version you have? snap was slightly behind the main release. The latest one is `1.0.38`

If you're having an older version run this:

`sudo snap refresh`

Let us know if you face the same issue even after moving to the latest version.

**Comment by jijojosephk** [comment] 2022-09-21 14:49
@DGrothe-PhD Could you confirm?

**Comment by jijojosephk** [comment] 2022-09-23 13:55
Closing this due to inactivity. You may re-open if any help is required.

**Closed by jijojosephk** 2022-09-23 13:55 UTC
Labels: question

**Comment by DGrothe-PhD** [comment] 2022-09-23 16:02
Sorry I cannot check this at the moment; I’ll try when I have time.

**Comment by DGrothe-PhD** [comment] 2022-09-24 14:12
My teams-for-linux is version 1.0.38, exactly. `sudo snap refresh` said snaps are up to date.

**Comment by jijojosephk** [comment] 2022-09-24 14:18
So are you saying that the issue is still there?

**Comment by DGrothe-PhD** [comment] 2022-09-25 14:42
Seems to work now (except for screen sharing, I have to wait for a meeting to test this.)
