### ISSUE TITLE
Have to sign in again on every launch

### ISSUE THREAD

**Issue by pszalanski** [IsmaelMartinez/teams-for-linux#6] opened 2018-10-26 12:03 UTC
Every time I open teams for linux from this fork it asks for my Microsoft credentials.

I even tried to start using `teams --partition persist:teams-linux`. It creates the corresponding folder and data in `~/.config/teams-for-linux`. However, I need to relogin every time I restart the Electron app.

I am using the git clone, which I then built with `yarn dist -l rpm` on my Fedora 28 machine using the Cinnamon Desktop.

Any idea what I might be doing wrong?

**Comment by IsmaelMartinez** [comment] 2018-10-27 14:41
Hi,

Yeah, I have seen this. I am not sure why is happening but I will investigate further and let you know.

I might end up reverting to persist but the ideal will be to make it configurable. I am not with my laptop at the moment but I will be back soon.

Feel free to pull request a fix if you find it... Maybe passing the actual value (config.partition) when generating the window instead of the config object make work (because object Vs reference stuff). Give it a try if you wish!

Thanks!

**Comment by IsmaelMartinez** [comment] 2018-10-28 21:40
I tried with my fix/suggestion and it seems to work! 

I have added the change in the branch 0.1.7 with a couple of other changes.

I need to test it tomorrow 1st thing in the morning and then I will create a pre-release. 

I will let you know once its available and you can then confirm it also works for you. (using the `--partition persist:whatever-you-like`) 

If you can't wait for it, you could get the branch 0.1.7 but still in testing (it should work but can't warranty until I finish testing tomorrow).

reference/value .... keeps biting me back every now and then.

**Comment by pszalanski** [comment] 2018-10-29 07:46
Thank you for checking this out so quickly.

So I tested the fix in branch 0.1.7, but it did not fix the persistence issue.

Additionally, switching the user agent does not seem to work anymore. I used it to mimic the edge browser, so video calls are enabled. That does not work anymore.

**Comment by IsmaelMartinez** [comment] 2018-10-29 11:49
Hi, 

I just reverted the changes that where disabling the user agent. As I mention, the branch is still a WIP.

Could you check again? I will change the browser to edge only (with mentions) if I get it all working in a future release.

Apologies if this caused any confusion.

Cheers!

**Comment by IsmaelMartinez** [comment] 2018-10-29 12:09
I have create a pre-release that is working on my machine and a few colleagues. 

https://github.com/IsmaelMartinez/teams-for-linux/releases/tag/v0.1.7

Could you test if that fixes this issues?

ps: you might need to remove the `~/.config/teams-for-linux` folder, as you did before, if it doesn't seem to finish loading the 1st time.

**Comment by pszalanski** [comment] 2018-10-29 15:02
Sorry, it does not work. I removed the config folder, uninstalled my current rpm, installed the new rpm, launched using ` --partition`, signed in, launched with the same command line and it is still asking me to sign in :disappointed:

**Comment by IsmaelMartinez** [comment] 2018-10-29 17:09
@pszalanski , JamieMagee project always persist the session so it makes sense it doesn't have that issue as it doesn't try to provide that feature.

It seems like i

**Comment by IsmaelMartinez** [comment] 2018-10-29 22:12
Hi @pszalanski ,

I think the issue is related to "yargs" module. It seems like the implementation from ivelkov (never released) only work when using the development environment. Once you package it stops working. 

This is documented in "yargs" (https://github.com/yargs/yargs/blob/master/docs/api.md#argv).

I have made the change that they suggested and, as it was a pre-release, I have release it again with it.

I have test it now successfully in the packaged version (deb in my case), but I will wait until you confirm this is fix to close it.

ps: apologies, this keeps closing the issue. I had the project setup to do automations and keep doing it. I added now a "In Review" type so hopefully that sorts also that issue out.

Thanks!

**Comment by pszalanski** [comment] 2018-10-30 09:21
**Success**!

It works! But only if I launch with `--persist`. Can you make it the default behavior?

**Comment by IsmaelMartinez** [comment] 2018-10-30 09:32
Maybe in a future release but now, having the persist and been able to change the user agent, creates more problems that the ones that solves. (History disappearing, white screens...). I close this and, again, I will consider it again one I can get mentions to work with the edge user agent string.

**Closed by IsmaelMartinez** 2018-10-30 09:32 UTC

**Comment by IsmaelMartinez** [comment] 2018-11-01 15:10
@pszalanski , version [0.1.9](https://github.com/IsmaelMartinez/teams-for-linux/releases/tag/v0.1.9) persists the session by default (and a couple of other improvements.

Hope helps

**Comment by pszalanski** [comment] 2018-11-02 10:22
Yes it did! It works flawlessly now. Thank you!

**Comment by rubin55** [comment] 2019-08-16 23:30
@pszalanski I'm on your latest build (0.6.x) which I downloaded today. I am running on Ubuntu 19.04. Every time I have to re-authenticate and am thinking that the authentication/creds are not saved. What can I do to debug? I'm running the .tar.gz version.

**Comment by IsmaelMartinez** [comment] 2019-08-17 11:20
Hi @rubin55 ,

Once you start the app, it should print the config folder location. That is normally `~/.config/teams-for-linux` 

Make sure you got access to that location. Also, I am not sure if it is supported. Have you tried any of the packaged versions? AppImage, snap, deb should work.

Thanks
