### ISSUE TITLE
"Open" from the tray menu does not focus the window

### ISSUE THREAD

**Issue by Niezoor** [IsmaelMartinez/teams-for-linux#81] opened 2019-03-25 16:18 UTC
If the application window is already open, clicking "Open" in the tray menu does not focus on the application window.

Tested on Ubuntu 16.04

**Comment by IsmaelMartinez** [comment] 2019-03-25 17:10
Hi, 

Does this happen when the app is minimised, close, in the background (under another app) or always?

Thanks

**Comment by IsmaelMartinez** [comment] 2019-03-25 21:33
Also, can you provide more information about what have you install the application with? deb, tar.gz, AppImage, snap, running from source...

Can you run it from the command line `teams-for-linux` and see if you get any log messages? You might need to look in `/var/log/syslog` (or whatever your linux put the syslogs/messages)

**Comment by Niezoor** [comment] 2019-03-26 08:35
Hi,

This problem always occurs when application in the background (under another app).
When the application is minimized, it works correctly only at the first time.
It always works correctly when application widow is closed/hided.

I installed application using snap.

My log shows only:
realpath: '': No such file or directory
realpath: '': No such file or directory
realpath: '': No such file or directory
realpath: '': No such file or directory
realpath: '': No such file or directory
realpath: '': No such file or directory
realpath: '': No such file or directory
realpath: '': No such file or directory
Gtk-Message: Failed to load module "canberra-gtk-module"
Gtk-Message: Failed to load module "canberra-gtk-module"

Thanks

**Comment by IsmaelMartinez** [comment] 2019-03-26 10:10
Can you try with the deb package or running from sources? Just to rule out is not a snap package issue (permissions etc)

**Comment by Niezoor** [comment] 2019-03-26 10:52
The same happens after install from deb package and running from sources.

**Comment by IsmaelMartinez** [comment] 2019-03-26 20:42
I keep it open and see if someone else is having this issue. I got Ubuntu 18.04 and works in the cases.

**Comment by alexeiskachykhin** [comment] 2019-03-29 04:32
@IsmaelMartinez I'm having the same issue on both Ubuntu 18.04 and 16.04. Steps to reproduce:

1. Launch the application
2. Minimize the application by clicking on its icon in a taskbar
3. Click Open in a tray

No errors are logged to a terminal or chrome dev tools, it just doesn't work.

It looks like there might be a straight forward fix for it in `menus/index.js`:

```
	open() {
		this.window.focus();
	}
```

It fixes a problem for me and a window gets predictable restored.

**Comment by IsmaelMartinez** [comment] 2019-03-29 07:24
Hi @alexeiskachykhin , 

Thanks for the PR and for investigating the issue. It's a strange one as it works fine in my environment but I am using Kubuntu.

I will test that in my environment as soon as I can (but I am with limited internet access at the moment) and accept the PR.

Maybe @julian-alarcon or @benyanke can do that before me. 

Thanks again!!

**Comment by IsmaelMartinez** [comment] 2019-04-04 08:06
closing as it is now in master, ready for release. Might be able to release something next week

**Closed by IsmaelMartinez** 2019-04-04 08:06 UTC
Labels: bug, snap

**Comment by IsmaelMartinez** [comment] 2019-04-09 21:00
Sorry but looks like the packaged "release" will need to wait until the end of the month (life commitments).

If you are using snap, you an use the edge branch (that is the current source, or at least got your changes). 

Apologies!

**Comment by IsmaelMartinez** [comment] 2019-04-13 08:29
Managed to release yesterday . Thanks again for your contribution!!

**Comment by alexeiskachykhin** [comment] 2019-04-13 14:34
Hi Ismael,

Thank you for letting me know. Have a great weekend.

Get Outlook for Android<https://aka.ms/ghei36>

________________________________
