### ISSUE TITLE
Trayicon stopped working on Unity

### ISSUE THREAD

**Issue by kaymes** [IsmaelMartinez/teams-for-linux#888] opened 2023-07-10 04:59 UTC
**Describe the bug**
Since the latest update to version "1.2.3 2023-07-09 (415)", the tray icon is no longer showing on Ubuntu Unity. 

It seems to still work on the normal Gnome Desktop. It used to work fine on the Unity Desktop until the teams snap updated to the latest version.

I reverted the snap to the previously installed version 1.1.11 which works fine and shows the tray icon as expected.

**To Reproduce**
1. Run Ubuntu Unity desktop, version 23.04
2. Install teams-for-linux 1.2.3
3. Launch it
4. Don't see a tray icon

**Expected behavior**
A tray icon should be shown

**Desktop (please complete the following information):**
 - OS: Ubuntu 23.04
 - Installation package: teams-for-linux snap 1.2.3 2023-07-09 (415)
 - Desktop: Ubuntu Unity

I'm happy to try other versions (if you tell me how) to work out where the braking change is.

**Comment by jijojosephk** [comment] 2023-07-10 05:38
You'll find the same problem with all sand-boxed environments like `snap`, `flatpak` etc. Workaround is to use native package from the releases page [1.2.3](https://github.com/IsmaelMartinez/teams-for-linux/releases/tag/v1.2.3). We're yet to figure the root cause. Probably something changed in the upstream `chromium` or even `electron` projects. If you want automatic updates you refer this: https://github.com/IsmaelMartinez/teams-for-linux#debianubuntu-and-other-derivatives

**Comment by jijojosephk** [comment] 2023-07-10 05:43
But one thing we're sure, `chromium` now supports only `KStatusNotifierItem`. If unity uses libappindicator, that's the obvious reason why you don't see it.

**Comment by kaymes** [comment] 2023-07-10 06:13
> But one thing we're sure, `chromium` now supports only `KStatusNotifierItem`. If unity uses `libappindicator`, that's the obvious reason why you don't see it.

Is this limitation a new thing? I couldn't find anything definitive on the topic but it could well be that KStatusNotifierItem support is missing. Is there an easy way to test this?

**Comment by jijojosephk** [comment] 2023-07-10 06:21
Can you check if this works? https://github.com/electron/electron/issues/38140#issuecomment-1619218462

**Comment by kaymes** [comment] 2023-07-10 06:36
Launching ths snap package version 1.2.3 from a terminal via `XDG_CURRENT_DESKTOP="" teams-for-linux` solves most of it: an icon shows up in the tray and it is functional (i.e., the menu pops up, I get notifications for new messages, etc.). 
However, the icon itself is a generic one, not the usual purple teams logo.

**Comment by jijojosephk** [comment] 2023-07-10 16:08
> I just tried it. Launching the snap package version 1.2.3 from a terminal via `XDG_CURRENT_DESKTOP="" teams-for-linux` solves most of it: an icon shows up in the tray and it is functional (i.e., the menu pops up, I get notifications for new messages, etc.). However, the icon itself is a generic one, not the usual purple teams logo.

The problem with icon could be something the workaround solution is not able to achieve. Will GNOME extensions work in Unity? I'm not familiar. We wanted to have the app built on the latest electron, that's why we did the upgrade. This KSNI thing is something all DEs should now be implementing or to be supported by some extensions.

**Comment by kaymes** [comment] 2023-07-10 22:36
I just installed the version from the .deb repository which is still 1.2.2. Started with the workaround `XDG_CURRENT_DESKTOP="" /usr/bin/teams-for-linux` the tray icon comes up correctly. 

So it's either a regression that happened between 1.2.2 and 1.2.3 or it's an issue with the snap sandbox.

**Comment by jijojosephk** [comment] 2023-07-11 02:48
The problem is with sandbox.

**Comment by kaymes** [comment] 2023-07-11 02:58
I found this Electron bug and added some more information about the XDG_CURRENT_DESKTOP issue: https://github.com/electron/electron/issues/38979#issuecomment-1630025534

**Comment by jijojosephk** [comment] 2023-07-11 05:08
> I found this Electron bug and added some more information about the XDG_CURRENT_DESKTOP issue: [electron/electron#38979 (comment)](https://github.com/electron/electron/issues/38979#issuecomment-1630025534)

Thanks. I just don't get why different DEs use different nomenclature for `XDG_CURRENT_DESKTOP`, if something had followed strictly, we could do something programmatically.

**Comment by jijojosephk** [comment] 2023-07-19 06:32
Is the right tray icon being rendered now?

**Comment by jijojosephk** [comment] 2023-07-20 07:24
Work around provided. Hence closing it. Please re-open if required.

**Closed by jijojosephk** 2023-07-20 07:24 UTC
Labels: known issue/workaround
