### ISSUE TITLE
Teams crash on phone call

### ISSUE THREAD

**Issue by Fedmahn99** [IsmaelMartinez/teams-for-linux#1388] opened 2024-09-02 08:08 UTC
Hi, when i try to call a number, the app close

If I launch the app from terminal with "teams-for-linux --webDebug --logConfig='{}'", when it crash it say : 

`09:59:12.288 › render-process-gone
09:59:12.288 › before-quit
09:59:12.289 › window close
09:59:12.297 › window closed
09:59:12.297 › will-quit
09:59:12.297 › quit
`

Some specs of my machine : 

OS: Arch Linux x86_64
Kernel: Linux 6.10.6-arch1-1
DE: GNOME 46.4
CPU: Intel(R) Core(TM) i5-8265U (8) @ 3.90 GHz
GPU: Intel UHD Graphics 620 @ 1.10 GHz [Integrated]

Regards

**Comment by GrzegorzKozub** [comment] 2024-09-02 08:54
I have a similar issue and i suspect this has to do with a camera and/or mic. When I disconnect my cam from the USB the issue cannot be reproduced anymore. However the same happens to me when using Teams on Brave so I suspect this is the Teams web app issue rather than teams-for-linux problem.

**Comment by Fedmahn99** [comment] 2024-09-02 09:08
Indeed, I have a similar issue with Teams in chromium (brave is based on chromium so). But I cannot disconnect my camera, it's a integrated one from a laptop :/

**Comment by IsmaelMartinez** [comment] 2024-09-02 18:33
Hi @Fedmahn99 and @GrzegorzKozub , It might be best to ask then in https://aur.archlinux.org/packages/teams-for-linux as they are the expert on arch packages (and are the ones that maintain that packaging).

That would be drivers, chrome or ms teams (I would think on that order). Maybe check the system logs to see if some driver is complaining.

Something that "could" help is running the app with --disableGpu , as this could be a gpu acceleration issue. See the config options in https://github.com/IsmaelMartinez/teams-for-linux/tree/develop/app/config 

Hope helps

**Comment by Fedmahn99** [comment] 2024-09-03 06:34
The logs with `teams-for-linux --appLogLevels debug `

> No config file found, using default values
> all good with appLogLevels you aren't using them
> Initialising logger with config: "{}"
> Logger initialised with transports: {}
> 
> 08:13:25.199 › Console logging enabled with level silly
> 08:13:25.200 › Logger initialised
> 08:13:25.200 › configPath: /home/mathieu.molinie/.config/teams-for-linux
> 08:13:25.200 › configFile: {}
> 08:13:25.205 › Running under Wayland, switching to PipeWire...
> 08:13:25.531 › processArgs: [ '/opt/teams-for-linux/teams-for-linux', '--appLogLevels', 'debug' ]
> 08:13:25.532 › testing RegExp processArgs false
> 08:13:25.533 › testing RegExp processArgs false
> 08:13:25.533 › testing RegExp processArgs false
> 08:13:25.534 › Testing network using net.request() for https://teams.microsoft.com/v2
> 08:13:25.536 › Spellchecker is disabled!
> 08:13:25.882 › Network test successful with method https
> 08:13:26.203 › GetSystemIdleState => IdleTimeout: 300s, IdleTimeoutPollInterval: 10s, ActiveCheckPollInterval: 2s, IdleTime: 0s, IdleState: 'active'
> [30446:0903/081326.204574:ERROR:object_proxy.cc(576)] Failed to call method: org.freedesktop.ScreenSaver.GetActive: object_path= /org/freedesktop/ScreenSaver: org.freedesktop.DBus.Error.NotSupported: This method is not part of the idle inhibition specification: https://specifications.freedesktop.org/idle-inhibit-spec/latest/
> 08:13:26.849 › did-frame-finish-load {} true
> 08:13:26.850 › did-finish-load
> 08:13:28.712 › Badge count set to '0'
> 08:13:28.737 › Badge count set to '0'
> 08:13:29.881 › Badge count set to '0'
> 08:13:32.525 › did-frame-finish-load {} false
> 08:13:36.235 › GetSystemIdleState => IdleTimeout: 300s, IdleTimeoutPollInterval: 10s, ActiveCheckPollInterval: 2s, IdleTime: 0s, IdleState: 'active'
> 08:13:46.297 › GetSystemIdleState => IdleTimeout: 300s, IdleTimeoutPollInterval: 10s, ActiveCheckPollInterval: 2s, IdleTime: 0s, IdleState: 'active'
> 08:13:47.546 › render-process-gone <---- when the app crash
> 08:13:47.546 › before-quit
> 08:13:47.546 › window close
> 08:13:47.550 › window closed
> 08:13:47.551 › will-quit
> 08:13:47.551 › quit
> 

Tried to run with wayland flag, no success either.

**Comment by IsmaelMartinez** [comment] 2024-09-03 13:38
Hi @Fedmahn99 , If you try one of the newest versions, the render-process-gone will print the error reason. Can you do that and include the logs again? https://github.com/IsmaelMartinez/teams-for-linux/releases/tag/v1.9.6 (or 1.10.0 if you prefer) 

The screensaver error seems to be similar to this one https://askubuntu.com/questions/1510794/chrome-124-hangs-doesnt-attach-to-wayland . you can pass the same flag.

Last, but not least, if you try to do it in a chromium browser, do you get the same issue? Thanks

**Comment by Fedmahn99** [comment] 2024-09-04 08:08
with 1.9.6 : 

> 10:06:52.925 › GetSystemIdleState => IdleTimeout: 300s, IdleTimeoutPollInterval: 10s, ActiveCheckPollInterval: 2s, 
> IdleTime: 0s, IdleState: 'active'
> 10:07:03.806 › GetSystemIdleState => IdleTimeout: 300s, IdleTimeoutPollInterval: 10s, ActiveCheckPollInterval: 2s, IdleTime: 0s, IdleState: 'active'
> 10:07:05.013 › Badge count set to '0'
> 10:07:05.474 › render-process-gone {"reason":"killed","exitCode":9}
> 10:07:05.475 › before-quit
> 10:07:05.476 › window close
> 10:07:05.496 › window closed
> 10:07:05.498 › will-quit
> 10:07:05.499 › quit

Does it help ?

**Comment by Fedmahn99** [comment] 2024-09-09 14:19
I don't understand how the chrome browser affect this. But the bug is affected all teams launch via a chrome base web browser. Aur package, flatpak, ntive chromium, all the same.

Only one is currently working, ironically : teams in firefox. I think it is using the electron package from the official arch repository.

**Comment by IsmaelMartinez** [comment] 2024-09-09 15:05
this app is a wrapper around a chrome browser (chromium) with some extras. If the issue happens in chrome, then the problem is around that area. Meaning you will do better by asking on those forums rather than in here. It smells like a drivers issue tbh. Hope you find the solution but there isn't much we can do in here, so closing the issue to keep the amount of issues manageable.

**Closed by IsmaelMartinez** 2024-09-09 15:05 UTC
