### ISSUE TITLE
White screen

### ISSUE THREAD

**Issue by harridu** [IsmaelMartinez/teams-for-linux#914] opened 2023-08-08 05:08 UTC
**Describe the bug**
Sometimes T4L just turns into a white empty space, unrelated to some suspend or hibernate mode. It seems to happen out of the blue. Workaround is to kill teams and start over.

T4L is version 1.3.0

**Comment by jijojosephk** [comment] 2023-08-08 06:16
Can you share some logs?

**Comment by janitza-anso** [comment] 2023-08-08 12:53
I am having the same problem. Here is my complete log from the Chrome Console.
[teams.microsoft.com-1691498959931.log](https://github.com/IsmaelMartinez/teams-for-linux/files/12291426/teams.microsoft.com-1691498959931.log)

And this are the errors right before the void page:
![image](https://github.com/IsmaelMartinez/teams-for-linux/assets/98828801/ad9da7e9-ff97-40e9-a621-395211191029)

I think the cause is the last error because the errors before are repeating.

**Comment by jijojosephk** [comment] 2023-08-08 14:12
Can you check `1.3.1` ?

**Comment by storm9c1** [comment] 2023-08-09 03:37
This is also happening to me.  I upgraded to 1.3.1 and will report back if it keeps happening.

**Comment by jijojosephk** [comment] 2023-08-09 05:07
> This is also happening to me. I upgraded to 1.3.1 and will report back if it keeps happening.

This `[DEBUG] render-process-gone` should be fixed in `1.3.1`. @harridu can you test that one?

**Comment by janitza-anso** [comment] 2023-08-09 05:11
> Can you check `1.3.1` ?

It seems 1.3.1 fixed this issue for me.

**Comment by jijojosephk** [comment] 2023-08-09 05:18
Closing as this issue seems fixed in `1.3.1`

**Closed by jijojosephk** 2023-08-09 05:18 UTC
Labels: question

**Comment by jijojosephk** [comment] 2023-08-12 04:14
What's done is a work-around. Created a defect here: https://github.com/electron/electron/issues/39476

**Comment by jijojosephk** [comment] 2023-08-12 09:55
We'll downgrade the electron. Check out version `1.3.2` when it's available.
