### ISSUE TITLE
Screen sharing on Tumbleweed does not work

### ISSUE THREAD

**Issue by ChristoSnake** [IsmaelMartinez/teams-for-linux#687] opened 2023-02-28 14:06 UTC
**Describe the bug**
Screen sharing does not work on Tumbleweed.

**To Reproduce**
1. Start meeting.
2. Share screen (FHD, full screen)
3. No screen is shared

**Expected behavior**
Screen sharing should be initiated..

**Screenshots**
Not applicable.

**Desktop (please complete the following information):**
 - OS: OpenSUSE Tumbleweed 20230226
 - Installation package: rpm, courtesy of Thaodan
 - Version: teams-for-linux-1.0.47-51.1.noarch
 -  CPU: Intel(R) Core(TM) i7-3740QM CPU @ 2.70GHz

**Additional context**
1. When starting from command line, the following warning/error is displayed:
christo@lenovo-t530:~> MESA-INTEL: warning: Ivy Bridge Vulkan support is incomplete
failed to open /usr/lib64/dri/hybrid_drv_video.so
Not using hybrid_drv_video.so
[978:0228/160044.142008:ERROR:nss_util.cc(349)] After loading Root Certs, loaded==false: NSS error code: -8018

2. When starting screen shared, debug shows the following:
0.2-angular-jquery.min-14969ec.js:114 2023-02-27T09:31:53.829Z [screenSharing][control] screenSharingControlService: unexpected, cannot find the call, teamsCallId [1]

0.2-angular-jquery.min-14969ec.js:114 2023-02-27T09:31:56.629Z callingAgents: calling-stack [JS.TsCalling.SignalingAgent] ffffffff: CSA[24634c42-1821-4d36-a0c5-93f7d8d9ddbf][Connected]/Broker _handleSubscriptionFailure failed, re-subscribing, {"response":16,"status":498,"statusText":"RequestAborted"}

3. Screen sharing works with Edge PWA, but not with Chromium PWA.  Might be related?

**Comment by IsmaelMartinez** [comment] 2023-03-01 21:42
I wonder if this is related to the magic @Thaodan is bringing?

Can you try with the rpm distributed in here just to ensure is not some config missing and/or requiring some tweaks? Thanks

**Comment by ChristoSnake** [comment] 2023-03-02 07:43
Thanks for the response!  The rpm here has libuuid & nss dependency issues Tumbleweed:

lenovo-t530:/data/Software/MS Teams/IsmaelMartinez # rpm -ihv teams-for-linux-1.0.49.x86_64.rpm
error: Failed dependencies:
        libuuid is needed by teams-for-linux-1.0.49-1.x86_64
        nss is needed by teams-for-linux-1.0.49-1.x86_64

... but there's a huge list of nss-related packages:

lenovo-t530:/data/Software/MS Teams/IsmaelMartinez # rpm -qa | grep nss
libnss_usrfiles2-2.27-3.11.x86_64
nss_synth-0.1.0~git2.ed6985d-2.1.x86_64
openssl-3.0.8-1.1.noarch
openssh-8.9p1-7.2.x86_64
libopenssl3-3.0.8-1.1.x86_64
libopenssl1_1-32bit-1.1.1t-1.1.x86_64
nss_wrapper-1.1.15-2.1.x86_64
openssh-server-8.9p1-7.2.x86_64
libjansson4-2.14-1.4.x86_64
nss-mdns-0.15.1-1.1.x86_64
mozilla-nss-certs-3.87-1.1.x86_64
openssh-askpass-gnome-8.9p1-7.2.x86_64
mozilla-nss-3.87-1.1.x86_64
mozilla-nss-sysinit-3.87-1.1.x86_64
nss-mdns-32bit-0.15.1-1.1.x86_64
libopenssl3-32bit-3.0.8-1.1.x86_64
libopenssl1_1-1.1.1t-1.1.x86_64
libxmlsec1-nss1-1.2.37-2.1.x86_64
libjansson4-32bit-2.14-1.4.x86_64
nss-pam-ldapd-32bit-0.9.12-1.8.x86_64
openssl-1_1-1.1.1t-1.1.x86_64
openssh-common-8.9p1-7.2.x86_64
openssl-3-3.0.8-1.1.x86_64
openssh-clients-8.9p1-7.2.x86_64
nss-pam-ldapd-0.9.12-1.8.x86_64
mozilla-nss-tools-3.87-1.1.x86_64

... and the same for libuuid:

lenovo-t530:/data/Software/MS Teams/IsmaelMartinez # rpm -qa | grep libuuid
libuuid1-2.38.1-7.1.x86_64
libuuid-devel-2.38.1-7.1.x86_64
libuuid-devel-static-2.38.1-7.1.x86_64

My guess is that I need to set up some links, bit I do not know where teams-for-linux expects them to be?  I will "--nodeps" install it and test it shortly.

**Comment by Thaodan** [comment] 2023-03-02 11:11
> lenovo-t530:/data/Software/MS Teams/IsmaelMartinez # rpm -ihv teams-for-linux-1.0.49.x86_64.rpm error: Failed dependencies: libuuid is needed by teams-for-linux-1.0.49-1.x86_64 nss is needed by teams-for-linux-1.0.49-1.x86_64
> 
> ... but there's a huge list of nss-related packages:

Why do you install the package with rpm and not with zypper?

**Comment by ChristoSnake** [comment] 2023-03-02 13:04
My best answer is "force of habit".  Will zypper make a difference to dependency handling?

**Comment by Thaodan** [comment] 2023-03-02 14:13
> BTW: Will zypper make a difference to dependency handling?

Yes, zypper will install dependencies that aren't installed rpm does not.

**Comment by Lomanic** [comment] 2023-03-08 17:51
@ChristoSnake  https://github.com/IsmaelMartinez/teams-for-linux/issues/687#issuecomment-1451429603 
> Thanks for the response! The rpm here has libuuid & nss dependency issues with my Tumbleweed:

Please see #521 where this is already reported (using zypper doesn't change anything, package names are different between RHEL and openSUSE), I had a workaround but I'm not sure if it's safe for RHEL-like distributions or in general as it forces users to have these dependencies manually installed.

**Comment by Thaodan** [comment] 2023-03-08 22:20
> > Thanks for the response! The rpm here has libuuid & nss dependency issues with my Tumbleweed:
> 
> Please see #521 where this is already reported (using zypper doesn't change anything, package names are different between RHEL and openSUSE), I had a workaround but I'm not sure if it's safe for RHEL-like distributions or in general as it forces users to have these dependencies manually installed.

The package is build for OpenSUSE and Fedora separately, in case there are issues in the spec file to sort of the differences between the two please report them to me.

If he installed the right rpm there are no dependency issues if you let your package manager install all dependencies, rpm will not fetch those, the dependencies are scanned during build.

**Comment by Lomanic** [comment] 2023-03-08 23:37
I guess you're talking about https://build.opensuse.org/package/show/home:Thaodan:network/teams-for-linux because https://github.com/IsmaelMartinez/teams-for-linux/releases/tag/v1.0.52 doesn't provide Fedora or openSUSE specific rpms.

The broken deps issue comes from trying to install the rpms served in GitHub releases, as suggested in https://github.com/IsmaelMartinez/teams-for-linux/issues/687#issuecomment-1450886198, not the builds from OBS.

**Comment by ChristoSnake** [comment] 2023-03-09 07:56
Indeed, guys!  To summarise:

- Package https://build.opensuse.org/package/show/home:Thaodan:network/teams-for-linux can be added as a repository, has no dependency issues & can be updated using a simple zypper dup command.  But its screen sharing does not work.
- Package https://github.com/IsmaelMartinez/teams-for-linux/releases/tag/v1.0.52 requires has no repository, requires a manual download & has dependency issues.  But ignoring the deps when installing allows for a working screen share.

I've gone for the second option - I require screen sharing on a daily basis...

**Comment by Thaodan** [comment] 2023-03-09 10:49
> * Package https://build.opensuse.org/package/show/home:Thaodan:network/teams-for-linux can be added as a repository, has no dependency issues & can be updated using a simple zypper dup command.  But its screen sharing does not work.

I'm working on fixing that issue right now, the issue is likely inside the electron package of Suse.

PS: If you want to install rpm files use zypper it will also handle dependencies on plain files.

**Comment by ChristoSnake** [comment] 2023-03-09 12:40
> PS: If you want to install rpm files use zypper it will also handle dependencies on plain files.

Zypper can not resolve the package dependencies when installing the https://build.opensuse.org/package/show/home:Thaodan:network/teams-for-linux package.  As Lomanic commented, this is due to differences in package naming and the location of the .so files between the different distros.

lenovo-t530:/ # zypper in ./teams-for-linux-1.0.52.x86_64.rpm 
Loading repository data...
Reading installed packages...
Resolving package dependencies...

**Problem: nothing provides 'libuuid' needed by the to be installed teams-for-linux-1.0.52-1.x86_64**
 Solution 1: do not install teams-for-linux-1.0.52-1.x86_64
 Solution 2: break teams-for-linux-1.0.52-1.x86_64 by ignoring some of its dependencies

Choose from above solutions by number or cancel [1/2/c/d/?] (c): 2
Resolving dependencies...
Resolving package dependencies...

The following NEW package is going to be installed:
  teams-for-linux

1 new package to install.
Overall download size: 68.8 MiB. Already cached: 0 B. After the operation, additional 231.5 MiB will be used.
Continue? [y/n/v/...? shows all options] (y): y
Retrieving: teams-for-linux-1.0.52-1.x86_64 (Plain RPM files cache)                                                    (1/1),  68.8 MiB    
teams-for-linux-1.0.52.x86_64.rpm:
    Package header is not signed!

teams-for-linux-1.0.52-1.x86_64 (Plain RPM files cache): Signature verification failed [6-File is unsigned]
Abort, retry, ignore? [a/r/i] (a): i

Checking for file conflicts: ........................................................................................................[done]
(1/1) Installing: teams-for-linux-1.0.52-1.x86_64 ...................................................................................[done]

**Comment by ChristoSnake** [comment] 2023-03-16 07:31
Sadly not fixed - it won't acknowledge that nss & libuuid are already installed and requires a --nodeps switch.  I can't see a loss of functionality, but I have no idea which Teams features require those two packages.

**Comment by jijojosephk** [comment] 2023-05-04 08:36
@Thaodan is this something you can fix?

**Comment by Thaodan** [comment] 2023-05-04 09:43
> @Thaodan is this something you can fix?

Yeah. I already did fix it but I have to work on pushing the fixes to the official OpenSUSE electron package.

My branch of the package electron package with the fix can be found here:
https://build.opensuse.org/package/show/home:Thaodan:network/nodejs-electron

**Comment by jijojosephk** [comment] 2023-05-05 05:06
@Thaodan  I assigned this to you :smile: . Could you close when this done?

**Comment by jijojosephk** [comment] 2023-06-08 05:58
Is this done @Thaodan ? can we close?

**Comment by jijojosephk** [comment] 2023-07-02 03:46
Closing due to inactivity. Let us know if any help is needed.

**Closed by jijojosephk** 2023-07-02 03:46 UTC
Labels: openSUSE
