### ISSUE TITLE
Context menus / reactions not working after some time

### ISSUE THREAD

**Issue by elhennig** [IsmaelMartinez/teams-for-linux#651] opened 2022-12-07 10:52 UTC
I have a problem that occurred in the past few days: After some time context menus do not work anymore. For example I cannot sent the meeting confirmations from the calendar or send reactions (similes) to chat messages. It works again after restart of the app and I have no idea yet, what triggers the faulty behavior.

I am using the flatpak 1.0.45 version on Linux

**Comment by IsmaelMartinez** [comment] 2022-12-07 13:46
Hi @elhennig , this is strange. Can you check if using rpm or deb sorts this out? snap and flatpak can have "funny" behaviours sometimes.

**Comment by elhennig** [comment] 2022-12-07 15:19
It is really strange, in the official PWA from MS it works and in the Teams for Linux client it also works since I restarted it after posting my issue here. I will observe this a bit more and post my feedback here. Maybe this has been solved somehow on the server side...

**Comment by elhennig** [comment] 2022-12-08 13:32
I tried with the AppImage 1.0.46 and it shows the same behavior.

**Comment by IsmaelMartinez** [comment] 2022-12-10 10:51
Can you check your processes and see if the memory of the process is going up to 100% ? I wonder if it is related to #652 , but it could also be one of the many changes MS are doing to support the PWA

**Comment by jijojosephk** [comment] 2023-04-26 18:36
@elhennig is this still a problem?

**Comment by elhennig** [comment] 2023-04-26 19:57
Yes, unfortunately. For me this is an external app that wants to perform an SSO login.

**Comment by jijojosephk** [comment] 2023-05-12 03:08
@elhennig have you found any solutions? does the native package face the same challenge too? can you post a video of the issue?

**Comment by elhennig** [comment] 2023-05-12 07:07
Well, it works for me if I click very carefully on the text and sometimes it needs more than one try. 

The native package I do not use anymore, since it does not integrate into the windows management of Linux at all (I cannot display the window an all virtual desktops for example).

**Comment by jijojosephk** [comment] 2023-05-12 15:56
@elhennig I'm closing this since there's workaround and the problem is not with `teams-for-linux`. Report if you require further help. Thank you.

**Closed by jijojosephk** 2023-05-12 15:56 UTC
Labels: question
