### ISSUE TITLE
Open URLs in default browser

### ISSUE THREAD

**Issue by agncr** [IsmaelMartinez/teams-for-linux#453] opened 2021-08-16 07:03 UTC
**Is your feature request related to a problem? Please describe.**
When i open links in Teams (via Ctrl-LeftClick) it will open a new small window. Is it possible to open the link in the default browser? The official teams app opens the url in the default browser.
OS: Ubuntu 20.10
Version: 1.0.9
Installed via: .deb package

**Describe the solution you'd like**
Open the link via default browser.

**Describe alternatives you've considered**
-

**Additional context**
-

**Comment by IsmaelMartinez** [comment] 2021-08-18 05:43
Hi @agncr ,

Thanks for reporting this request.

Have you tried without the ctrl button been pressed?

That should open your link in your default browser, but electron has some "funny" ways sometimes.

The reason the ctrl click opens in that window is related to the tabs and integrations. Is a way to be able to authenticate with an external service but within the electron context.

For security reasons, you can't authenticate in your browser and then pass that to electron, the same way that is you have Firefox and Chrome you need to log in once for each browser.

Hope helps,
Ismael

**Comment by clsaclsa** [comment] 2021-08-18 12:45
I observe the same issue for a few days, but in a slightly different context:

I have always opened links by a simple left-click (without pressing Ctrl). So far they were handled by the default browser as expected.

Now i see a popup instead (translated):
```
Failed to open URI.
This location is not supported
about:blank#blocked
```
... which originates from the process "xdg-open about:blank#blocked".
Looks like some kind of protocol handling is broken or forbidden.
The debugger doesn't print anything related (checked "Console" and "Network").

Package: teams-for-linux-1.0.9.AppImage on Debian Sid with XFCE

**Comment by bugzy** [comment] 2021-08-18 18:02
I have the same problem. One thing to note though is that if you click on the top left menu grid and click on the other MS 365 apps such as Outlook, Word, or OneDrive, they open as expected in the default browser.

Package: teams-for-linux-1.0.9.rpm on Fedora 34 with KDE Plasma

**Comment by agncr** [comment] 2021-08-19 07:43
>Have you tried without the ctrl button been pressed?

Yep, that does nothing. The URL gets highlighted, but clicking and also double and triple clicking does nothing. Right clicking, copying URL and pasting it in a browser works though. I've also checked the console while clicking on URLs and there aren't any error.
(I do get a couple of TypeErrors, but those only appear, when i scroll inside a chat, change from Chat to Teams)

I'll try to install the .deb file in a clean Ubuntu Installation and check, if the same problem occurs there.

**Comment by agncr** [comment] 2021-08-19 08:51
Installed `teams-for-linux_1.0.9_amd64.deb` in a new VM (PopOS (Ubuntu) 20.10) and i see the same problem. Left Clicking on URLs is not working.

**Comment by Paul-Houser** [comment] 2021-08-23 23:13
I'm having the same problem. Left clicking a URL in teams opens Firefox pointed to `about:blank#blocked`.

I'm using teams-for-linux 1.0.9-1 from the AUR on Arch Linux with i3 WM.

**Comment by IsmaelMartinez** [comment] 2021-08-24 16:08
I suspect this is a change in Microsoft side (they did something similar last year). Can someone try an older version just to rule that out? Like version 1.0.7 or older. Apologies for not been more useful. No time available (not linux env available)

**Comment by agncr** [comment] 2021-08-25 06:39
I've installed 1.0.6 (no Package for 1.0.7) and it works. Left clicking on URLs opens my default browser.

**Comment by IsmaelMartinez** [comment] 2021-08-25 09:04
Thanks for testing. Then it must be related to the electron version increase.

**Comment by jijojosephk** [comment] 2021-08-25 09:15
@IsmaelMartinez on('new-window') is deprecated in latest versions in favour of setWindowOpenHandler. I haven't checked the code but if the previous event handler is used somewhere, we'd better upgrade to setWindowOpenHandler and see if it's working. I'll try that when I'm free.

**Comment by jijojosephk** [comment] 2021-08-25 09:27
Could someone explain the scenario a bit more? I trying to quickly reproduce the problem. I have a chat window with https://google.com when I click on that the browser opens but address bar has nothing. Is that the problem? or the browser is not opening at all?

**Comment by IsmaelMartinez** [comment] 2021-08-25 10:21
Worth checking reverting this change to see if it is related. 
https://github.com/IsmaelMartinez/teams-for-linux/commit/d7925bed899eaad76045ac36a3a08ac7627543f8#diff-fcd76a40df5a5907cd8b9cc625c4744dab419d131843252d7c8b961e7c6e92f1

For the "about:black" pages we had to open a new browserWindow in order to load the content. https://github.com/IsmaelMartinez/teams-for-linux/blob/develop/app/mainAppWindow/index.js#L134 I believe that was to allow the use of tab integrations (like github etc). That opens the login window in an electron window so we don't lose the session (as we can't share the session between electron and an external browser.

This is the function that handlers the new window https://github.com/IsmaelMartinez/teams-for-linux/blob/develop/app/mainAppWindow/index.js#L131 . It uses the [shell](electronjs.org/docs/api/shell) module to open the browser.

Otherwise, it could be a change in the security area on the electron (I am thinking of that because of the "block" mentioned in one comment) 

But I might be completely wrong and be something unrelated 👯‍♂️

**Comment by jijojosephk** [comment] 2021-08-28 03:15
1.0.10 is out as pre-release. Snap is available in edge channel.

**Comment by jijojosephk** [comment] 2021-08-28 03:18
@agncr You may download the appropriate package now and let us know if everything is ok.

**Comment by IsmaelMartinez** [comment] 2021-08-28 08:22
I will see if I can release it tonight.

**Comment by yaseen-mowzer-hexagon** [comment] 2021-08-30 12:17
Thanks for all your guys work! I was having the exact same issue and installing the `.deb` of the 1.0.10 pre-release fixed it for me. :tada:

**Comment by IsmaelMartinez** [comment] 2021-08-30 16:28
Released so closing. Thanks @jijojosephk for fixing this, and everybody involved for reporting and/or testing the solution.

**Closed by IsmaelMartinez** 2021-08-30 16:28 UTC
Labels: bug, ready

**Comment by rustyscottweber** [comment] 2025-05-01 23:58
It would appear that there has been a regression to this issue. Links that I open are opened in chrome, not the default browser for the system. Can we reopen this issue, or should we create a new one entirely?

**Comment by IsmaelMartinez** [comment] 2025-05-05 08:05
Hi @rustyscottweber , can you open a new issue? The app has changed quite a bit since this issue was created and sorted. Include as much info as possible. Thanks!
