### ISSUE TITLE
Faulty Calendar View in 1.4.12 (Appimage) and 1.4.10 (flatpak)

### ISSUE THREAD

**Issue by elhennig** [IsmaelMartinez/teams-for-linux#1116] opened 2024-02-22 08:40 UTC
With release 1.4.12 (Appimage Linux) I have the problem, that the calendar view "week" only shows the working days without weekend and entries are shown in the wrong day. So appointments and meetings from yesterday are shown in today's agenda in the week view.
I wonder if this is caused by some change in teams on the MS side or if this is related to the app version? Could this be caused by the change to V2 of Teams?

EDIT: The same is true for the flatpak version 1.4.10

**Comment by tlo8640** [comment] 2024-03-06 14:34
I can confirm this.
I'm using the rpmversion teams-for-linux-1.4.13-1.x86_64 on fedora 39
switching calendar view to work week solves this problem for the moment. week view moves calendar entries one day forward.
unfortunately I cannot say, when this problem started.

**Comment by elhennig** [comment] 2024-03-07 08:04
Yes the workaround seems to be, to use the work week view

**Comment by jijojosephk** [comment] 2024-03-11 10:23
Electron or chromium has to support.

**Comment by jijojosephk** [comment] 2024-03-12 01:39
Is this related to #1063 ?

**Comment by elhennig** [comment] 2024-03-12 06:53
No, I do not think so. The normal week view does not work and mixes up entries from different days and displays only 5 days. But this also shows Sundays. Yesterday, Monday, for example it showed the 5 days from Sunday to Thursday, but the entries from Monday were displayed in the Tuesday column.

**Comment by elhennig** [comment] 2024-03-12 09:08
Actually I cannot check this as the web version has been switched to Teams 2 (?) by my organization already. There I do have a new view besides Day, Work Week and Week: Agenda
All of them seem to works fine.

**Comment by tlo8640** [comment] 2024-03-12 16:41
For anybody with this problem, I would recommend to check the LANG and the LC_TIME Variable of the OS.
I have 
LANG="en_US.UTF-8"
LC_TIME="de_CH.UTF-8"
This make the Problem visible.  in all Teams-variants (Web, this package, teams over Citirx! and  the quite old ms provided debian package). I thiknk there is something with the handling of different week starts...
Perhaps the problems is in electron or in teams itself, but not in this repository here:
I didn't found the time to try different settings for LANG and LC_TIME, but I will try to find some minutes and will post the result here. 
In my Eyes it's not a bug what can be solved in this package

**Comment by elhennig** [comment] 2024-03-12 17:24
Does that also explain the faulty display in the week view where appointments are sorted into different days? In my case it is not only the week start.

**Comment by tlo8640** [comment] 2024-03-12 17:58
Yes, I think that's the reason for the (by one day) moved appointments in the calendar. Somehow, it wil lbe counted from week start for the right column to be visible or something like this...

**Comment by elhennig** [comment] 2024-03-13 06:34
In the Teams Developer Preview (activated in the menu - info, right top)  the display problem seems to be fixed.

Anyway, is there a plan or chance to provide Teams 2 interface in the app? Maybe it is a better idea to have this as discussion....

In my start script for teams I tried to set 
export LC_TIME="de_DE.UTF-8"
to the same value as $LANG (before it was empty)

For me this does **not** solve the issue with the calendar views.

**Comment by IsmaelMartinez** [comment] 2024-03-15 19:40
Hi @elhennig, my hope is to get some time to look into that react transition, but I had no time to look at it. Apreciate if anyone has time and can have a wee look.

Is only a few files where we "talk" to angular, to get notification count and a few other things. 

In here we disable some things (that I am not sure if they even do anything anymore) https://github.com/IsmaelMartinez/teams-for-linux/blob/aafed1c90a5a1ca81e45c152891f4add4cd66780/app/browser/index.js#L19 . In general anything around https://github.com/IsmaelMartinez/teams-for-linux/tree/aafed1c90a5a1ca81e45c152891f4add4cd66780/app/browser can be affected, but looks like the documentation on that area is a bit lacking, so a great opportunity for refactoring. 

Regarding your issue, it looks more of a locale configuration issue (probably OS specific rather than package specific). This reminds me on an old issue (so maybe check the closed issues). If I was you, I would look for other electron apps that use calendar. Maybe one of the outlook electron apps or similar. See if you have the same issue, as if that is the case then is again a system/OS config. Otherwise trying other packaging systems can help you narrow the issue down.

If it is any consolation, I had a similar problem in macOS using the official app, but changed mac and has gone away. 

Tell us how you get on, but I am not sure what else to look at TBH. Hope you find a solution.

**Comment by elhennig** [comment] 2024-03-26 09:46
I guess this is caused by the switch to classic teams instead of using the new V2. See https://github.com/IsmaelMartinez/teams-for-linux/discussions/1141
For this I do not have a solution, yet.

**Comment by IsmaelMartinez** [comment] 2024-05-03 05:34
Hi @elhennig , is this still an issue? I do remember seen something odd in the macOS app that when away so just to confirm this wasn't a bugger in MS side and is now fixed. Thanks!

**Comment by tlo8640** [comment] 2024-05-03 07:13
With the "new" Teams I can (for myself) confirm, that there is no faulty calenar view anymore.
But I'm still looking for a way  to move the week starting day from sunday to monday
Using Teams (most recent version) on fedora 39

**Comment by IsmaelMartinez** [comment] 2024-06-11 05:44
closing as it looks like MS might have fixed this with teams-v2.

**Closed by IsmaelMartinez** 2024-06-11 05:44 UTC
Labels: known issue/workaround, blocked
