### ISSUE TITLE
Notifications come from wrong user

### ISSUE THREAD

**Issue by 31337-4554551n** [IsmaelMartinez/teams-for-linux#724] opened 2023-04-04 03:34 UTC
**Describe the bug**
When:
Conversation A is open in teams.
User is in a different program.
Message comes into conversation B.

The notification from the teams client comes through as though there was a new message in conversation A.

**To Reproduce**
As above

**Expected behavior**
The notification references the conversation the message came into-not the one you happen to have open

**Desktop (please complete the following information):**
 - OS: Pop OS 22.01
 - Installation package flatpak
 - Version 1.0.58

**Comment by jijojosephk** [comment] 2023-04-04 05:03
Though I'm not quite clear on the issue, if the focus is not in teams, I guess the notification should be shown. May be you can clarify a bit more.

**Comment by 31337-4554551n** [comment] 2023-04-04 06:09
Sure.
So I may be speaking with Bob, and have his conversation open.

I start working on something else, and teams is not in focus.

Michael will send me a message.
The notification from this app will read "From Bob" even though the message is from Michael.

This doesn't happen with the teams pwa.

**Comment by tom-dierckx** [comment] 2023-04-06 07:48
I also have this issue.
The chat you have open in the teams window will always be the user sending the notification in notifications, not the actual user sending the message.
- OS: Ubuntu 22.04.2
- Snap install 
- Version 1.0.55

**Comment by jijojosephk** [comment] 2023-05-02 02:20
I'm not able to reproduce this issue. Is it with group chat?

**Comment by 31337-4554551n** [comment] 2023-05-02 02:24
I'm experiencing it with regular 1v1 chats

**Comment by 31337-4554551n** [comment] 2023-05-24 07:31
Just wondering if anyone has had a chance to look at any of this?

**Comment by jijojosephk** [comment] 2023-05-24 08:59
Sorry, I tried and could not reproduce. I'll wait for someone else to find and fix.

**Comment by storm9c1** [comment] 2023-05-25 19:29
Sorry, I cannot reproduce this either.  I use Teams For Linux every day.  Never once seen this behavior.

Ubuntu 22.04 LTS
XFCE
Teams For Linux snap version 1.1.0

**Comment by aseligmann** [comment] 2023-06-13 07:26
@jijojosephk 
I believe what is referred to here is the "<window title> is ready" notification, where <window title> is usually the name of the conversation currently open.

Here's an example where I had opened a chat with myself, and received a notification from a different chat while unfocused:
![Screenshot from 2023-06-13 09-17-22_crop](https://github.com/IsmaelMartinez/teams-for-linux/assets/40468411/aa08bc7f-b401-4223-8be5-6b9749082c34)

I will occasionally get a "proper" notification showing the right chat and part of the received message, but the above type of notification is much more common on my system.

```
albert@albert:~$ snap list teams-for-linux
Name             Version  Rev  Tracking       Publisher       Notes
teams-for-linux  1.1.1    387  latest/stable  ismaelmartinez  -
```

**Comment by jijojosephk** [comment] 2023-06-13 09:03
This is really interesting. I don't get this problem and probably many others. But one thing I noticed, people who get this is having GNOME desktop.

**Comment by jijojosephk** [comment] 2023-06-13 11:53
@aseligmann 
Added additional log in the next release `1.1.3`. Kindly report when you have the latest build. 

start with `teams-for-linux --appLogLevels debug` and when you have a notification, you should see something similar below:

![image](https://github.com/IsmaelMartinez/teams-for-linux/assets/11662148/437ffacd-c7ad-418b-849e-a4cb5ed2167c)

**Comment by jijojosephk** [comment] 2023-06-13 11:56
What you see in the log and notification should be same, if they're not, something wrong with notifications implementation of GNOME or Microsoft did some logical mistake there.

**Comment by aseligmann** [comment] 2023-06-13 12:57
> @aseligmann Added additional log in the next release `1.1.3`. Kindly report when you have the latest build.
> 
> start with `teams-for-linux --appLogLevels debug` and when you have a notification, you should see something similar below:
> 
> ![image](https://user-images.githubusercontent.com/11662148/245465932-437ffacd-c7ad-418b-849e-a4cb5ed2167c.png)

Here's the GNOME notification:
![Screenshot from 2023-06-13 14-32-58_crop](https://github.com/IsmaelMartinez/teams-for-linux/assets/40468411/1a90437e-d51c-4319-bccb-e17c2b0c7b55)
 

Here's what I get in the log:
```
...
[DEBUG] GetSystemIdleState => IdleTimeout: 300s, IdleTimeoutPollInterval: 10s, ActiveCheckPollInterval: 2s, IdleTime: 0s, IdleState: 'active'
[DEBUG] Badge count set to '1'
[DEBUG] Notificaion => Type: new-message, Audio: default, Title: <redacted chat B>, Body: Not yet 👌
[DEBUG] Playing file: /snap/teams-for-linux/391/resources/assets/sounds/new_message.wav
[DEBUG] GetSystemIdleState => IdleTimeout: 300s, IdleTimeoutPollInterval: 10s, ActiveCheckPollInterval: 2s, IdleTime: 0s, IdleState: 'active'
...
```

It seems your suspicion is correct. 
However, it is worth noting that occasionally the notification shows correctly. Perhaps if several notifications arrive in "short" succession..?

**Comment by jijojosephk** [comment] 2023-06-13 13:08
@aseligmann Thanks for testing. I think it's due to multiple notifications from the same app. It makes me believe the problem is more with GNOME notifications. Do you think GNOME has some settings to ungroup the notifications? I'm on Ubuntu Budgie, for me all are individual notifications. We have some progress here  at least. . Thanks!

**Comment by aseligmann** [comment] 2023-06-14 06:47
@jijojosephk
Here are a few related issues from similar apps. Perhaps their discussion can be used for inspiration.
https://github.com/signalapp/Signal-Desktop/issues/5004
https://github.com/signalapp/Signal-Desktop/issues/3321
https://github.com/telegramdesktop/tdesktop/issues/8853

(For reference, I am on Ubuntu 20.04 with GNOME Shell 3.36.9.)

I've tried out using the following GNOME extension, which seems to help. 
https://extensions.gnome.org/extension/1007/window-is-ready-notification-remover/
However, with the extension, the notification are no longer added to the notification/date area like before. They show up and disappear, and are no longer visible anywhere else.
This is probably not in the scope of this project to fix, but it means that using the extension is not the _perfect_ solution even though it helps.

**Comment by jijojosephk** [comment] 2023-06-14 06:55
@tom-dierckx and @31337-4554551n could you please try the above? Thanks @aseligmann for your efforts!

**Comment by jijojosephk** [comment] 2023-06-14 09:48
Would this help? @tom-dierckx and @31337-4554551n 

https://github.com/telegramdesktop/tdesktop/issues/8853#issuecomment-711851968

**Comment by jijojosephk** [comment] 2023-06-15 04:18
Assume this can be fixed by GNOME notifications settings mentioned in the comment above. Hence closing. Thanks again @aseligmann

**Closed by jijojosephk** 2023-06-15 04:18 UTC
Labels: known issue/workaround, GNOME Desktop

**Comment by 31337-4554551n** [comment] 2023-06-15 04:27
> Assume this can be fixed by GNOME notifications settings mentioned in the comment above. Hence closing. Thanks again @aseligmann

Hi,

Are you referring to the extension mentioned above?
That breaks all notifications by not having them appear where they're supposed to, it's not really a fix. It just creates more problems than it solves.

Or are you referring to the telegram desktop comment? In which case that's referring to an option within the telegram software.

**Comment by jijojosephk** [comment] 2023-06-15 06:02
> > Assume this can be fixed by GNOME notifications settings mentioned in the comment above. Hence closing. Thanks again @aseligmann
> 
> Hi,
> 
> Are you referring to the extension mentioned above? That breaks all notifications by not having them appear where they're supposed to, it's not really a fix. It just creates more problems than it solves.
> 
> Or are you referring to the telegram desktop comment? In which case that's referring to an option within the telegram software.

I see, @aseligmann how can we disable `ready` notifications?

**Comment by jijojosephk** [comment] 2023-06-15 06:06
Is this causing the problem? `.flashFrame`

![image](https://github.com/IsmaelMartinez/teams-for-linux/assets/11662148/27ac182e-d1cf-404a-8c63-ea3b6dfc57e1)

**Comment by aseligmann** [comment] 2023-06-15 07:34
> > > Assume this can be fixed by GNOME notifications settings mentioned in the comment above. Hence closing. Thanks again @aseligmann
> > 
> > 
> > Hi,
> > Are you referring to the extension mentioned above? That breaks all notifications by not having them appear where they're supposed to, it's not really a fix. It just creates more problems than it solves.
> > Or are you referring to the telegram desktop comment? In which case that's referring to an option within the telegram software.
> 
> I see, @aseligmann how can we disable `ready` notifications?

@jijojosephk 
I am not very familiar with GNOME interfacing or the inner workings of this project to be honest, so I can't provide a good answer. From what others mention on the issues I linked to earlier, it is related to the `window-demands-attention` signal.

The extension ([source](https://github.com/nunofarruca/WindowIsReady_Remover/blob/master/windowIsReady_Remover%40nunofarruca%40gmail.com/extension.js)) that I linked to brute force disconnects the GNOME-wide listener for the relevant signals which cause the "X is ready" notification. And as @31337-4554551n mentioned, this workaround is unrelated to teams-for-linux.

**Comment by aseligmann** [comment] 2023-06-15 12:03
@jijojosephk 
`--disableNotificationWindowFlash` seems to work as intended in my limited testing.

**Comment by jijojosephk** [comment] 2023-07-04 08:34
@aseligmann @31337-4554551n @tom-dierckx can you update if the problem is resolved with the command line flag?

**Comment by aseligmann** [comment] 2023-07-04 10:36
> @aseligmann @31337-4554551n @tom-dierckx can you update if the problem is resolved with the command line flag?

If you are refering to `--disableNotificationWindowFlash`, then that seems to work for me

**Comment by jijojosephk** [comment] 2023-07-04 10:36
Thanks.

**Comment by aseligmann** [comment] 2023-07-07 07:51
> Thanks @aseligmann for the testing! If this fixes, may be we can disable the flashing for only GNOME desktops by default instead of passing as an argument.
> 
> Can you please help me with output of these commands in terminal?
> 
> ```shell
> $ echo $XDG_SESSION_DESKTOP
> ```
> 
> and
> 
> ```shell
> $ echo $XDG_CURRENT_DESKTOP
> ```

@jijojosephk If this is possible, then I believe it would be a neat solution. 

Currently I am setting some options through the `.config` file listed here: https://github.com/IsmaelMartinez/teams-for-linux/blob/develop/app/config/README.md#available-starting-arguments
As I am using the Snap version, the `current` symlink changes to point to a new folder every time the Snap updates, so I have to be mindful to manually update the config file if the snap updates.
I'm not aware of how to keep this file constant across versions, but perhaps you have some insight?
