### ISSUE TITLE
it doesn't remember language - spell check

### ISSUE THREAD

**Issue by eXt73** [IsmaelMartinez/teams-for-linux#895] opened 2023-07-18 07:18 UTC
As the title says = doesn't remember language - spell checker.

Start the program - enter the word in the chat bar > right mouse button and the previously selected language is still unchecked - it does not check the spelling.

 - OS: Kubuntu 22.04
 - Installation package [deb]
 - Version 1.2.5

![Screenshot_20230718_091213-1](https://github.com/IsmaelMartinez/teams-for-linux/assets/20760088/e0c71333-4960-4cfe-ac44-d606349915b9)

**Comment by jijojosephk** [comment] 2023-07-18 10:41
Duplicate of #867

**Closed by jijojosephk** 2023-07-18 10:41 UTC
Labels: duplicate
