### ISSUE TITLE
Tray Icon not displaying unread messages

### ISSUE THREAD

**Issue by jftempo** [IsmaelMartinez/teams-for-linux#536] opened 2022-06-17 08:08 UTC
Hi,
Sometimes the tray icon does not display the notifications (unread messages) until I click on the Team Window to put it in foreground, then all notifications are shown.
This is a random issue.

Could be linked to this error displayed in the console:
(teams-for-linux:134654): libnotify-WARNING **: 09:42:42.489: Failed to connect to proxy

I'm using v1.0.24 on Ubuntu 20.04 and XFCE.
Thanks.

**Comment by chrihoff** [comment] 2022-06-21 15:29
Same issue here actually and its a big problem for me. I also randomly don't get notifications if Teams is running in the background. When I put the Teams window into the foreground for some time, the notifications are displayed.

At least for me, this is a new issue that I started seeing about 1.5 weeks ago. The likely trigger is probably a change on the Microsoft side (changes in the HTML or the scripts).

Do you have any idea how I could debug this issue?

**Comment by IsmaelMartinez** [comment] 2022-06-24 08:36
I believe this is a limitation on electron and how it handles the "focus". Basically the browser still think is in focus when you got it minimised. Can you confirm this is basically what you are seeing? Basically, you would get notifications for the channel you are in, as it thinks you are "seeing it"

**Comment by chrihoff** [comment] 2022-06-24 09:20
Thanks @IsmaelMartinez for your ideas.

Meanwhile, I also started Teams in my browser (chromium) and noticed the exact same behaviour. I would expect the title of the browser tab to change to show e.g. "(1)" in the beginning of the window title if there is one new notification / message from someone. But this only happened once I put the browser tab in focus. The title didn't change as long as the browser tab was running in the background. In that sense, it is very similar to the problem I am now seeing with Electron.

Yesterday, I even saw the same problem with the official teams client from Microsoft for Linux: notifications were sporadically only visible after the Teams app was in focus.

Since I have observed the issue now on so many different clients (browser, teams-for-linux and the official Linux client), I am starting to suspect that its a new MS Teams issue. For now, I have enabled the developer preview of Teams (Settings -> About -> Developer Preview) to see if maybe the problem was fixed there.

**Comment by IsmaelMartinez** [comment] 2022-06-27 13:22
if it happens on the browser, then is MS issue. Apologies but little we can do from here :/ (Not the 1st time something liek this happens)

**Comment by jijojosephk** [comment] 2022-08-03 08:19
@jftempo @chrihoff what I found is that it's related to icon theme. Not sure how to fix.

**Comment by jijojosephk** [comment] 2022-08-06 04:03
Duplicate of #506

**Comment by Normand-Nadon** [comment] 2022-09-15 16:49
I can confirm that the tray icon **works as expected** both on the Flatpak and .deb version for me

**System:**
Pop!Os 22.04
Gnome 42.4 on X11

It might be system specific? Post your combination of OS, version, Desktop environement with version and Display manager... it might be helpfull for the devs :)

**Comment by jijojosephk** [comment] 2022-09-29 08:50
What I found is interesting. It has something to do with the binary name. `teams-for-linux` some how conflicts with icon theming. As far as I know this and #506 can't be fixed unless the binary name is changed.

**Comment by jijojosephk** [comment] 2022-09-29 08:50
It's not related to flatpak.

**Closed** 2023-03-22 14:47 UTC
Labels: bug, duplicate

**Comment by prettybits** [comment] 2023-07-10 13:06
FYI, thanks to the recent update to a newer Electron version I was for the first time able to see an unread message indicator on the tray icon on KDE, using the Tela icon theme and the Flatpak version of teams-for-linux. :)

**Comment by jijojosephk** [comment] 2023-07-10 16:01
> FYI, thanks to the recent update to a newer Electron version I was for the first time able to see an unread message indicator on the tray icon on KDE, using the Tela icon theme and the Flatpak version of teams-for-linux. :)

Also now other DEs started crying :rofl:
