### ISSUE TITLE
Teams keeps setting user to away when they are not

### ISSUE THREAD

**Issue by 31337-4554551n** [IsmaelMartinez/teams-for-linux#721] opened 2023-03-31 03:59 UTC
**Describe the bug**
Status is set to away unless a user is actively interacting with the teams window

**To Reproduce**
Use teams
Tab out and start using a different program
Teams sets you to away

**Expected behavior**
Teams keeps you as available unless you're fully afk or while the computer is unlocked

**Desktop (please complete the following information):**
 - OS: pop os 22.01
 - Installation package flatpak
 - Version 1.0.55 [edit] also applies to 1.0.58

**Comment by 31337-4554551n** [comment] 2023-03-31 04:44
I'm noticing that this is also happening with the teams pwa.
So perhaps this would be more of an enhancement-are you able to please program in something that triggers some insignificant thing in the client every couple of minutes to stop the away status bs unless the pc is locked?

**Comment by Lomanic** [comment] 2023-04-06 08:18
Duplicate of #577

**Comment by jijojosephk** [comment] 2023-04-15 01:25
@31337-4554551n and @Lomanic can you check if this issue is fixed in `1.0.60` ? Closing this as it's also duplicate of #577

**Closed by jijojosephk** 2023-04-15 01:25 UTC
