### ISSUE TITLE
Camera only visible in the preview - not for others

### ISSUE THREAD

**Issue by werner-kapferer-lgs** [IsmaelMartinez/teams-for-linux#909] opened 2023-08-01 05:54 UTC
**Describe the bug**
During calls:
Since a few days, my camera picture is only showing in my own preview on the bottom right and for everybody else black.
As the preview is working, I don't think it is hardware-related.
Note: I also use custom backgrounds which are displaying normally for me.

**To Reproduce**
1. Start a call/meeting.
2. Turn on camera.
3. Camera is visible for me in preview but not for others.

**Expected behavior**
Everybody in a call sees my camera picture.

**Screenshots**
(Tell me if a screenshot would help here and what it should show).

**Desktop (please complete the following information):**
 - OS:
 ```
Distributor ID: Ubuntu
Description:    Ubuntu 23.04
Release:        23.04
Codename:       lunar
```
 - Installation package: deb
 - Version 1.2.9

**Comment by jijojosephk** [comment] 2023-08-04 05:16
Sorry, I could not follow the description. Could you add some screenshots?

**Comment by werner-kapferer-lgs** [comment] 2023-08-04 06:47
![image](https://github.com/IsmaelMartinez/teams-for-linux/assets/88432915/64e237a4-b336-439e-bd6a-55143ed92ee7)
That's what I mean by "preview".
It was showing my camera picture with custom background correctly while the call partner only saw a black rectangle.

**Comment by werner-kapferer-lgs** [comment] 2023-08-04 07:29
> 1. When the custom background on were they able to see you with a black background or they can't see you at all?

I got two different answers here from my chat partners: It was partly working (with seeing the custom background and the camera) sometimes. When the problem appears, they see either a black rectangle or my profile picture without any camera content at all.

> 2. Is the problem with your own image or it is with Microsoft provided images also?

I normally don't use the default background images and only my own (sizes are the recommended 1920 × 1080 for image and 280 × 158 for thumbnails).

> 3. When you say the background can be turned on again, are you able to use custom backgrounds and the problem is not there? Like a temporary issue?

So I had the following workflow:

1. Custom background, working in my preview windows, not working for others.
2. Changing background to "Blur" or "None" and re-joining the call.
3. Others could now see "Blur" or "None" successfully.
4. Changing background back to the custom background and others see the custom background without problem.

After some time (days ?) it will break again and I have to re-do the mentioned procedure.

**Comment by jijojosephk** [comment] 2023-08-04 07:37
Thanks @werner-kapferer-lgs  for the details. I think the cache plays a role here. I'm not sure how can I reproduce as I don't use webcam and no background effects. We'll request others to try and reproduce.

**Comment by RolandRosenfeld** [comment] 2023-08-04 08:00
I observed the same yesterday in a meeting.  I entered a meeting and was told that my webcam shows black.
Someone shared his teams window with me, so I saw what was sent from my side.
I disabled camera, which resulted in showing my avatar image.
I enabled the camera and the black video stream was back.
Then I remembered that I read this issue here and that it could have to do with my background image.
I disabled the (custom) background and my original camera image was shown.
Then I re-enabled my custom background and everything works as expected.

No idea what the root cause is/was.
This was with 1.2.9 Debian package on Debian 12 (bookworm) with X11.

**Comment by jijojosephk** [comment] 2023-08-04 09:56
> I observed the same yesterday in a meeting. I entered a meeting and was told that my webcam shows black. Someone shared his teams window with me, so I saw what was sent from my side. I disabled camera, which resulted in showing my avatar image. I enabled the camera and the black video stream was back. Then I remembered that I read this issue here and that it could have to do with my background image. I disabled the (custom) background and my original camera image was shown. Then I re-enabled my custom background and everything works as expected.
> 
> No idea what the root cause is/was. This was with 1.2.9 Debian package on Debian 12 (bookworm) with X11.

Thanks. Good to know that the issue is not permanent.

**Comment by RolandRosenfeld** [comment] 2023-08-04 10:08
The problem is, that you do not notice yourself, that the issue is active, since the webcam-preview shows everything okay.  You have to wait until somebody else tells you, that there is no webcam stream but a black video...

**Comment by FelipeAngelini** [comment] 2023-08-07 14:21
I have the same problem here

**Comment by jijojosephk** [comment] 2023-08-21 09:47
We're not much in control of the problem. We'll have to stick to the work around provided by @RolandRosenfeld  and @werner-kapferer-lgs

**Comment by IsmaelMartinez** [comment] 2023-09-01 10:59
I think we can close this. This might be related to MS as I have seen similar situations with their own implementation/client. Meetings where I only see 1 person, but the rest sees everyone, background not available, background only loading on my preview but not others... (all in the official MS MacOS client). I suspect this one is on them.

**Closed by IsmaelMartinez** 2023-09-01 10:59 UTC
Labels: help wanted, good first issue
