### ISSUE TITLE
Tray (Notification) icon broken in MATE with snap images

### ISSUE THREAD

**Issue by storm9c1** [IsmaelMartinez/teams-for-linux#1155] opened 2024-03-25 19:20 UTC
**Describe the bug**
The tray icon appears broken when running from snap using MATE desktop.
The same icon works fine if installed via DEB package on MATE desktop.

**To Reproduce**
1. Switch to MATE desktop (can be installed with sudo apt-get install mate-desktop-environment)
2. Install teams-for-linux via snap
3. Invoke teams-for-linux either by menu or by /snap/bin/teams-for-linux, etc.
4. Note that a system tray (notification area, indicator, whatever people call it these days) has wrong icon

**Expected behavior**
The proper Teams icon should appear in the system tray (notification area, indicator area, etc)

**Screenshots**
MATE + snap: broken
![image](https://github.com/IsmaelMartinez/teams-for-linux/assets/16827398/ec873155-a1ab-431d-98b5-04d8087aabbf)

MATE + DEB: good
![image](https://github.com/IsmaelMartinez/teams-for-linux/assets/16827398/e650532b-40c9-4888-ad5e-a7aaff6a0d37)

MATE + DEB + snap running at same time: suddenly good
![image](https://github.com/IsmaelMartinez/teams-for-linux/assets/16827398/409c6c0b-bffc-4fb4-aa70-0ab1df4b3ce7)

**Desktop (please complete the following information):**
 - OS: Ubuntu 22.04 LTS
 - Happens on MATE desktop only, snap image only (XFCE, GNOME, Unity are fine, DEB is fine in all cases)
 - Installation package: snap
 - Version 1.4.14 (also tried 1.4.15 beta/edge, and also broken up to this point on older versions)

**Additional context**
Tried using workaround from other bugs (#506) to no avail.
Only happens with snap image.  DEB package has proper icon, as expected.
XFCE, GNOME, Unity also have correct icon when running the snap.  This is MATE only.

Additional testing:
Installing both DEB and snap at the same time, still broken icon running snap version only.
Running both DEB and snap at the same time, both icons suddenly appear correct.
Closing DEB version with snap version still running, snap icon reverts back to broken again.

**Comment by IsmaelMartinez** [comment] 2024-03-25 20:47
Hi,

On 1st impressions, this looks like a snap configuration issue. I would check around snap repo and see if there is something there. Otherwise I would suggest using one of the other packages. 

Alternatively, see if you can provide the icon using the appIcon config option (see https://github.com/IsmaelMartinez/teams-for-linux/tree/develop/app/config). Just download one of this https://github.com/IsmaelMartinez/teams-for-linux/tree/develop/app/assets/icons and see if that works for you. Use the full path. 

Snap tends to be iffy in many installations. Sorry about that.

**Comment by storm9c1** [comment] 2024-03-25 22:10
I prefer to use the snap at the moment.  And I'm forced to use a GNOME derivative (ie: MATE) otherwise I'd just use XFCE (my preference) and be done with it.  Gotta love how employers find ways to take something with unlimited potential and eliminate as much choice as possible.  Then again, I'm just happy to have a Linux option at all, and not to be forced onto Windows (which 95% of the company uses over Linux anyways).

That said, you gave me some breadcrumbs!

While using snap, I can only point `--appIcon` to something in it's own tree, so I tried pointing it to it's own icon (/snap/teams-for-linux/current/meta/gui/icon.png).  Doesn't help.

Next step was to try copying the DEB package icons into /snap/teams-for-linux/usr.  but I should know better, it's a read-only filesystem.  So next potential debug step was to copy the icon tree to $HOME/snap/teams-for-linux/current/.local/share/icons.  But in getting ready to do so, I noticed something alarming and possibly the root cause of the problem.  There's a bunch of existing (and broken) sym links there in `$HOME/snap/teams-for-linux/current/.local/share/icons`.  I looked on two different Ubuntu systems.

```
$ ls -algG hicolor/
total 4
drwxr-xr-x  2 4096 Mar 22 23:00 .
drwxr-xr-x 10  171 Mar 22 23:00 ..
lrwxrwxrwx  1   56 Mar 22 23:00 128x128 -> /snap/teams-for-linux/537/data-dir/icons/hicolor/128x128
lrwxrwxrwx  1   54 Mar 22 23:00 16x16 -> /snap/teams-for-linux/537/data-dir/icons/hicolor/16x16
lrwxrwxrwx  1   56 Mar 22 23:00 192x192 -> /snap/teams-for-linux/537/data-dir/icons/hicolor/192x192
lrwxrwxrwx  1   54 Mar 22 23:00 22x22 -> /snap/teams-for-linux/537/data-dir/icons/hicolor/22x22
lrwxrwxrwx  1   54 Mar 22 23:00 24x24 -> /snap/teams-for-linux/537/data-dir/icons/hicolor/24x24
lrwxrwxrwx  1   56 Mar 22 23:00 256x256 -> /snap/teams-for-linux/537/data-dir/icons/hicolor/256x256
lrwxrwxrwx  1   54 Mar 22 23:00 32x32 -> /snap/teams-for-linux/537/data-dir/icons/hicolor/32x32
lrwxrwxrwx  1   54 Mar 22 23:00 36x36 -> /snap/teams-for-linux/537/data-dir/icons/hicolor/36x36
lrwxrwxrwx  1   54 Mar 22 23:00 48x48 -> /snap/teams-for-linux/537/data-dir/icons/hicolor/48x48
lrwxrwxrwx  1   56 Mar 22 23:00 512x512 -> /snap/teams-for-linux/537/data-dir/icons/hicolor/512x512
lrwxrwxrwx  1   54 Mar 22 23:00 64x64 -> /snap/teams-for-linux/537/data-dir/icons/hicolor/64x64
lrwxrwxrwx  1   54 Mar 22 23:00 72x72 -> /snap/teams-for-linux/537/data-dir/icons/hicolor/72x72
lrwxrwxrwx  1   54 Mar 22 23:00 96x96 -> /snap/teams-for-linux/537/data-dir/icons/hicolor/96x96
lrwxrwxrwx  1   60 Mar 22 23:00 index.theme -> /snap/teams-for-linux/537/data-dir/icons/hicolor/index.theme
lrwxrwxrwx  1   57 Mar 22 23:00 scalable -> /snap/teams-for-linux/537/data-dir/icons/hicolor/scalable
lrwxrwxrwx  1   57 Mar 22 23:00 symbolic -> /snap/teams-for-linux/537/data-dir/icons/hicolor/symbolic

$ ls -al /snap/teams-for-linux/current/data-dir/icons/
total 0
drwxr-xr-x 2 root root  3 Jul 10  2019 .
drwxr-xr-x 5 root root 56 Jul 10  2019 ..

```

They point to an empty `icons` directory under `data-dir` in the snap tree.

If we populate this properly in the snap package, perhaps it will work?  Can this be fixed in the snap package at your convenience and then I can test it again.  Thanks!

**Comment by storm9c1** [comment] 2024-03-26 03:15
I tried to copy the DEB package's `hicolor` icon tree into `$HOME/snap/teams-for-linux/current/.local/share/icons` to see if that fixes the problem.  But that did not help.  Snap and apparmor were not happy.  I tried using --devmode to disable apparmor, but still no luck.  I would guess snap needs the proper directory structure under `/snap/teams-for-linux/current/data-dir/icons` for this to work.  Just copying that one directory in your home directory is not enough.

After copying, I also tried several permutations of using --appIcon too, no go.

Sorry, I don't know enough about this to help further.

**Comment by IsmaelMartinez** [comment] 2024-03-26 06:16
Can you try the workaround in #888 ? If MATE is a version of GNOME, I think this might just be the electron issue @jijojosephk has mentioned in the past

**Comment by storm9c1** [comment] 2024-03-26 15:43
Thanks for the suggestions.  Yes, unfortunately, before I filed the bug, I tried every workaround I could find in the TfL bug database related to tray icons, and a few on the internet, including that one.  I also tried different permutations of values (blank, GNOME, XFCE, etc)  for `XDG_CURRENT_DESKTOP`.  No luck.  This is why I didn't reopen or tack it onto #888 because it didn't seem to fit that same scenario.

Going from this assertion:
The tray icon does work in the snap under XFCE and Unity (GNOME3), and the known workarounds do not work for MATE.  

That tells me it's a icon resource location problem of some sort going on in the snap image.  Considering that MATE is a GNOME2 fork, and not GNOME3, it stands to reason that the missing resources from `data-dir` in the snap package could be to blame since those missing resources seem GNOME2-ish to me.

Also note that these files are present in the DEB package, which works fine.  Those are my thoughts, but I am no desktop environment expert.

Here's a list of all of the broken symlinks used by the snap package from `$HOME/snap/teams-for-linux/current/.local/share` pointing to empty directories in the snap tree.  These broken links seem to be created when TfL runs from snap, on a MATE desktop environment.

```
share/icons/Breeze_Snow/cursors -> /snap/teams-for-linux/537/data-dir/icons/Breeze_Snow/cursors
share/icons/Breeze_Snow/index.theme -> /snap/teams-for-linux/537/data-dir/icons/Breeze_Snow/index.theme
share/icons/DMZ-Black/cursor.theme -> /snap/teams-for-linux/537/data-dir/icons/DMZ-Black/cursor.theme
share/icons/DMZ-Black/cursors -> /snap/teams-for-linux/537/data-dir/icons/DMZ-Black/cursors
share/icons/DMZ-Black/index.theme -> /snap/teams-for-linux/537/data-dir/icons/DMZ-Black/index.theme
share/icons/DMZ-White/cursor.theme -> /snap/teams-for-linux/537/data-dir/icons/DMZ-White/cursor.theme
share/icons/DMZ-White/cursors -> /snap/teams-for-linux/537/data-dir/icons/DMZ-White/cursors
share/icons/DMZ-White/index.theme -> /snap/teams-for-linux/537/data-dir/icons/DMZ-White/index.theme
share/icons/Papirus-Adapta-Maia/index.theme -> /snap/teams-for-linux/537/data-dir/icons/Papirus-Adapta-Maia/index.theme
share/icons/Papirus-Adapta-Nokto-Maia/index.theme -> /snap/teams-for-linux/537/data-dir/icons/Papirus-Adapta-Nokto-Maia/index.theme
share/icons/breeze_cursors/cursors -> /snap/teams-for-linux/537/data-dir/icons/breeze_cursors/cursors
share/icons/breeze_cursors/index.theme -> /snap/teams-for-linux/537/data-dir/icons/breeze_cursors/index.theme
share/icons/default/index.theme -> /snap/teams-for-linux/537/data-dir/icons/default/index.theme
share/icons/hicolor/128x128 -> /snap/teams-for-linux/537/data-dir/icons/hicolor/128x128
share/icons/hicolor/16x16 -> /snap/teams-for-linux/537/data-dir/icons/hicolor/16x16
share/icons/hicolor/192x192 -> /snap/teams-for-linux/537/data-dir/icons/hicolor/192x192
share/icons/hicolor/22x22 -> /snap/teams-for-linux/537/data-dir/icons/hicolor/22x22
share/icons/hicolor/24x24 -> /snap/teams-for-linux/537/data-dir/icons/hicolor/24x24
share/icons/hicolor/256x256 -> /snap/teams-for-linux/537/data-dir/icons/hicolor/256x256
share/icons/hicolor/32x32 -> /snap/teams-for-linux/537/data-dir/icons/hicolor/32x32
share/icons/hicolor/36x36 -> /snap/teams-for-linux/537/data-dir/icons/hicolor/36x36
share/icons/hicolor/48x48 -> /snap/teams-for-linux/537/data-dir/icons/hicolor/48x48
share/icons/hicolor/512x512 -> /snap/teams-for-linux/537/data-dir/icons/hicolor/512x512
share/icons/hicolor/64x64 -> /snap/teams-for-linux/537/data-dir/icons/hicolor/64x64
share/icons/hicolor/72x72 -> /snap/teams-for-linux/537/data-dir/icons/hicolor/72x72
share/icons/hicolor/96x96 -> /snap/teams-for-linux/537/data-dir/icons/hicolor/96x96
share/icons/hicolor/index.theme -> /snap/teams-for-linux/537/data-dir/icons/hicolor/index.theme
share/icons/hicolor/scalable -> /snap/teams-for-linux/537/data-dir/icons/hicolor/scalable
share/icons/hicolor/symbolic -> /snap/teams-for-linux/537/data-dir/icons/hicolor/symbolic
```

**Comment by IsmaelMartinez** [comment] 2024-03-26 19:39
Let's see if @jijojosephk shares some light on that gnome issue and we can see if it is the same or something else. It could be that electron/or electron builders do not support MATE in the latest versions. Worth exploring either electron-builder or electron to see if there are other people with the same issue. They might have a workaround or something. I will see if I can have a look but I am quite limited these next few weeks

**Comment by IsmaelMartinez** [comment] 2024-03-26 19:50
This sounds similar. https://github.com/signalapp/Signal-Desktop/issues/6691

**Comment by storm9c1** [comment] 2024-03-27 01:02
> This sounds similar. [signalapp/Signal-Desktop#6691](https://github.com/signalapp/Signal-Desktop/issues/6691)

Thanks.  I'm not too sure it is the same.  In my case, the icon is reliably appearing with all desktop types, but only MATE shows a broken image.  Note that I can click on the broken image in the tray and get the normal TfL menu.

**Comment by hanlof** [comment] 2024-04-18 08:51
Hello. I am seing the same issue under xfce4.
Is teams-for-linux supposed to display a systray icon?

Can confirm that /snap/teams-for-linux/559/data-dir/icons/ is completely empty. This does not seem right? :open_mouth:

**Comment by storm9c1** [comment] 2024-04-19 14:46
Hi @hanlof -- actually the systray icon works under XFCE (Ubuntu 22.04) if you disable Ayatana Indicator Application under "Session and Startup".  Then reboot.

I also have libnotification-plugin and libsystray.so running (use ps -efww to verify).  I do know Ayatana conflicts with those.  I've read it elsewhere.

I'm staring at the icon in the systray on my XFCE desktop right now.  LOL.

Thus, I'm not sure if this is a TfL issue on XFCE.  But it could be an issue with latest (and multiple) systray/notification interfaces, I'm not sure.  Desktop Linux has a lot of variables in play.  And competing technologies.

I've determined that XFCE does not seem to need "data-dir/icons" to work properly.  It renders icons differently apparently.

I tried all of the same tricks with MATE and had no luck resolving with that desktop.  Since MATE is derived from GNOME2, I do wonder if the missing "data-dir/icons" is affecting that desktop only.  But I am not sure.  I know my way around XFCE more than GNOME.

**Comment by storm9c1** [comment] 2024-04-19 18:23
Also try installing the DEB package with XFCE.  If the tray icon still does not work, it's definitely NOT a TfL issue.

Only the snap image is affected on MATE.

The DEB package works fine for both desktops in my experience.  If an icon does not work after installing the DEB package (be sure to launch /usr/bin/teams-for-linux to get the DEB version), your systray/notifier app is the cause.  See my previous reply about Ayatana.

**Comment by hanlof** [comment] 2024-04-25 07:24
> Hi @hanlof -- actually the systray icon works under XFCE (Ubuntu 22.04) if you disable Ayatana Indicator Application under "Session and Startup". Then reboot.

Confirmed! This does make the teams icon show up in systray and thank you for that! 🙏

BUT, I do not see any numbers in systray indicating unread messages or indicating away/dnd/online/etc status. Perhaps those images are the missing resources. It can't be good to have those broken links.

**Comment by IsmaelMartinez** [comment] 2024-05-03 05:27
@hanlof , try moving to the latest available version and see if you can see the numbers, as this might be related to another already fixed issue related to MS moving from angular to react.

**Comment by storm9c1** [comment] 2024-05-03 14:07
Hi all.  The counter works fine for me.

I was running 1.4.31 and I can confirm with the DEB package, running under MATE.  Also confirmed working using the snap under XFCE (assuming the aforementioned steps have been taken).  Both cases on Ubuntu 22.04.  Just updated to 1.4.35 and it's still working.

SIde note, this can be easily tested by marking a chat message as unread buy clicking on a message, selecting "..." and then selecting "Mark as unread".  The counter should immediately appear or increment.

**Comment by IsmaelMartinez** [comment] 2024-05-28 05:05
closing as there is a known workaround provided. Do write back if the workaround is not working for you.

**Closed by IsmaelMartinez** 2024-05-28 05:05 UTC
Labels: snap, known issue/workaround

**Comment by IsmaelMartinez** [comment] 2024-05-28 16:38
aye, the workaround is not to use the snap package but to use the deb one. I know that might be a pain snap is really causing a lot of problems for a few people. 

I hope you understand. We are only a few (normally a couple) of people supporting this, and need to try to keep the number of issues to a manageable number. Specially as I do have a life/work to continue doing 😄 

I would recommend looking around apparmour specially if you aren't using a standard installation. By standard installation I mean anything that is not 'old school'. 

As an example, I do remember spending far too long to understand that apparmour wasn't properly working because my path wasn't `/home/my.name/` but `/home/domain.name/my.name`. I don't remember the solution for that but was something like re-initialising apparmour, but there was no error messages nor helpful information about it (something snap really needs to work on)

**Comment by storm9c1** [comment] 2024-05-29 05:59
Side note: the (latest) 1.5.0 upgrade using snap also breaks the running application icon under XFCE.  I will try the usual workaround to see if I can get it back (this will have to wait until next week).  The tray icon still works under XFCE, I'm talking about the running application icon now in the icon window and virtual desktop itself.  What a frustrating situation.

It's a shame because I much prefer using snap images, which are much more secure, especially for anything untrusted like a browser, and much more especially an app talking to Microsoft that probably tries to vacuum as much information as it can from your computer and send it off to the mother ship.

Anyways, this feels like icon resources are missing or lacking in the snap image.  Especially based on some of my previous findings regarding broken symlinks to icons in the snap package affecting MATE.

Unfortunately work/life balance is also preventing me from debugging this further.  If I come across anything, I'll update this thread.

**Comment by IsmaelMartinez** [comment] 2024-05-29 06:45
Aye, completely understand. Strange that the 1.5.0 breaks the running application icon. Both changes are behind a feature flag what probably means it is a configuration option with apparmour (or another snap part).

We do filter a lot of rubbish (see https://github.com/IsmaelMartinez/teams-for-linux/issues/1045#issuecomment-2025728184) - but we should probably leave some of those to call back home as it is breaking people login 😄 

We can re-open if you manage to find something.

**Comment by storm9c1** [comment] 2024-05-30 02:55
@IsmaelMartinez, thank you for filtering the "rubbish".  I didn't realize that.

(Oh, I posted a comment to that thread since that login issue hasn't been a major issue for me anymore since switching to Teams 2.0)

**Comment by storm9c1** [comment] 2024-06-10 18:29
> Aye, completely understand. Strange that the 1.5.0 breaks the running application icon. Both changes are behind a feature flag what probably means it is a configuration option with apparmour (or another snap part).

**Update**:  1.6.1 fixes the broken running application icon.
But the tray icon is still broken with MATE as originally reported (works fine with XFCE and GNOME).
